### ISSUE TITLE
Docker image fails on Apple silicone / M1

### ISSUE THREAD

**Issue by pwmcintyre** [swagger-api/swagger-codegen#11650]
##### Description

Unable to run via Docker on Apple silicone (arm / M1)

Example:
```shell
$ docker run --rm -it swaggerapi/swagger-codegen-cli
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Then my terminal crashes

##### Swagger-codegen version

"latest" on Dockerhub appears to be `2.4.25`

##### Steps to reproduce

On an Apple computer with an M1 processor — run
```
docker run --rm -it swaggerapi/swagger-codegen-cli
```

##### Related issues/PRs

https://github.com/swagger-api/swagger-editor/issues/2725

**Comment by pwmcintyre** [comment]
attempting to clone and build locally — the readme suggests i can use:
```
./run-in-docker.sh
```

WIP

**Comment by BenStirrup** [comment]
Any update ?

**Comment by danieleds** [comment]
also see this for a workaround: https://github.com/swagger-api/swagger-codegen/issues/11020#issuecomment-1022606350

**Comment by frantuma** [comment]
Thanks all for your patience, this has been fixed by the following changes adding multi-platform images builds:

[#12290, #12291, #12292, #12293, #12294](https://github.com/swagger-api/swagger-codegen/compare/d97e6c6343832554f66f7de1352b7b3d4f90843f..d249140100b38754f469907aaf01bb1aa2fecc56)

similar changes are being applied to 3.0.0 branch
