### ISSUE TITLE
Build fails on Mac, complaining about JAVA_HOME although it's set. Please revise documentation.

### ISSUE THREAD

**Issue by Stokestack** [swagger-api/swagger-codegen#11908]
##### Description

This is under Mac OS 11.7. Following the building instructions in the readme, I get:

```
% mvn clean package
The JAVA_HOME environment variable is not defined correctly,
this environment variable is needed to run this program.
```

But JAVA_HOME is defined, and points to where JDKs are:
```
% echo $JAVA_HOME
/Library/Java/JavaVirtualMachines
```

There are JDKs in that directory:
```
/Library/Java/JavaVirtualMachines % ls
jdk1.8.0_251.jdk	openjdk-8.jdk		openjdk.jdk
```

Here's what Java reports:
```
% java -version
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment Homebrew (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.2.1+1, mixed mode, sharing)
```

I even tried setting JAVA_HOME to point directly to /Library/Java/JavaVirtualMachines/openjdk.jdk, but Maven still gives the same error.

##### Swagger-codegen version
After 3.0.35, but I don't know because I don't know where that's specified in the source code.

**Comment by Stokestack** [comment]
OK, by pointing JAVA_HOME at the Contents/Home directory buried within the JDK, I could get the build kicked off. It fails with many other errors now, such as

[main] ERROR io.swagger.codegen.DefaultCodegen - unexpected missing property for name inner

But I'm not sure that's even the real problem amongst the copious output. In the end:

INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for swagger-codegen-project 2.4.29-SNAPSHOT:
[INFO] 
[INFO] swagger-codegen-project ............................ SUCCESS [  0.875 s]
[INFO] swagger-codegen (core library) ..................... FAILURE [ 19.418 s]

**Comment by mlemnian** [comment]
Hi @Stokestack, 
your issue is not directly related to this project, but to 
how to install java and use maven on MacOS.

If you have installed multiple JDKs (and JVMs) (not via sdkman!) for MacOS.
You can ask for all available JDKs (and JVMs) via:

```
/usr/libexec/java_home -V
```
It will also print out the current JAVA_HOME path at the bottom.

In my case:
```
Matching Java Virtual Machines (5):
    19.0.1, x86_64:	"Amazon Corretto 19"	/Library/Java/JavaVirtualMachines/amazon-corretto-19.jdk/Contents/Home
    17.0.2, x86_64:	"Amazon Corretto 17"	/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home
    16.0.1, x86_64:	"AdoptOpenJDK 16"	/Library/Java/JavaVirtualMachines/adoptopenjdk-16.jdk/Contents/Home
    11.0.17, x86_64:	"Amazon Corretto 11"	/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home
    1.8.0_352, x86_64:	"Amazon Corretto 8"	/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/amazon-corretto-19.jdk/Contents/Home
```

You can then switch JDKs via
```
export JAVA_HOME=`/usr/libexec/java_home -v YOUR_VERSION`
```

In my case e.g.
```
export JAVA_HOME=`/usr/libexec/java_home -v 17`
```

In your particular situation:

1. your JAVA_HOME was not correct in the beginning
2. it looks like, you have installed a JVM 1.8 to run java applets in the browser (which should be removed because java applets are usually not used anymore)
   * because of that, `/usr/libexec/java_home -v 1.8` could point to an invalid JVM


> I think this is unlikely to work in the vast majority of cases. 
This is not true, it will work with all Mac users, that have installed JDKs/JVMs via brew or as DMGs.

It will only not work if you have:
* installed JDKs only via sdkman
* no JDK installed at all
* installed the java applet runtime (which shouldn't be used anymore)

**Comment by Stokestack** [comment]
Thanks for the reply. I've never heard of "sdkman," so that's not a factor. And I don't recall ever having installed the Java applet runtime, so that most likely was installed by the old Oracle Java 8 installer that unfortunately many projects still apparently hard-code a dependency on. Given that many people developers will have installed this, I would expect the problem to occur reasonably often. But I understand that every project can't baby-sit the mess that Java installations have become.
