### ISSUE TITLE
CodegenOperation nonempty wrong

### ISSUE THREAD

**Issue by sverhagen** [swagger-api/swagger-codegen#1221]
All `getHasXxxParam` methods in `CodegenOperation` use the following:

    return nonempty(bodyParams);

They all use `bodyParams`, regardless the collection they are supposed to check, such as: `queryParams`, `headerParams`, `pathParams`.

As a result, any of these (`queryParams`, `headerParams`, `pathParams`) only show up if there are `bodyParams`.

**Comment by wing328** [comment]
@sverhagen thanks for reporting the issue. Agreed that these are bugs and we'll update that. 

I couldn't find anywhere in code in which the `getHasXxxParam` methods are used. If you've a spec that has issue using codegen due to this bug, please share with me so that I can try to repeat the issue. (even though these methods are not used, we should still fix it and again thanks for reporting the bug)

**Comment by sverhagen** [comment]
The `CodegenOperation` is available in the Mustache templating. Hence things like `{{#hasQueryParams}}` are broken, even in the `htmlDocs/index.mustache` that's part of the standard distribution.

**Comment by wing328** [comment]
@sverhagen you're right. It's done by this commit: https://github.com/swagger-api/swagger-codegen/commit/b14edffc795083ea13ff35e733069989ac042744

I'll file a PR to fix that.

**Comment by sverhagen** [comment]
I'm wondering if there's a workaround. I tried putting an alternative `io.swagger.codegen.CodegenOperation` on the classpath of the `swagger-codegen-maven-plugin`, but that seems not to work. I'd rather not have a temporary fork of the `swagger-codegen` in my environment.

**Comment by wing328** [comment]
@sankargorthi submitted #1225 to address the issue.

**Comment by sankargorthi** [comment]
@wing328 have I though?

**Comment by wing328** [comment]
@sankargorthi sorry for incorrectly tagging you in this thread.

**Comment by sankargorthi** [comment]
😎 it's cool.
