### ISSUE TITLE
basepath option not recognized when a server-stub is generated with Jax-rs

### ISSUE THREAD

**Issue by arthurMll** [swagger-api/swagger-codegen#1425]
Hello,

I have been trying to generate a server-stub from a swagger-model that I have create following the spec 2.0 and I found a little issue. All the server stub seems to generate the code according on what I was expecting except of that in the APIs each URL does not include the basepath I specified in my model.

I don't know if this is something which it has not been implemented yet or if I understood wrong the meaning of this field in described in the specification:

![base_path](https://cloud.githubusercontent.com/assets/10529210/10666113/f046e482-78cf-11e5-885f-1ad986859c61.png)

Thanks you very much in advance and congratulations to this community for the great job!

Arturo.

**Comment by wing328** [comment]
@arthurMll thanks for reporting the issue. I cannot find the use of `basePath` in jaxrs templates so your finding is likely correct.

Using [Petstore](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L17) as an example, the sample code for Jax-RS can be found at `samples/server/petstore/jaxrs` and `mvn jetty:run` will start the web server.

Given that the `basePath` is `v2` in the Petstore spec, where in the sample code would you add `basePath` to support `http://localhost:8080/v2/pet/1` instead of `http://localhost:8080/pet/1` ?

**Comment by arthurMll** [comment]
Hi @fehguy , thanks for replying. I am not so expert on the code-generator engine you have developed here, but what I did, in order to hot-fixing this issue in my already generated code, has been to directly add the basepath in the father path annotation of every API class, so in the pet store example would be to add:

@Path("/v2/pet")

**Comment by wing328** [comment]
@arthurMll thanks for sharing the fix. I've filed #1439 to fix it in master. Test result looks good.

**Comment by arthurMll** [comment]
@wing328 @fehguy  Great response guys! Thanks you very much.
