### ISSUE TITLE
C# dependency that is PCL friendly

### ISSUE THREAD

**Issue by chitankensuru** [swagger-api/swagger-codegen#1557]
Currently the C# client export has a dependency on RestSharp. I am working on a Xamarin PCL project and unfortunately RestSharp has no PCL implementation.

Could C# client export with PCL friendly libraries be added? That would be awesome.

**Comment by who** [comment]
@chitankensuru 

You may be able to use the C# .Net 2.0 generator for this.

I've used it to create clients for Unity projects.

https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/csharp-dotnet2/SwaggerClientTest/Lib/SwaggerClient

**Comment by chitankensuru** [comment]
The C# .Net 2.0 seems to be using RestSharp also.

**Comment by wing328** [comment]
@chitankensuru have you used https://github.com/FubarDevelopment/restsharp.portable before? would it meet your requirement ?

**Comment by chitankensuru** [comment]
@wing328 Tried that. Only in the generated ApiClient several functions are used from RestSharp.Extensions. Which I didn't find in RestSharp.Portable.

**Comment by wing328** [comment]
@chitankensuru thanks for trying. If those functions are replaced properly, then RestSharp.Portable can be used, right ?

**Comment by wing328** [comment]
@chitankensuru I've filed #1572 to remove dependency on RestSharp extension.

**Comment by wing328** [comment]
@chitankensuru PR merged into master. Please pull the latest master and give it a try.

**Comment by chitankensuru** [comment]
@wing328 Thanks for this. It partially solved the issue. We got it working by commenting out some parts in the ApiClient and Configuration file. And had to change RestClient.Execute and RestClient.ExecuteTaskAsync to RestClient.ExecuteAsync.

**Comment by wing328** [comment]
@chitankensuru no problem. Can you please show us the updated ApiClient and Configuration file in http://gist.github.com so that we can make the change in the templates?

For RestClient.ExecuteAsync, I cannot think of a workaround for the time being. We might need to add a switch in the command line just for that.

**Comment by wing328** [comment]
Closing this as there's no update.

**Comment by Gronsak** [comment]
I've ran into a similar problem recently when working with a asp.net core app and I concluded that Restsharp.Portable is a good replacement, compared to Restsharp it does some stuff differently though but I've managed to get it working on one of my generated api clients with minor modifications.

would it be possible to get this issue reopened?

**Comment by wing328** [comment]
@Gronsak I've reopened the issue. Ideally we want to support `RestSharp.Portable` via the `--library` option. May I know if you've time to contribute the enhancement?

**Comment by Gronsak** [comment]
It's a busy week so I don't have time right away but I'll take a look at what I can do during the weekend, I do not have a lot of experience working with java projects though so it could take me a couple of days to get up to speed.

**Comment by wing328** [comment]
No problem. Let us know if you need any help.

**Comment by johnamcruz** [comment]
Any update on this? I would love to use SwaggerCodeGen for my xamarin project.

**Comment by Gronsak** [comment]
@johnamcruz like I said, gonna work on this during the weekend since I don't have time during the week. It's now the weekend and I'm making a lot more progress than I thought I would (finally wrapped my head around java IDEs), I'll update you all on monday at the latest if I don't have it working sooner than that.

**Comment by Gronsak** [comment]
Okay so I got a working implementation, I'm missing the unit testing at the moment but I will have a look at that during the coming week.

I've opted for making it generate a .NET Standard Library project instead of a standard PCL project though, don't know if this is an unpopular choice but if I remember correctly the only real difference it makes is what version of VS you can open it in.

@wing328 should I submit a pull request with what I have now or should I wait until I have the unit testing done as well?

**Comment by wing328** [comment]
@Gronsak thanks for your effort. Please submit a PR so that we can review the enhancement.

**Comment by wing328** [comment]
#4955 has been merged into master. @johnamcruz @chitankensuru @who please pull the latest master to give it a try.

Thanks for the contribution by @Gronsak

**Comment by johnamcruz** [comment]
how do i use this version @wing328? what is the command to generate .NET standard c# SDK?

**Comment by wing328** [comment]
@johnamcruz would the following help?

https://github.com/swagger-api/swagger-codegen/blob/master/bin/csharp-petstore-v5.sh#L29

The config file: https://github.com/swagger-api/swagger-codegen/blob/master/bin/csharp-petstore-v5.json

**Comment by HappyTreesDev** [comment]
With the .NET standard format, I was able to include a compiled dll, but there were issues when attempting to include the project. After converting the project to a pcl and setting the pcl to support xamarin stuff, I found that there are Path and File usages that do not work. It would be nice to switch to PCL instead of .NET Standard and also use PCLStorage for paths so that we can target xamarin

**Comment by wing328** [comment]
@HappyTreesDev please open a new issue with more details (e.g. error message, etc) for tracking.

**Comment by Gronsak** [comment]
@HappyTreesDev ping me when you've opened a new issue about your problem, I have some questions

**Comment by HappyTreesDev** [comment]
I have opened a new issue at [#5889](https://github.com/swagger-api/swagger-codegen/issues/5889)
