### ISSUE TITLE
Objective-C client operations fail with missing Content-Type header when input is a JSON string (as opposed to an object)

### ISSUE THREAD

**Issue by rbhunt** [swagger-api/swagger-codegen#1612]
We're implementing a RESTful API that consumes and produces JSON.  We've discovered that swagger-generated Objective-C clients are not working correctly when the input to an operation is defined as a string rather than an object reference.

The issue in this scenario seems to be that no "Content-Type: application/json" header is present in the request, causing the server to reject the request.  It's worth noting that the server code is generated correctly and that requests from Postman, the Swagger Editor and swagger-generated Android clients work correctly, it only seems to be Objective-C clients that experience this issue.

I've attached a sample YAML file that should reproduce the issue.

[sample-yaml.txt](https://github.com/swagger-api/swagger-codegen/files/43267/sample-yaml.txt)

**Comment by wing328** [comment]
You can use `consumes` to specify the content type in the request. Here is an example:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L30

Instead of passing JSON string as input, I would recommend using model/object reference, which is automatically serialized into JSON string.

**Comment by wing328** [comment]
Closing this as there's no update. Please reopen if you need help from us.
