### ISSUE TITLE
Static HTML generation turns snake case query parameters into CamelCase

### ISSUE THREAD

**Issue by pniederw** [swagger-api/swagger-codegen#1938]
JSON input:

```json
"parameters" : [ {
          "name" : "project_id"
```

HTML output:

```html
<div class="param">projectId (required)</div>
```

`swagger-codegen-cli:2.1.5`

**Comment by wing328** [comment]
@pniederw thanks for reporting the issue. I think that's because [StaticHtmlGenerator](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/StaticHtmlGenerator.java) is using `toParamName` in [DefaultCodegen.java](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L363)

You can fix the issue by overriding it to simply return `name` without doing anything.

May I know if you've cycle to contribute the fix?

**Comment by pniederw** [comment]
Sorry but I'm not able to make code contributions at this time; best I can do is to file accurate issues.

**Comment by fehguy** [comment]
I believe we can fix this in the template.  I'll do so.
