### ISSUE TITLE
Static HTML generation disregards basePath

### ISSUE THREAD

**Issue by pniederw** [swagger-api/swagger-codegen#1939]
When adding a `basePath` such as `/v1` in the JSON, this isn't reflected anywhere in the generated static HTML.

`swagger-codegen-cli:2.1.5`

**Comment by wing328** [comment]
That can be fixed with {{basePathWithoutHost}} mustache tag in the static HTML mustache template.

e..g
https://github.com/swagger-api/swagger-codegen/blob/9a54371ca9e0355dfebd7cdfe4c4632684791c5a/modules/swagger-codegen/src/main/resources/flaskConnexion/README.mustache#L25

Would you have cycle to file a PR for that?

**Comment by pniederw** [comment]
Sorry but I'm not able to make code contributions at this time; best I can do is to file accurate issues.

**Comment by wing328** [comment]
Closed via #2928

**Comment by wing328** [comment]
Thanks for the PR from @catinred2
