### ISSUE TITLE
Webpack fails with "the request of a dependency is an expression"

### ISSUE THREAD

**Issue by ktunkiewicz** [swagger-api/swagger-codegen#2279]
in file `swagger-codegen/modules/swagger-codegen/src/main/resources/Javascript/model.mustache`
lines 4 and 7:
```javascript
define([undefined, '../ApiClient'{{#imports}}, './{{import}}'{{/imports}}], factory);
```
```javascript
module.exports = factory(undefined, require('../ApiClient'){{#imports}}, require('./{{import}}'){{/imports}});
```

The `undefined` in the parameters list causes webpack to fail with error "the request of a dependency is an expression". Everything seems to work fine if these `undefined`s are removed. Is there any particular reason why these are there or could they just be removed?

**Comment by xhh** [comment]
@ktunkiewicz the first argument for the `factory` function is for the usage in browser (without common.js + browerify/webpack or amd.js) which is the module name set into `window` (`root`), [see here for an example](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/src/model/Tag.js#L75).
It does not work the same way with [API files](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/javascript/src/api/PetApi.js#L13) because the model's name could not be accessed within the context of that line in model template.

With that said, I've found a way to add the model name to that context by referring to how it is done for API files. So I'll fix this issue soon.

**Comment by xhh** [comment]
Submitted PR #2323 for a fix. Please try in that branch and see if it works. cc @ktunkiewicz

**Comment by wing328** [comment]
@ktunkiewicz PR merged into master so please pull the latest.
