### ISSUE TITLE
Using Response header in subsequent Requests

### ISSUE THREAD

**Issue by egimaben** [swagger-api/swagger-codegen#2358]
In my manually built Java SDK for a REST service, I have this scenario when a User logs in.

1. I hit the login API

2. Receive response from server, pick out sessionID from response headers.

3. From this point hence forth, every request sends this sessionID in the request header. 

How can I make the generated client code replicate this?

**Comment by ePaul** [comment]
Things like HTTP sessions are not RESTful (because you should have a stateless server).

Of course you can specify the header parameter and response headers in your REST specification, but you then still have to manually pass them from one to the other. I would think that any automatic passing by generated code is out-of-scope of this project.

(Though I'm not having any decision power here.)

**Comment by fehguy** [comment]
Yes, what @ePaul said is correct about state being out of scope for this project.  That's your job to manage, and the generated client should make it easy to call the service and pass your state along with it.

**Comment by egimaben** [comment]
@ePaul and @fehguy , thanks for adding more light to this. Seems like I was asking too much of swagger-codegen. I will instead focus on doing this manually now.
