### ISSUE TITLE
C#: Use fully qualified names for model objects

### ISSUE THREAD

**Issue by jforsell** [swagger-api/swagger-codegen#2589]
Had an offline convo with @wing328 about this - in the generated Java code Api classes use fully qualified type names, but not in C#. I'm generating code for an API that I don't have control over, and it defines a "Stream" model which causes an ambiguous reference to System.IO.Stream and causes the code to not compile.

I can fix it by commenting out "using System.IO" which is an unused import in the Api class, but would probably be more robust to use the fully qualified type names.

**Comment by wing328** [comment]
@guohuang has filed #2594 to use fully qualified names in C# API client.

**Comment by jimschubert** [comment]
/cc @wing328

@jforsell verified in #2594 that this works for `System.IO.Stream`. Would this issue now be more appropriate to allow for the generation of fully qualified names for all models, not just Stream?

**Comment by wing328** [comment]
@jimschubert yes, looking at the bigger picture, we should consider using fully qualified names for all models.

We began with Task (System.Threading.Tasks.Task) a year ago and then Stream (System.IO.Stream) and it's just a matter of time we hit another one.

I'll create a separate task to track it.

**Comment by wing328** [comment]
Also @jforsell confirmed earlier (via email) that the fix works for him.

**Comment by wing328** [comment]
Sorry one more note. Based on my understanding, using fully-qualified name is not against the C# best practices or coding style guide.

Please correct me if I'm wrong.

**Comment by jimschubert** [comment]
@wing328. Fully qualified names don't break guidelines. Usually they're
used for short examples and not used when a parent namespace is already
imported.  I don't see it as an issue since the IDE and tools now allow you
to clean up the source code quickly. It *could* break builds with strict
static code analysis, but there's no real way to solve for all possible use
cases here.

On Sun, Apr 17, 2016 at 10:37 AM, wing328 <notifications@github.com> wrote:

> Sorry one more note. Based on my understanding, using fully-qualified name
> is not against the C# best practices or coding style guide.
>
> Please correct me if I'm wrong.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-codegen/issues/2589#issuecomment-211031339>
>



-- 

________________________
james.schubert@gmail.com
H (804) 571-1924
C (804) 921-7331
