### ISSUE TITLE
Generated Java Client relies on java.util.Objects (since 1.7), pom.xml specifies Java 1.6

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#2607]
_From @devinjones on April 14, 2016 20:58_

I generated a Java client for a swagger file and imported it as an existing maven project in eclipse.
There were compilation errors related to the `equals()` and `hashCode()` methods, caused by class not found: java.util.Objects

_Copied from original issue: swagger-api/swagger-editor#869_

**Comment by wing328** [comment]
@devinjones can you please provide the swagger spec for us to reproduce the issue?

**Comment by sbelan** [comment]
@wing328 ... I faced similar issue couple of days back when I changed target source compilation level to 1.6 in pom file. This is because java.util.Objects has different implementation for equals() and hashcode(). So all generated models gives the error mentioned by @webron. I modified logic of equals() and hashcode() compatible to 1.7. But as I have using retrofit and OKhttp, Okhttp not compatible to 1.6 so I rolled back changes.

**Comment by skirkpatrick** [comment]
@wing328 The `default.yaml` example spec available in the swagger editor is sufficient for reproducing this.

A minimalist spec would be any spec that has a `definitions` section:
```
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description: OK
definitions:
  Example:
    type: object
    properties:
      uuid:
        type: string
```

Every generated class under `io.swagger.client.model` has a reference to `java.util.Objects`, which was only added in JDK 1.7. The generated `build.gradle` specifies 1.7 as the target/source version, but the `pom.xml` specifies 1.6.
