### ISSUE TITLE
Generated Api Endpoint classes should implement common base interface

### ISSUE THREAD

**Issue by bluemmc** [swagger-api/swagger-codegen#2723]
I am using generated c# api classes by swagger-codegen to access an api with a large number of endpoints (i.e. many generated c# xxxApi classes). My use case is generated c# code but I assume the problem applies to other languages as well.

Swagger-codegen works fine when writing specific code against specific endpoints, but there are problems if I try to add general code that work against general aspects of the multiple endpoints / xxxApi classes. All generated xxxApi classes have common methods  GetBasePath() and Configuration() but they share no common interface declaring these methods, so I can't easily create a method that extracts configuration or base path from ANY xxxApi class generated by swagger-codegen. For instance, I need generalized access to the configuration to support adding e-tag headers used by caching. Currently, I can do this only by adding specific code for each generated xxxApi class or by using reflection (not nice).

This could be solved by having the generated classes implement both the endpoint specific interface AND a common interface containing GetBasePath and Configuration methods. Alternatively, the specific interface that is generated could extend a common interface.

**Comment by wing328** [comment]
@bluemmc I think that's a very good suggestion.

If anyone from the community wants to work on this, please reply to let us know.

**Comment by jimschubert** [comment]
Should this be done only for C#, or other languages as well?

**Comment by wing328** [comment]
@jimschubert when you've time, please add "partial" to C# API endpoint classes to begin with. I think we'd a similar discussion before and this should be the right time to do it.

(understood that adding partial is not the same as implementing a common interface but adding partial should provide the flexibility to allow developers to further customize it so as to address some of the pain points mentioned above)

**Comment by jimschubert** [comment]
@wing328 I reread the question to see if a partial class would resolve the issue, and it looks more like the question is how to use the ApiClient.Configuration singleton. I can add the partial keyword, too, but I think the fix here is to update documentation with how to modify the client configuration.

**Comment by wing328** [comment]
@jimschubert based on the following:
> Currently, I can do this only by adding specific code for each generated xxxApi class or by using reflection (not nice).

I think partial class would help (not a perfect solution).

Also agree on improving the documentation on show advanced usage of the C# SDK (e.g. how to use configuration, how to debug, etc)

**Comment by jimschubert** [comment]
@wing328 I agree the partial class could help some users, but I don't think it fully addresses this issue. I'll try to clarify and maybe @bluemmc can set me straight. ;)

I've always thought the `ApiClient` would be a little wonky for a lot of devs to follow.

Here's some relevant code to my comments below, with inline NOTES related to my comments:
```
    // from the constructors of *Api
    if (Configuration.ApiClient.Configuration == null)
    {
        // NOTE: because of the null check, this.configuration and this.Configuration.ApiClient.Configuration
        //       can refer to different instances.
        this.Configuration.ApiClient.Configuration = this.Configuration;
    }

   public String GetBasePath()
   {
       // NOTE: Api classes constructed with the basePath constructor will have unexpected behavior
       //       if user sets api.Configuration equal to some ApiClient with a different BaseUrl.
       return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
   }
```

Meanwhile, this is one of the constructors for ApiClient:

```
    public ApiClient(Configuration config = null)
    {
        // NOTE: Configuration.Default is not thread-safe, and results in 
        //       possibly unexpected Global configuration for individual requests.
        if (config == null)
            Configuration = Configuration.Default;
        else
            Configuration = config;

        RestClient = new RestClient("http://petstore.swagger.io/v2");
    }
```

The other two constructors are a parameterless constructor and a string-defaulted (`basePath`) constructor.

I think the issue, and @bluemmc may be able to verify this, is that an `ApiClient` instance constructed as `new ApiClient()` uses `Configuration.Default` which will have global level headers instead of instance level headers (I'm not sure many developers know which of the three constructors is actually invoked by `new ApiClient()`!). If a developer needs to deliver e-tag headers specific to a single endpoint in a multithreaded application, `Configuration.Default` isn't exactly thread-safe and you may end up setting e-tag headers from one thread which are inadvertently sent or modified on one or more other threads. This wouldn't be an issue specific to e-tags.

It sounds to me like the solution would require one or more of the following:

1. Make the *Api types partials, if for no other reason than consistency with model classes.
2. Differentiate between "global configuration" and "instance/per-request configuration". 
3. Better documentation related to constructing the *Api classes
4. Clean up the constructors for `ApiClient` to call through to the other constructors.
5. Maybe deprecate `Configuration.Default`?
6. Maybe remove the circular reference between Configuration and ApiClient?

I believe the second item above would resolve this issue. I think 4 and 5 above are indirectly adding confusion to the usage caused by the lack of global vs request configuration.

I don't think any of my comments above about multithreading are issues, unless Api instances are constructed with the `basePath`-argument constructor. It's likely that most code is constructing the ApiClient and Configuration on-demand for each call to an api/endpoint anyway. As long as ApiClient is constructed in a way so as to avoid hitting `Configuration.Default`, this would work perfectly well in a multithreaded scenario.

Also, I agree with @bluemmc's recommendation for common interfaces. @bluemmc can you provide an example of the type structure you'd like to see? With `partial` types, we'd want to avoid concrete base types because if I recall a user wouldn't be able to define a partial with a base implementation if the generated code also does this. If nothing else, I think the common things `GetBasePath` and `Configuration {get;set;}` should be defined in something like `IApiAccessor`.

**Comment by bluemmc** [comment]
@jimschubert Many thanks for the details. I was not aware of the dangerous Configuration.Default.

And a more general thanks to you both for this discussion. It is a great pleasure to be a small part of the consistently responsive and helpful open source community that swagger-codegen has ! 

I agree with your IApiAccessor proposal, I agree with the idea of making the generated clients partial and I agree with the need for additional documentation. I think that changes should be made to make it more difficult to use Configuration.Default so it is not used by accident.

I appears that there are many hidden gems and dangers, some in ApiClient and some in RestClient. For example, I have yet to find out if I can use the underlaying RestClient's CachePolicy to support automatic caching by etags or if I need to program something specific.Hope to have time to experiment soon.

**Comment by jimschubert** [comment]
@bluemmc I've submitted pull request #2857. Please let me know if this meets your needs.

**Comment by bluemmc** [comment]
The pull request looks great!

**Comment by bluemmc** [comment]
I will close this as it is fixed by #2858

**Comment by bluemmc** [comment]
@jimschubert 
Ups. A kind of regression. See #3106

**Comment by jimschubert** [comment]
Opened PR #3110 to add the ExceptionFactory property definition to the interface.
