### ISSUE TITLE
[Typescript] Add .gitignore to Typescript SDK

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#2767]
.gitignore to be added/auto-generated: https://github.com/Microsoft/TypeScript/blob/master/.gitignore

**Comment by jimschubert** [comment]
That ignore file is really specific to the Typescript compiler/project itself.

Maybe we could generate from https://www.gitignore.io (VS Code, node, Visual Studio I think would suffice) or pull from github's repo of ignore files https://github.com/github/gitignore/?

**Comment by wing328** [comment]
@jimschubert  I couldn't fine one from https://github.com/github/gitignore/ for TS. That's why I suggested the one above.

I'll take a look at https://www.gitignore.io

**Comment by jimschubert** [comment]
@wing328 There's nothing that's Typescript specific, because it's not a framework. We could pick some things out of Microsoft's file, but things in that file like `*.config` won't make sense for many users.

For example, compare to Angular 2's gitingore, which only has 5 or so repository specific excludes: https://github.com/angular/angular/blob/master/.gitignore

**Comment by wing328** [comment]
Added via https://github.com/swagger-api/swagger-codegen/pull/3172
