### ISSUE TITLE
Generating Client Libraries for Multiple Environments

### ISSUE THREAD

**Issue by tjboudreaux** [swagger-api/swagger-codegen#2769]
This seems like it would be a common use case but I am having trouble finding any reference to it in the docs or an example of it in any of the samples.  

We have development and production environments for our API's, which is a common scenario.

I am looking for a way to configure the base path based on environment.  I've checked the docs, wiki, and looked through some of the generated samples, but every sample I find has the base path hardcoded into the generated library. 

Should I generate a client library for each environment, or is there some way to specify in the generation process that the base path should be configurable?

**Comment by wing328** [comment]
@tjboudreaux the basePath can usually be set when constructing the Api class or ApiClient object. Which language are you referring to in particular?

**Comment by tjboudreaux** [comment]
@wing328 after filing this and generating a couple more CALs I noticed the objective-c library supported initializing the client with the base path.

The first client library I generated though, which was a java retrofit library doesn't seem to support it.  

Here's the APIClient template that generated the code I was referring to.

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/ApiClient.mustache

**Comment by wing328** [comment]
@tjboudreaux sorry that we missed the feature in Retrofit. We'll add it to Retrofit 1.x and 2.x.

**Comment by wing328** [comment]
@cbornet can please take a look when you've time?

**Comment by cbornet** [comment]
@tjboudreaux you can do ```apiclient.getAdapterBuilder().setEndpoint(newBasePath)```. It must be done before creating the service classes.
@wing328 I can PR the helper method if you think it's useful.

**Comment by wing328** [comment]
@cbornet one way is to generate the helper method. Another way is to generate documentation (md) showing how to set the base path with code sample (ref: https://github.com/swagger-api/swagger-codegen/issues/2359).

I would prefer the latter as a starting point if you've cycle to work on the auto-generated doc (currently auto-generated doc does not show advanced usage such as setting the base path. I plan to add it this coming week for Ruby)

**Comment by wing328** [comment]
@tjboudreaux since there's no update from you, I assume you've found a way to customize the base path. Please let ue know if that's not the case.

**Comment by wshreek** [comment]
Hi!
I am trying to use typescript client, and soon we will also be using a C# client. We definitely need configurable basepaths. 
Basically, as it seems the client gets the basepath from the swagger spec file. How can I have it configurable, so that we can have one endpoint for development environment and one for production. It would be best if it is configurable so that the consumer of the client can set it himself. The use case is, when the developers on the team are developing, they would like the client to point to their local desktop. And we also have alpha, beta, gamma, prod environments. 

Please let me know, if this can already be done.

Thank you very much for your help!
