### ISSUE TITLE
C# generated code should use ASP.NET core project structure

### ISSUE THREAD

**Issue by kbrooks** [swagger-api/swagger-codegen#2886]
We should add an option to the csharp generator to use the new ASP.NET core project structure.

@wing328

**Comment by wing328** [comment]
@kbrooks thanks for the suggestion. Is there any official guide from MS on the ASP.NET core project structure?

I did a search and found this: http://zablo.net/blog/post/modular-asp-net-core-project-structure (which is not official)

Also to be clear, you're referring to C# API client but not ASP.NET5 server stub, right?

Recently, there's a change to the folder structure via https://github.com/swagger-api/swagger-codegen/pull/2752 so please pull the latest master and give it a try if you've not done so.

**Comment by kbrooks** [comment]
The official docs appear to be down right now, but in case they come back up: https://docs.asp.net/en/latest/conceptual-overview/understanding-aspnet5-apps.html.

The main difference is the use of project.json files instead of the old xml configuration files.
The new project structure will be useful to anyone developing on mono or .NET core.

The ASP.NET5 server stub actually already uses the ASP.NET core project structure, so we could use that as a guide.

**Comment by wing328** [comment]
Yup, I got a 404. Will check it out later.

**Comment by jimschubert** [comment]
@kbrooks @wing328  I'd put this on the back burner for now. There's talk of dropping the `project.json` and moving back to MSBuild based .csproj after RC2.

See: https://twitter.com/davidfowl/status/730219570783363073 and https://youtu.be/P9HqMZviaMg?t=1712. There was also a pretty [lengthy discussion on Reddit](https://www.reddit.com/r/programming/comments/4iveez/projectjson_is_dead_aspnet_core_goes_back_to/) about a week ago.

Since Xamarin Studio is free to use on OS X and Linux and Visual Studio Community Edition is also free to use, there's nothing blocking anyone from developing on mono on any OS. Both of these support targeting current .NET 4.6.1.

The only thing this blocks is from consuming .NET Core assemblies, which I think would be fairly minor to incorporate after all the csproj stuff dies down.

**Comment by kdc415** [comment]
Looks like MS says they're going back to MSBuild

[https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/](url)

I've just downloaded my first swagger generated api server stub. I downloaded core RC1 to try to run it and it hosed my VS 2015 installation. 

Then I found this article, so I decided to make a new MVC5 project and incorporate the models/controllers and I'm having some trouble. Is there an example/tutorial out there somewhere? I've looked to no avail.

Thx - Ken

**Comment by jimschubert** [comment]
@kdc415 You should be able to run .NET Core RC1 and RC2/RTM side by side. I'm not sure why it would hose your environment.

When I created the aspnet5 server generator, I created two examples here https://github.com/jimschubert/webapi-swagger-samples. The `netstandard-1.4` directory is what became the generator while the `net45/src` stuff is Web API 5.2.3 code. I didn't create a generator for the older MVC code because it would quickly become outdated.

You should be able to develop against the generated code, and run in [Docker](https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/aspnet5/src/IO.Swagger/Dockerfile) if your local RC1 install is messed up.

```
docker build --name myapp .
docker run -v .:/app/proj -w /app/proj myapp
```

The app should be available now on port 5000. To get the ip address of the `myapp` container, run:
```
docker inspect --format '{{ .NetworkSettings.IPAddress }}' myapp
```

**Comment by kdc415** [comment]
Thanks for the response and the advice - I'll give it a shot. This is a new project and I suppose I may as well bite the bullet and use the latest. I expect we'll see final release very soon.

**Comment by stunney** [comment]
I know a lot of you are talking about this work being put on hold.  For those that care I'm currently doing some work on this in stunney/swagger-codegen.  I'll be making a PR soon :)

**Comment by stunney** [comment]
I can honcho that effort for sure :)
I've created a new "language" for this effort so that folks that still *need* RC1 for existing projects can still get at it without me interfering with them.  Some backwards compatibility is always a good thing.  Also, aspnet5 won't be a valid name anymore as they are calling it aspnet core 1.0, correct?  I was going to call it aspnetcore1.

I haven't checked it in yet, but I'm working on an msbuild moustache as well as the project.json file.  Maybe I don't need both as per the discussions above.  I can nix the json file :)

**Comment by jimschubert** [comment]
@stunney You bring up good points ;)

I've already accounted for the name change in #3085. My suggestion for the name change was to have a top level generator called `aspnet` and have library options like `core-1.0rc1`, `core-1.0rc2`, etc. This way we could also have MVC 4/5 templates and it wouldn't be confusing about how to find the generators and it wouldn't clutter the list of available server generators.

However, I don't think it would be beneficial from an open source community perspective to continue maintaining many separate `1.0x` generators. If anyone needs 1.0rc1, it's available in version 2.1.6 of the generator. 1.0rc2 is honestly not that much different from rc1.

Also, I have a few cleanup/include tasks in #2914 for the existing generator. If you're modeling your update after the current code, those are a few things that are missing.

**Comment by stunney** [comment]
Looking to moustache-ize the .xproj file
Does anyone know how to generate a new UUID from moustache?  My googling has come up blank.  Would I have to write a custom javascript block at the top of this moustache file?  I can't be the first person to hit this :(

**Comment by jimschubert** [comment]
There's already support for project guid on the csharp generator.

**Comment by stunney** [comment]
Blarg @jimschubert 
I feel silly.  Thanks for that smack, I deserve it.

**Comment by stunney** [comment]
{{packageGuid}}

Its so simple :)

**Comment by ogreenz** [comment]
I don't know if I should reply here / start an issue. So basically `project.json` is a dead horse and in VS 2017 RC ASP.NET Core projects are created with a `.csproj` any chance there will be porting for that convention?

**Comment by wing328** [comment]
@ogreenz I would suggest you to open a new issue for tracking and link to this one.

**Comment by jimschubert** [comment]
We'll want this behind a flag (even if it's the new default behavior), because not all devs track on the latest Visual Studio. I was waiting until general availability before doing an update, because the .NET Core stuff is known to change on a dime.

**Comment by ogreenz** [comment]
@jimschubert Well to be honest swagger kind of "forced" me to used the latest .NET Core stuff when it deprecated the `.csproj` in favor of the `project.json`. And because I have in my solution "old" `.csproj` projects, they don't like to play together and make my life harder. So now I'm transitioning into the "new" `.csproj` in the hopes that it will resolve my issues. But I completely understand and agree with you on the .NET Core stuff changing on a dime, believe me I'm no happy user when standards keep on changing every few months.
@wing328 will do, even if you don't get to it right away I think it would be inevitable in the future anyway.

**Comment by knom** [comment]
Are you planning to change to .NET Core 2.0 in the next version?
Happy to help!

**Comment by jimschubert** [comment]
I personally would like to move to .net core 2 for Swagger Codegen 2.3.

The issue with making the change before 2.3 is that it would be confusing if you've customized templates to have different (or missing) templates and configurations.

**Comment by wing328** [comment]
#7114 BY @knom has been merged into master. 

For those who need .NET core 2.0 support, please pull the latest master to give it a try.

**Comment by knom** [comment]
@wing328 Should this be closed?

**Comment by mdmota** [comment]
any prediction to launch client for asp.net core with dependency injection?
the constructor api is giving new in restsharp.
I tested with CsharpDotnett2
