### ISSUE TITLE
[Tizen] Updating the Tizen Client Generation Code

### ISSUE THREAD

**Issue by akhilkedia94** [swagger-api/swagger-codegen#3076]
Note - Please consider the following communication unofficial until I get the requisite approvals.

##### Updating the Tizen Client Generation Code

Hello,

I am an employee working in Tizen Platform Lab., Samsung R&D Centre, Samsung Electronics.

The current client template files for Tizen are extremely outdated and depend on deprecated system APIs, so much so that I could not even find the binaries for several of the imports (such as Tizen::Base::).

We have internally developed an updated version, and are currently testing it (The tests are also almost done). Once the required approvals are through (before the end of the month by my estimates), we will push it to Github.

Since the old mustaches are outdated, can you tell me exactly how you would require us to give the update?

Perhaps I fork a branch, update the required /modules/swagger-codegen/src/main/resources/tizen/*.mustache files and /modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TizenClientCodegen.java file and send a pull request?

Or perhaps for backwards compatibility you would still like to keep the old Tizen templates as well, so that I instead add another language, say Tizen2?

Also, will you require test cases for the PetStore sample?

Thanks and Regards,
Akhil Kedia

**Comment by wing328** [comment]
@akhilkedia94 Glad to hear that you've a better version for Tizen.

Given that the existing Tizen template is referencing/using depreciated system APIs. I suggest we simply sunset it. If developers need to use the deprecated system APIs, they can always use the Swagger Codegen v2.1.6 (latest stable version released about 2 months ago).

My take is to update the Tizen generator/template directly with PRs and avoid creating another generator "Tizen2"

For test cases with Petstore, we strongly recommend adding those so that we can include in our Travis CI to run the tests. As a reference, here are some tests for Petstore Qt5 C++ API client: 

https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/qt5cpp/PetStore

**Comment by fehguy** [comment]
@wing328 agreed.  CC @maneeshsahu

**Comment by wing328** [comment]
@akhilkedia94 may I know if you need any assistance filing a PR (pull request)?

**Comment by akhilkedia94** [comment]
@wing328 Hi!
I'm still waiting for the requisite approvals to release the code as open-source. 
By my estimates it should take a couple of more weeks unfortunately.

**Comment by wing328** [comment]
@akhilkedia94 please take your time. I was wondering if you need help on the PR. Looking forward to your PR.

Btw, we just added another C++ generator to the master, which generates C++ API client with [C++ REST SDK](https://github.com/Microsoft/cpprestsdk)

**Comment by maneeshsahu** [comment]
The old Tizen Codegen was written by @fehguy for @artikcloud, and it is not being used because of the Tizen platform upgrades. I recommend replacing it with the new codegen that @akhilkedia94 created, so there is no confusion.
