### ISSUE TITLE
C#: New property ExceptionFactory should be declared in interface IApiAccessor

### ISSUE THREAD

**Issue by bluemmc** [swagger-api/swagger-codegen#3106]
##### Description

I just tried the newest version from main branch (date 10-06-2016) and the new property ExceptionFactory on generated Api classes is missing from the new IApiAccessor interface. The absence makes it difficult to configure different Api classes using a common method. 

##### Swagger-codegen version

Newest unreleased version as of date 10-06-2016.

##### Steps to reproduce

Generate csharp Api for any json

##### Related issues

#2724 and #2723

##### Suggest a Fix

Add the following line to generated IApiAccessor.cs:

ExceptionFactory ExceptionFactory {get; set;}

**Comment by wing328** [comment]
@bluemmc can you help file a PR with the suggested fix?

**Comment by bluemmc** [comment]
@jimschubert The nice IApiAccessor interface you added should contain all such methods.

**Comment by bluemmc** [comment]
@wing328 I can tell you exactly where to add the line "ExceptionFactory ExceptionFactory {get; set;}" to the interface but bureaucracy here at work currently hinders me doing it myself. Sorry.

**Comment by jimschubert** [comment]
@bluemmc Sorry about the politics. I know that can be frustrating.

The fix was simple, so I've done it before going to work. I was playing around with the ExceptionFactory implementation a few different ways, and I think I only added it to the interface on the first attempt. Sorry about that.

On a side note, thanks @bluemmc for being so thorough with the description and linking of related issues.

**Comment by wing328** [comment]
PR merged. Thank you both!

**Comment by bluemmc** [comment]
Great. Just tested the newest version and now I see the property on the interface. Thanks for the impressive quick fix.
