### ISSUE TITLE
Model with name Map/List is ignored 

### ISSUE THREAD

**Issue by daisymoon** [swagger-api/swagger-codegen#3223]
##### Description

I have [this json](https://watson-api-explorer.mybluemix.net/listings/tradeoff-analytics-v1.json) that defines a model called "Map". 
I noticed that both in java and csharp this gets ignored when generating the code, I'm building a generator for a personalized language and it also gets ignored.
What I did was changing the name to "Mapa", and the problem is solved. 
But if I name it "List" I get the same problem, so it seems to be related to names that exist as types (like tony tam guessed [here](https://groups.google.com/forum/#!topic/swagger-swaggersocket/5DIXpnXhbW8))

##### Swagger declaration file content or url

    ```json
    "Map": {
      "description": "Typically, the map format would be consumed by Tradeoff Analytics JavaScript widget.",
      "required": [
        "anchors",
        "nodes"
      ],
      "properties": {
        "anchors": {
          "description": "A representation of the vertices for the objectives and their positions on the map visualization.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Anchor"
          }
        },
        "nodes": {
          "description": "A cell on the map visualization. Each cell in the array includes coordinates that describe the position on the map of the glyphs for one or more listed options, which are identified by their keys. The structure of an array element is `{\"coordinates\": {\"x\": 0, \"y\": 0}, \"solution_refs\": [\"key1\", \"key3\"]}`, where `coordinates` describe the position on the map visualization of options identified by the keys in `solution_refs`.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/MapNode"
          }
        }
      }
    },
    ```
##### Command line used for generation

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i https://watson-api-explorer.mybluemix.net/listings/tradeoff-analytics-v1.json -l csharp -o outputC

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i https://watson-api-explorer.mybluemix.net/listings/tradeoff-analytics-v1.json -l java -o outputJ

**Comment by wing328** [comment]
@daisymoon thanks for reporting the issue. I think it's due to the following:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractCSharpCodegen.java#L499

May I know if you've cycle to look into the issue and ideally submit a PR with the fix?

**Comment by daisymoon** [comment]
I decided to try all of the languages with [this yaml](https://s3.amazonaws.com/genexuss3test/issueSwagger.yaml) and got the following results:

- android
- aspnet5
- async-scala **//ok**
- csharp
- dart
- flash **//ok**
- python-flask **//no sure what it´s doing**
- go **//ok**
- groovy
- java
- jaxrs
- jaxrs-cxf
- jaxrs-resteasy
- inflector
- javascript **//ok**
- javascript-closure-angular **//ok**
- jmeter **//ok**
- nodejs-server **//ok**
- objc **//ok**
- perl
- php
- python
- qt5cpp **//ok**
- ruby
- scala **//ok**
- scalatra **//creates List but not Map**
- silex-PHP **//ok**
- sinatra **//ok, maybe?**
- rails5 **//ok**
- slim
- springboot
- spring-mvc
- dynamic-html
- html **//ok**
- swagger **//ok**
- swagger-yaml **//ok**
- swift **//ok**
- tizen **//ok**
- typescript-angular2
- typescript-angular
- typescript-node
- typescript-fetch 
- akka-scala **//ok**
- CsharpDotNet2
- clojure **//ok** 
- haskell  **//creates List but not map**
- lumen **//ok, maybe?**

Those where the results, the ones that don´t have a comment generated the model for ObjectForTest but not for List or Map.
[Here is the code that each one generated](Here is the code that each one generated)

@wing328 do you still think the problem might be related to AbstractCSharpCodegen?

**Comment by daisymoon** [comment]
I´ve been looking at the code and the problem seems to be [here](https://github.com/swagger-api/swagger-codegen/blob/89741c75f7ab289596b3d1d386946f0fbb45f859/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L273) 
Running the [yaml](https://s3.amazonaws.com/genexuss3test/issueSwagger.yaml) I added this lines to see if it was here where the models where getting lost:
```
if (config.importMapping().containsKey(name)) {
   LOGGER.warn(name);
   continue;
}
LOGGER.info(name);
```
And got this as a result:
```
[main] WARN io.swagger.codegen.DefaultGenerator - Map
[main] WARN io.swagger.codegen.DefaultGenerator - List
[main] INFO io.swagger.codegen.DefaultGenerator - ObjectForTest
```
So that´s where the problem seems to be.

The values for importMapping are stated [here](https://github.com/swagger-api/swagger-codegen/blob/9830e82add6f194226412d3de81acf711852185a/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L755) in DefaultCodegen.

And I checked why this isn´t a problem in some of the languages. They all seem to be either: removing List and Map from the typeMapping values, creating a new typeMapping object or clearing the typeMapping object.

I think there is more than one way in which this could be solved:
- [Here](https://github.com/swagger-api/swagger-codegen/blob/89741c75f7ab289596b3d1d386946f0fbb45f859/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L273) instead of ignoring it changing it´s name
- Not adding values to the importMapping object in [here](https://github.com/swagger-api/swagger-codegen/blob/9830e82add6f194226412d3de81acf711852185a/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L755) in DefaultCodegen.

Any of this options will have effects on how the code is generated that might not be what we you are looking for so i´m not sure which one would be the best fix.

**Comment by wing328** [comment]
@daisymoon thanks for the detailed findings. I do not have an answer on which one is the best way to fix the issue.

I'll take a  deeper look after the 2.2.0 stable release.

**Comment by jimschubert** [comment]
@wing328 @daisymoon I think we can re-initialize the `importMappings` hash for `AbstractCSharpCodegen`. Those java-y mappings aren't relevant for .NET types.

The `swagger-codegen-cli` module allows for an [import-mappings switch](https://github.com/swagger-api/swagger-codegen/blob/4d19da41dd8a3462f88c2be57174aace45101064/modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java#L90), which is [applied to the CodegenConfigurator instance](https://github.com/swagger-api/swagger-codegen/blob/4d19da41dd8a3462f88c2be57174aace45101064/modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfiguratorUtils.java#L33). The `CodedgenConfigurator` instantiates the relevant C# generator based on other parameters passed to the tool, and uses the `DefaultGenerator` type for generation of all generators (this is where the import mappings are consumed). We don't really do imports in the C# code [the way Java does](https://github.com/swagger-api/swagger-codegen/blob/4d19da41dd8a3462f88c2be57174aace45101064/modules/swagger-codegen/src/main/resources/Java/api.mustache#L10).

So, my proposal for this issue is to clear the `importMappings` for C# generators in `AbstractCSharpCodegen` then open another issue to add support for the `import-mappings` switch to C# generators (at least csharp, nancyfx, and aspnet5)

**Comment by wing328** [comment]
@jimschubert thanks for the suggestion.

@daisymoon I'll take a look tomorrow (Sunday) or Monday when I've time. Hopefully I'll have a PR to fix the issue.

**Comment by wing328** [comment]
@daisymoon I've filed #3454 to fix it using Jim's proposal.

For Java-related generators, we'll file another PR to address the issue later.
