### ISSUE TITLE
[RUBY] Petstore generated sample code is out of date

### ISSUE THREAD

**Issue by chadrosen** [swagger-api/swagger-codegen#3239]
I ran the sample code generator for ruby using bin/ruby-petstore.rb and realized that there were updates. I assume that there were changes either to the mustache or schema that just have not been updated in the sample code yet.

##### Description

It seems reasonable to keep the code up to date. I also want to submit patches to the mustache files and these differences will show up later.

##### Swagger-codegen version

This is happening on master

##### Swagger declaration file content or url

N/A

##### Command line used for generation

bin/ruby-petstore.sh

##### Steps to reproduce

1. Check out code
2. Run bin/ruby-petstore.sh
3. git diff master

##### Related issues

N/A

##### Suggest a Fix

https://github.com/swagger-api/swagger-codegen/pull/3238

**Comment by wing328** [comment]
@chadrosen there's a reason why the Petstore sample may be out of date. As the project matures, we add more and more test cases to the Petstore spec but we won't update Petstore sample for all languages. We (or the contributors) normally update the language that they're working on because not a single person can command all the languages or frameworks that we support.

I'll update https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md to include the above explanation.

**Comment by wing328** [comment]
UPDATE: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md has been updated with more info related to updating Petstore samples (and vendor extensions)

**Comment by chadrosen** [comment]
I threw the out my original PR and replaced it with this.

https://github.com/swagger-api/swagger-codegen/pull/3253

**Comment by wing328** [comment]
PR merged. Thanks for the contribution.
