### ISSUE TITLE
[csharp] add header problem due to static method for adding header

### ISSUE THREAD

**Issue by lunat** [swagger-api/swagger-codegen#3295]
##### Description

Adding an header value may cause a duplicate Header issue because the list is static.
Furthermore it could be useful adding a method that sets up the Api Key

##### Swagger-codegen version

2.2.0

##### Suggest a Fix

In file "Configuration.mustache"
change line 159

```
        public void AddDefaultHeader(string key, string value)
        {
            _defaultHeaderMap.Add(key, value);
        }
```

to

```
        public void AddDefaultHeader(string key, string value)
        {
            if (_defaultHeaderMap.ContainsKey(key))
                _defaultHeaderMap.Remove(key);
            _defaultHeaderMap.Add(key, value);
        }
```

And Add
```
        public void AddApiKey(string key, string value)
        {
            if (ApiKey.ContainsKey(key))
                ApiKey.Remove(key);
            ApiKey.Add(key, value);
        }

        public void AddApiKeyPrefix(string key, string value)
        {
            if (ApiKeyPrefix.ContainsKey(key))
                ApiKeyPrefix.Remove(key);
            ApiKeyPrefix.Add(key, value);
        }
```

**Comment by wing328** [comment]
@lunat thanks for the suggestion. Would you mind submitting a PR for your suggested change?

**Comment by lunat** [comment]
@wing328 sure I will do

**Comment by wing328** [comment]
@lunat thanks. Here is the contributing guideline: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by lunat** [comment]
@wing328 I have no permission submit a PR nor pushing any changing about this issue.
Am I missing something ?

**Comment by wing328** [comment]
@lunat you need to folk this git repo so that you will have permission to create a branch with the fix.

**Comment by jimschubert** [comment]
While related, I'm not sure how #3407 resolves any issues unless default construction of the static `Configuration` object  (e.g. `Configuration.Default`) is being heavily relied on. In which case, a consumer could just instantiate the configuration object and pass in the dictionaries (which is ideal because you can use `ReadOnlyDictionary` or `ConcurrentDictionary`). The addition of two instance level helper methods to interact with dictionaries that aren't owned by the instance just adds to the already confusing (imo) usage. 

The issue as presented mentions duplicate headers due to a static list. There are lists here, and no statics on the Configuration type, other than `Configuration.Default`, the exception factory, and a debug helper method. @lunat can you provide some clarification on how you're using Configuration and ApiClient to result in an issue? I assume by list you mean dictionary, and by static you mean the `Configuration.Default` instance?

I agree with the first suggestion of `_defaultHeaderMap.ContainsKey(key)`. I'm not saying the fix in the PR is wrong by any means. #2858 is open to get community feedback on refactoring the ApiClient and Configuration objects because they're not entirely thread-safe for the static `Default` instances, and I'd hate to see the interface with Configuration changed and coded against just to be completely changed again soon.

**Comment by jimschubert** [comment]
I've opened #3530 for refactoring the `ApiClient` and `Configuration` types to remove a lot of the possible usability issues. For example, from that PR:

```
var a = new ApiClient(); // obviously Configuration.Default
Configuration.Default.ApiClient; // obviously Configuration.Default
var a2 = new ApiClient(config); // obviously config instance
config.ApiClient; // obviously config instance
```

The configuration property from an api client instance (`apiClient.Configuration`) is exposed as an interface with getter-only properties. This somewhat limits where configuration can be changed. I say "somewhat" because one could still cast to `Configuration` and abuse this.

A key point in #3530 that addresses this issue is that Configuration instances no longer share dictionaries of settings-- other than `Configuration.Default`. Values are copied into the configuration instance on construction, so there's no oddities here. It's possible to create a configuration instance and manually construct multiple ApiClient instances using that same configuration, but this will be obvious when configuration values are changed. Also, the default container for headers, api keys, and api key prefixes is a `ConcurrentDictionary`. I left these as settable properties in case there are scenarios where a `ConcurrentDictionary` is suboptimal or where developers want a custom dictionary implementation.

@lunat would you mind reviewing my changes in that PR? It includes the changes from your merged PR associated with this issue, but I'd be interested in feedback related to the breaking changes and usability of these types.

**Comment by lunat** [comment]
For me it is ok.

I suggested two variations in documentation file. anyway I answered in issue #3530
