### ISSUE TITLE
Spring: make API interface default implementations configurable

### ISSUE THREAD

**Issue by ralfstuckert** [swagger-api/swagger-codegen#3408]
I'm using swagger code gen maven plugin 2.2.0 to create both a spring boot controller and a feign client (in two different projects). Since I'm using java 8 date time API, I'm setting the additional property dateLibrary=java8. This - implicitly - sets the java8 flag true (see io.swagger.codegen.languages.AbstractJavaCodegen.processOpts()). This leads the api.mustache to create default implementations for the interface methods. Here comes the catch: When there is a default implementation, the Spring Feign client always calls the default implementation instead of making a remote call :-/

Ok, you may argue that this is a problem in the spring feign implementation, but theses default implementations are quite disturbing. What's their sense anyway? I always prefer fail fast instead of any "silent-do-nothing" behaviour in case things are going wrong. So please make these default implemenations at least configurable... or remove them at all.

**Comment by ralfstuckert** [comment]
This seems to be a [Feign feature](https://github.com/OpenFeign/feign/blob/master/README.md#static-and-default-methods).

So these default implementations renders the interface useless for usage with feign, or am I missing a point here?

**Comment by cbornet** [comment]
@ralfstuckert Are you using Feign directly or through a spring-cloud FeignClient ? Are you generating the client with the spring-cloud generator ?

**Comment by ralfstuckert** [comment]
I'm using the spring-cloud generator:
```
@FeignClient(name = "test", url = "${test.url}")
public interface TestClient extends ApiApi {
}
```

**Comment by ralfstuckert** [comment]
But I guess the problem is independent of spring, it is feign itself that calls the default method, see `feign.DefaultMethodHandler`

**Comment by cbornet** [comment]
Indeed ! So ```default``` must not be used with Feign !
The api template is the common spring one but it is easy to create a dedicated one for spring-cloud.

From there, you have several possibilities :
* wait for a fix in the codegen (and a release ?)
* write your own template and use it with ```-t``` option
* use typeMappings + importMappings to map the date/dateTime types instead of using dateLibrary. That way you won't have the java8 flag set. The drawback is that the generated pom.xml will embed jackson-datatype-joda instead of jackson-datatype-jsr310

**Comment by ralfstuckert** [comment]
What would have to do to use my own template until it is fixed?

By the way: what are those default methods good for?!?

**Comment by cbornet** [comment]
You can [specify a template dir](https://github.com/swagger-api/swagger-codegen#modifying-the-client-library-format) with ```-t```.
In this dir provide a ```api.mustache```. An easy way to modify them would be to replace any mention of java8 by java8default. So java8default will be false even with dateLibrary=java8.

The interest of default methods is that server-side, you don't have to implement all methods in the controller. So you can generate the controller the first time, then modify the controller with your own code and prevent further generation for the controller (using swagger-ignore for instance). If you add new endpoints and regenerate, the code will still work because the controller has a default implementation.

**Comment by ralfstuckert** [comment]
Thanks for your support :-)

I guess it will take some time until a fix resp. the next release will be available? 
So I'm gonna try a modified template in the meantime.
