### ISSUE TITLE
[Go] [Bug] Client does not fully honor Configuration

### ISSUE THREAD

**Issue by neilotoole** [swagger-api/swagger-codegen#3464]
##### Description

The generated client does not honor all the settings in `Configuration`.  I haven't performed an exhaustive examination of the code, but I found these very quickly:
- `Configuration.UserAgent`: this is just ignored.
- `Configuration.Debug`: also ignored. See code example:
  
  ``` go
  //set debug flag
  configuration := NewConfiguration()
  resty.SetDebug(configuration.GetDebug())  // wut?!
  ```
##### Swagger-codegen version

`master`
##### Suggest a Fix

Fix the code to honor the variables.

**Comment by wing328** [comment]
@neilotoole thanks for the details.

@guohuang can you take a look please?

**Comment by guohuang** [comment]
@neilotoole thanks reporting the issue, regarding to `Configuration.UserAgent` if i understand correctly, there is no way to set it via the CLI, so, in order to set the value, you have to change the default value in configuration.go, if i remember correctly, we are not using `Configuration.UserAgent` anywhere in the project, is that what you mean "ignored"? where do you want to apply this variable?

Regarding to the `Configuration.Debug` @wing328 wants it to be locked, he doesn't want people to change the flag outside of `configuration.go`, that is why we created the `SetDebug` and `GetDebug` method, and made the debug variable private. In terms of functionality, the flag should be working as expected if you change the debug value in configuration.go

**Comment by neilotoole** [comment]
@guohuang I've fixed the issue wrt the `User-Agent` and other settings in the PR above. 

Regarding `Configuration.Debug`... I don't understand what is meant by "to be locked"? If there are getters and setters for the field, then it's effectively exported (public), and the Go idiom is to generally make fields exported rather than getter/setters. Believe me, it took me a while when moving from Java-land to grok the Go idioms (I'm over 6 months into this brave new world of Go!), but it all makes sense in the context of your Go program being statically linked... it's not like Java, where your application can load an arbitrary JAR at runtime, and that library could run amok; with Go, when you build your project, you have total and final control over the entire program code, therefore the need to "hide" fields (as in Java etc) is somewhat redundant.

**Comment by guohuang** [comment]
I agree with you, having the setter and getter does not fit the Go style, in fact, that is what i had before https://github.com/swagger-api/swagger-codegen/blob/70e42cb0db9021e81ffebba84e4fec1622f506b5/samples/client/petstore/go/go-petstore/configuration.go#L12

**Comment by neilotoole** [comment]
@guohuang Excellent, glad we're on the same page!

**Comment by wing328** [comment]
@guohuang @neilotoole I would suggest you open a ticket with your feedback regarding `SetDebug` in https://github.com/go-resty/resty
