### ISSUE TITLE
[javascript client] ability to access superagent request for custom request options

### ISSUE THREAD

**Issue by rgarcia** [swagger-api/swagger-codegen#3527]
##### Description

superagent (the http client used in the generated javascript client) is very extensible, but this extensibility is not accessible in the generated client code.

This makes it difficult for us to satisfy some of our requirements, e.g.
- request tracing (via [opentracing](https://github.com/opentracing/opentracing-javascript))
- richer retry logic (via [superagent-retry](https://github.com/segmentio/superagent-retry))
- custom logging (via [superagent-logger](https://github.com/yamadapc/superagent-logger))
##### Swagger-codegen version

2.2.0
##### Swagger declaration file content or url

N/A
##### Command line used for generation

N/A
##### Steps to reproduce

Generate a javascript client.
##### Related issues

Couldn't find any.
##### Suggest a Fix

One potential fix: add a `withRequestMiddleware` method to the `ApiClient` class that takes in a function that mutates the request, e.g.

``` javascript
const apiClient = new yourapi.ApiClient().withRequestMiddleware((request) => {
  // set up how you'd like to modify requests made by this client
  request.use(...);
});
```

Then `ApiClient`'s `callApi` method can call this function on all requests it makes.

**Comment by wing328** [comment]
@rgarcia I think basically you want to expose `request` so that developers can do whatever they want. The suggestion sounds good to me and we've already done something similar in other API clients (e.g. C#, Java, etc). For example, C# API client provides setter for RestClient (HTTP lib): https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger/Client/ApiClient.cs#L117 so that developers can change its setting to meet their requirement.

May I know if you've cycle to submit a PR for the enhancement so that we can review the change?

**Comment by rgarcia** [comment]
@wing328 it sounds like there are two possible approaches:

1) expose `request` via something like I describe
2) expose the http client itself (`superagent`) similar to how other clients expose the http client

`superagent`'s plugin design is oriented around the `request` object, so I lean towards approach (1). Approach (2) would require injecting your own, extended `superagent` object. There is a way to do this ([superagent-use](https://github.com/koenpunt/superagent-use)) but I fear that this is not a common approach.

I will try to make a PR demonstrating approach (1) today.

**Comment by rgarcia** [comment]
Submitted #3540
