### ISSUE TITLE
CLI: --config param not working?

### ISSUE THREAD

**Issue by PhilippSoehnlein** [swagger-api/swagger-codegen#3589]
##### Description

The docs say, that there's a `-c` or `--config` parameter. I tried, but no matter what, it looks like it doesn't work at all.

##### Swagger-codegen version

2.2.1

##### Command line used for generation

`swagger-codegen generate -c config.json`

config.json:
```json
{
    "input-spec": "https://someserver.tld/api/swagger.json",
    "output-dir": "src/app/shared/",
    "lang": "typescript-angular2"
}

```

Output: 
```
Exception in thread "main" io.airlift.airline.ParseOptionMissingException: Required option '-l' is missing
       	at io.airlift.airline.Cli.validate(Cli.java:157)
       	at io.airlift.airline.Cli.parse(Cli.java:116)
       	at io.airlift.airline.Cli.parse(Cli.java:97)
       	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
```

When I add `-l` paramter on the CLI the next error message is about the missing `-i`-parameter. When I provide this one, code gets generated, but the specified `output-dir` is also ignored.

##### Suggest a Fix

Not really a suggestion for a fix, but I think a documented example on how the config file should work (and to what path the paths in there are relative) would also be a good idea.

**Comment by wing328** [comment]
`-c` (or `--config`) is for language-specified options. Please refer to https://github.com/swagger-api/swagger-codegen#getting-started for more information. If you need further help, let me know.

**Comment by PhilippSoehnlein** [comment]
> -c (or --config) is for language-specified options
I see, misunderstanding from my site. Thanks for clarifying!

**Comment by ePaul** [comment]
Looking at the code, I think it should be easily possible to set everything (including the currently required parameters `--lang` and `--input-spec`) from the config file (`CodegenConfigurator.fromFile(configFile)` does just that).

The problem is just that the Cli validator (which throws this exception) wants those parameters as required (because we annotated them as such), and we don't have an easy way of saying "those parameters need to be either in the command line or in the config file".
We have this check also in CodegenConfigurator.toClientOptInput, but there we don't have the parameter names from the CLI anymore, so the error message would be a bit less specific.

By the way, I think we should catch this exception and print just the message, not the stack trace.
