### ISSUE TITLE
[ASPNET5] basePath not be used in the auto-generated code

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#3910]
##### Description

For `aspnet5`, there's no reference to v2 in the auto-generated Petstore sample at the moment:
```
$ grep -R v2 samples/server/petstore/aspnet5/*
$
```
which means `basePath` (e.g v2) in the spec is not being utilized.

##### Swagger-codegen version

Latest master

If anyone wants to work on this, please reply to let us know.

Ref: https://github.com/swagger-api/swagger-codegen/issues/3418

**Comment by jimschubert** [comment]
@wing328 I'll try to take a look at this today. If I don't open a PR by end of day, I won't have had the chance.

Sorry I didn't respond to the mention in the linked issue, I don't recall getting a notification for that.

**Comment by wing328** [comment]
@jimschubert that's ok bro. No one has reported similar issue so far.

**Comment by jimschubert** [comment]
@wing328 that was actually a pretty quick fix.

We've probably not had this reported before because I doubt most C# devs are doing spec-driven development from swagger definitions. Everyone I've ever met who uses C#/ASP.NET do code-first development and use generated Swagger definitions as post-facto developer documentation.  The definition is heavily dependent on how tools like Swashbuckle generate routes (which I seem to recall does not break out route versions from routes).

**Comment by wing328** [comment]
@jimschubert thanks for the quick fix. PR merged.
