### ISSUE TITLE
branch develop_2.0 is missing scala generator

### ISSUE THREAD

**Issue by alonsnir** [swagger-api/swagger-codegen#393]

**Comment by fehguy** [comment]
Please give that a shot.  I've added tests but not thoroughly tested it.

**Comment by alonsnir** [comment]
java -cp ./target/*:./target/lib/* com.wordnik.swagger.codegen.Codegen -i http://localhost:8080/api-docs -l scala -o samples/client/inventory/scala
gives me:
loading class scala
usage: Codegen
 -d,--debug-info           prints additional info for debugging
 -h,--help                 shows this message
 -i,--input-spec <arg>     location of the swagger spec, as URL or file
 -l,--lang <arg>           client language to generate.
                           Available languages include:
                           [android, java, jaxrs, nodejs, objc, scalatra,
                           dynamic-html, html, swagger, tizen, php]
 -o,--output <arg>         where to write the generated files
 -t,--template-dir <arg>   folder containing the template files

**Comment by alonsnir** [comment]
kindly ignore - user error

**Comment by alonsnir** [comment]
as for the tests, getting errors like following:
[ERROR] /home/user/swagger-codegen/samples/client/inventory/scala/src/main/java/io/swagger/client/api/CollectionApi.scala:54: error: identifier expected but ':' found.
[ERROR]   def create (: CollectionCreationRequest) : Option[Collection] = {
[ERROR]               ^
[ERROR] /home/user/swagger-codegen/samples/client/inventory/scala/src/main/java/io/swagger/client/api/CollectionApi.scala:160: error: ':' expected but '}' found.
[ERROR] }
[ERROR] ^

**Comment by alonsnir** [comment]
the error above is from the build of generated sources, so not related to test generation.
looks like the template you added requires some fix

**Comment by fehguy** [comment]
If you can post some or all of the spec that you're using to get that error, it should be a quick fix

**Comment by alonsnir** [comment]
@Api(value = "/collection", description = "CRU(D) and query operations on Data Collections.", position = 0)
class DataCollectionService(dataCollectionActor: ActorRef, datasetActor: ActorRef)(implicit executionContext: ExecutionContext, val bindingModule: BindingModule)
  extends Directives with DefaultJsonFormats with InventoryModelJsonFormat with Injectable with ConfigConversions {

  implicit val collectionErrorSelector : ErrorSelector[CollectionError] = (error: CollectionError) => error match {
    case InvalidCollectionInfo(msg) => BadRequest
    case InternalFailure(msg) => InternalServerError
  }

  implicit val timeout = injectOptionalProperty[Timeout]("service.timeout.default") getOrElse Timeout(2.seconds)


  val route =
    pathPrefix("collection") {
      pathEnd {
        queries ~
        create ~
        updateCollection
      } ~
      path( Segment ) { dataSetId: String =>
        getById(dataSetId)
        //deleteCollection(dataSetId)
      } ~
      path( Segment / "dataset" ) { collection_id: String =>
        getAllDatasetsOfCollection(collection_id)
      }
    }

  def queries =
    get {
      searchCollectionByLocation ~
      searchCollectionByName
    }


  @ApiOperation(value = "Create a new collection", nickname = "create", httpMethod = "POST", response = classOf[Collection])
  @ApiImplicitParams(Array(
    new ApiImplicitParam(name = "body", value = "The new collection to create", required = true, dataType = "org.fannan.bigdata.core.inventory.model.api.CollectionCreationRequest", paramType = "body")
  ))
  def create =
    post {
      handleWith {  ctc: CollectionCreationRequest =>
        val collection = Collection("", ctc.name, ctc.schemaId, ctc.location, ctc.metadata)
        (dataCollectionActor ? CreateDataCollection(collection)).mapTo[CollectionError \/ Collection]
      }
    }

  @ApiOperation(value = "Retrieve a collection using its ID", nickname = "getById", httpMethod = "GET", response = classOf[Collection])
  @ApiImplicitParams(Array(
    new ApiImplicitParam(name = "id", value = "ID of the collection to get", required = true, dataType = "String", paramType = "path")
  ))
  def getById(dataSetId: String) =
      get {
        query( GetDataCollection(dataSetId) )
      }
@ApiOperation(value = "Update a collection using its ID", nickname = "update", httpMethod = "POST", response = classOf[Collection])
  @ApiImplicitParams(Array(
    new ApiImplicitParam(name = "body", value = "The collection to update", required = true, dataType = "Collection", paramType = "body")
  ))
  def updateCollection =
    post {
      handleWith {  dataCollection: Collection =>
        (dataCollectionActor ? UpdateDataCollection(dataCollection)).mapTo[Collection]
      }
    }
............................
............................

**Comment by fehguy** [comment]
Can you post just the Json from /api-docs/collection?

**Comment by alonsnir** [comment]
{"apiVersion":"2.0","swaggerVersion":"1.2","apis":[{"path":"/collection","description":"CRU(D) and query operations on Data Collections."},{"path":"/etl","description":"Operations on Etl"},{"path":"/dataset","description":"CRU(D) and query operations on DataSets."},{"path":"/schema","description":"Simplified schema CRU(D) and query API"}],"info":{"title":"InventoryService API","description":"REST API for the Inventory Services.","termsOfServiceUrl":"","contact":"Tiago Palma (the Inventory Master)","license":"-","licenseUrl":""}}

**Comment by fehguy** [comment]
Hi, I've found two issues.

First, the `name` field for the input body on `"summary": "Create a new collection"` is empty.  Can you add one?  I've manually updated the json for testing.

Next, there are two models where you're passing `"$ref": "Map[string,string]"`, which is not valid swagger.  You have two options.

1) change it to `Object` in your `@ApiModelProperty` annotation and cast it to a map on the client
or
2) create a container object to hold a list of key, value objects.

Alternatively we can support a hack in swagger-codegen to transform these into valid swagger 2.0 maps, which look like this:

```json
"metadata": {
  "additionalProperties": {
    "type": "string"
 }
```

Since you are not the only one to do this, I don't mind the transformation of the map[string, string] into the proper syntax above.

**Comment by alonsnir** [comment]
Hey,
this is strange, Ron already has pointed out that there is a problem with missing name, so amended  as following:

 @ApiOperation(value = "Create a new collection", nickname = "create", httpMethod = "POST", response = classOf[Collection])
  @ApiImplicitParams(Array(
    new ApiImplicitParam(name = "body", value = "The new collection to create", required = true, dataType = "org.fannan.bigdata.core.inventory.model.api.CollectionCreationRequest", paramType = "body")
  ))
  def create =
    post {
      handleWith {  ctc: CollectionCreationRequest =>
        val collection = Collection("", ctc.name, ctc.schemaId, ctc.location, ctc.metadata)
        (dataCollectionActor ? CreateDataCollection(collection)).mapTo[CollectionError \/ Collection]
      }
    }

do you know what is wrong?

**Comment by fehguy** [comment]
I'm not sure why it would be disappearing.  I do think the codegen can replace missing `name` params with a default, or throw an error.  That I can help with.

How about the other question I had regarding the maps?

**Comment by alonsnir** [comment]
Regarding maps, i'm trying out the object casting to map approach.
Could you please drop a link to some sample of both approaches?
Thanks

**Comment by fehguy** [comment]
Well for maps, it's going to be grunt work--looking at the map[string,_] and creating a MapProperty.

I would approach it here:

https://github.com/swagger-api/swagger-parser

Since this project is what reads in the JSON and creates POJOs from it.  I suggest looking in the legacy-parser since you're looking at a 1.2 spec.  Specifically this class:

https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-legacy-spec-parser/src/main/java/io/swagger/parser/SwaggerLegacyConverter.java

You should be creating a MapProperty object when detecting the map ref.

**Comment by fehguy** [comment]
This has been added to develop_2.0

**Comment by alonsnir** [comment]
Just to update on how we have resolved it.
As suggested by @fehguy we have created a container object to hold map's key/values and then converting to/from map/list between server/client.
Thanks @fehguy !

**Comment by kenterxie** [comment]
@alonsnir would you mind sharing your code snippet of the server side for this container object to resolve the map[string, string] issue? I met the same issue in my project. In our project, we had built server side code first. Then from the generated JSON file I saw same as below. 

"$ref": "Map[string,string]"

Then when I tried to generate client side code using swagger-codegen, it simply translates it to Map[string, string] which cann't pass compiling. 

For example, in my server side I have below code:
        @JsonIgnore
	@JsonProperty(value = "attributes")
	@ApiModelProperty(value = "user attributes", required = false)
	Map<String, String> attributes = new HashMap<String, String>();

Then I got below JSON file:

"attributes":{"$ref":"Map[string,string]","description":"user attributes"},

Then in the generated java client side code I see below code. 

         private Map[string,string] attributes = null; <-----compiling error here

I'm wondering how I can modify my existing server side code so that I can get correct JSON file and then generated correct client side java code. You can also send your code snippet to kenter.xie@gmail.com if you don't want to paste it here. Thanks a lot in advance!

**Comment by fehguy** [comment]
@kenterxie the problem is, you are using 1.3.x but that version does not support maps.  You should consider updating to 1.5.x which has map support.

If you want to do map-like support, you'll have to create an object with something like "key" and "value" as properties, and put them in an array.

**Comment by kenterxie** [comment]
@fehguy So if I update to 1.5.x then I don't need to create an object with "key" and "value" properties and put them in an array, correct?
