### ISSUE TITLE
[Discussion] Migrate the project from Java to other programming language

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#3948]
As part of the OpenAPI/Swagger 2.0 release 2 years ago, the Swagger Codegen was migrated from Scala to Java. The goal was to make it easier for developers to contribute bug fixes and enhancements.

Given that OpenAPI 3.0 will be released soon, we want to ask the community to see if anyone has an opinion to migrate the project from Java to other programming langauges (other than Scala as it's unlikely we'll move back).

Please reply with your suggestion and most importantly the reason behind the switch (e.g. the advantages of using the programming language you proposed)

This is not to say Java is bad and we need to replace it. Personally I feel more comfortable with Java than Scala. We just want to take this opportunity (OpenAPI 3.0 release) to gather more feedback from the awesome community.

Ref: https://www.infoq.com/articles/open-api-initiative-update

**Comment by cbornet** [comment]
We depend on external libs such as swagger-core and swagger-parser. Does this mean that these would be recoded or is the choice limited to languages on the JVM ?
Java being the language known by most people, I don't think it would be wise to change. And we have a huge code base most of which will be reusable.
Maybe the libs we use could be done with fancy JVM languages such as Groovy or Kotlin since they have less contributors.

**Comment by wing328** [comment]
Very good question. The way I look at the current dependencies is that these are not a must when it comes to switching to another programming languages.

Let's say we switch from Java to Ruby instead. As the project matures, we might do the same thing by separating the logic in parsing the OpenAPI/Swagger spec into a standalone Ruby gem.

I agree leveraging the current dependencies (e.g. swagger-parser, swagger-core) may be a good idea but I don't want to put it as a hard requirement that we must keep these dependencies when migrating to another language.

**Comment by jimschubert** [comment]
I think a different way to phrase the question would be: what is gained (and lost) by moving to another language?

What's lost...?

I use Scala at work. The Scala 2.10/2.11 work in Swagger Core was very usable, while the Java implementation makes things a little more difficult (because types aren't immutable, not all types support method chaining, etc.). Staying in the JVM at least makes the code usable, even if the usability isn't ideal for a small set of people.

Like @cbornet suggests, I would avoid switching to a non-JVM language. If Swagger Codegen switched to Ruby, for example, I think it would have to be JRuby otherwise we'd have to rewrite Swagger Core/Parser in Ruby? Plus, we lose any tooling built around Swagger Core/Parser/Codegen both in the community and internal tools (such as those I'm currently working on at work) which required the JVM based implementation.

One major consideration against migrating from Java to some non-JVM language is that Java is still _the most popular_ language (see [IEEE Spectrum](http://spectrum.ieee.org/computing/software/the-2016-top-programming-languages), which agrees with many other polls).

Whats gained...?

I don't really have a good idea of what would be gained by a complete language rewrite? Maybe we could use some library in something like Ruby or Python which doesn't exist in Java? A new language may excite more community contribution from people familiar with another language, but would that also mean losing many current contributors who contribute because the project(s) are written in Java?

All that said, I would suggest looking at Kotlin as an alternative language. Some benefits:

* Kotlin is 100% compatible with Java
* IntelliJ can automatically convert Java -> Kotlin
* Java and Kotlin can co-exist in the same project
* We may be able to leverage Kotlin's DSL support for generating things like documentation

I'm using Kotlin in a personal project, and I'm enjoying it. The great thing is that it could be evaluated incrementally, rather than requiring a full rewrite.

I think there should also be a consideration of sticking with the current Java implementation, and evaluating whether there's any way to simplify the code structure to improve ease of contributions.

**Comment by dcbroad3** [comment]
Based on the discussion so far, it looks like you're pretty set on Java and I'm not sure I blame you, but since you're asking for feedback:
I'm personally working on mapping a Web API assembly through a swagger spec to typescript/angular2, and no one in our company uses Java. We're a Microsoft focused company and we primarily use C++/C#. I'm having to consider alternatives to swagger-codegen because I don't want anyone building our angular2 library from the swagger spec to have to install Java first. I'm also concerned that our clients, who I know are also Microsoft-focused and may not have Java installed, would also have to install Java and Maven to use this library, which seems to be the only large-scale library available for code generation. 
It doesn't sound like it's a possibility, but since you're asking, it would be better for our use case if this library was written in C#.

**Comment by jimschubert** [comment]
@dcbroad3 

You don't need Java installed to use swagger codegen. 

With Docker installed (which most devs have anyway), you can use my container: https://hub.docker.com/r/jimschubert/swagger-codegen-cli/

There's also a web service which you can deploy internally in commodity hardware (swagger-generator, which should run on as little as a Raspberry Pi). The generator is different from editor.swagger.io, and you can check it out here: https://generator.swagger.io

**Comment by cbornet** [comment]
You could also wrap the jar+JRE in an exe with [Launch4j](http://launch4j.sourceforge.net/) (which makes me think that we could distribute the cli releases as windows exe)

**Comment by cbornet** [comment]
And installing .NET or Mono is not better than Java :smile:

**Comment by dcbroad3** [comment]
I'm sure we'll find a way to get it to work, but just figured that since you're asking, I'd point out that it's a fair amount of extra work for us to use this project in Java. For me it's not a matter of whether .NET or Java is better, but a matter of consistency and convenience in our company since we don't use Java for anything, but we use .NET wherever possible.

**Comment by wing328** [comment]
@dcbroad3 do you know that this project also comes with a web service to generate code (API clients, server stubs, documentation) ??

editor.swagger.io sends HTTP requests to generator.swagger.io to generate code and generator.swagger.io is exactly powered by this project.

The easiest way is to run it via docker: https://hub.docker.com/r/swaggerapi/swagger-generator/

and here is how to generate code online: https://github.com/swagger-api/swagger-codegen#online-generators

Would this work better in your environment which does not use Java?

**Comment by fehguy** [comment]
My thoughts for switching languages are:

* Java is typesafe.  Codegen templates are not, and using a dynamic language could make things immensely easier.  For example, look at example objects.  They're almost impossible to support in the way users really want to.  `example: "{\"foo\":\"bar\"}"` is not very usable in templates.

Look at places in the code where we have to work around setting maps in maps, etc.  An untyped language would probably be a lot easier.

* The project _is_ expensive to run, meaning it requires a bunch of memory and several seconds to just load.  Javascript, for example would be at least 20x faster

* There may be better template frameworks in different languages

* If the project can be run in a browser, we may introduce the ability for some very cool tooling.

That said, there is a substantial investment from the community in the current codebase.  The swagger team will have a new set of POJOs to support the 3.0 spec, and I would also expect the parser to translate swagger 2.0 specs directly into 3.0 when it's fully baked.

**Comment by dcbroad3** [comment]
I ended up writing a ~1000 line C# app that generates exactly what we want.

**Comment by ePaul** [comment]
@fehguy:

> My thoughts for switching languages are:
> 
> * Java is typesafe. Codegen templates are not, and using a dynamic
>    language could make things immensely easier. For example, look at
>    example objects. They're almost impossible to support in the way users
>    really want to. `example: "{\"foo\":\"bar\"}"` is not very usable in templates.
>
>    Look at places in the code where we have to work around setting maps in maps,
>    etc. An untyped language would probably be a lot easier.

I agree that the maps of maps we are putting together for the templates are a ugly, even more where we are trying to extract stuff from the nested maps again in Java. I'm not sure that using an untyped language is the way to go, though – one could possibly just use a set of classes made for this goal instead of generic collections.

(I don't understand the relation to examples. If the API definition contains the example as a string instead of a JSON object, how does this relate to the choice of a dynamic language in order to use this from a template?)

**Comment by cbornet** [comment]
Yes I share the pain when it comes to static classes used in our templates (try to add a custom field to a CodegenProperty and you'll see what @fehguy means) and we can't workaround that in the template itself since they are logic-less.
Then @fehguy, what do you suggest ? Going javascript (node/npm I imagine) ?
At least JS is known by everyone and I think there is already a good parser existing. We could also have a nice templating system (I use ejs in another project but there are plenty others used in front-end dev). But that's still a huuuge rework...

**Comment by ePaul** [comment]
@cbornet I wouldn't say "JS is known by everyone". (Generally, most all-quantified assertions are wrong.)

(Maybe "Many developers which would be interested in Swagger-Codegen know enough JavaScript to understand basic stuff." could be true.)

**Comment by cbornet** [comment]
Lol. Yes your one is better :smile: . I could also have said: "Unfortunately, any dev has been forced to use this flawed language once in its life :smile: !"

**Comment by dlamblin** [comment]
Cool kids [parse with Go](https://blog.gopheracademy.com/advent-2014/parsers-lexers/), but please keep using Java. I'm assuming this is soon to be closed?

**Comment by ramzimaalej** [comment]
@wing328 are we still considering this or we can close the ticket? 

It's also not clear to me what we are trying to achieve by switching to another programming language

**Comment by wing328** [comment]
@ramzimaalej yup, I think we can close it for now as there's no plan to switch to another language.
