### ISSUE TITLE
[swagger, all] Integer enum parameters are not put into swagger model

### ISSUE THREAD

**Issue by checat** [swagger-api/swagger-codegen#3964]
##### Description

Proper descriptions for integer enum parameters are not present with neither `-l swagger` nor `-DdebugOperations`.
##### Swagger-codegen version

2.2.1 and current master
##### Swagger declaration file content or url

Source JSON: https://gist.github.com/checat/1d9b014e39e9767cf30ba401d2cf18c4#file-source-json

Result JSON: https://gist.github.com/checat/1d9b014e39e9767cf30ba401d2cf18c4#file-swagger-json
##### Command line used for generation

`java -DdebugOperations -jar swagger-codegen-cli-2.2.1.jar generate -i source.json -l swagger -o out-swagger`
##### Steps to reproduce

Just generate. See result contains `"enum" : [ null, null ]` for "integerEnum" and does not contain "enum" for "integerArrayEnum", while string parameter has proper output
##### Related issues
#2508

**Comment by checat** [comment]
I assume other non-string types are affected the same way.

**Comment by fehguy** [comment]
Fixed by latest parser.

**Comment by jtegile** [comment]
While the latest parser works, the generated java client code is not compilable (and Ruby as well).

##### For java, the compilation error looks like
`incompatible types: int cannot be converted to java.lang.String` due to use of `@SerializedName(1)`

##### For Ruby, the error looks like
`syntax error, unexpected '=', expecting keyword_end (SyntaxError)
    0 = 0.freeze`
