### ISSUE TITLE
[Python] Camel case seems to be not applied to classes' names

### ISSUE THREAD

**Issue by khorolets** [swagger-api/swagger-codegen#3988]
##### Description

I am using swagger-codegen to generate python lib. Everything is working. 

But for urls similar to `/data_sources/` class that generated is named `DatasourcesApi`. I suspect that function that makes it camel cased didn't work.

Can you help me? Thank you!

##### Swagger-codegen version

2.2.1 (current stable)

**Comment by wing328** [comment]
Class name is determined by `tags`. What's the `tags` for the endpoints in question?

**Comment by khorolets** [comment]
@wing328 Thank you for your attention.

Here is the tags

```
"tags": [
    "data_sources"
]
```

**Comment by wing328** [comment]
@khorolets it turns out the `tags` name has already been cleaned up before reaching the Python generator (e..g fake_class_name_tags becomes Fakeclassnametags). We'll probably need to modify the default generator to remove that logic.

It should be done over the weekend. Will keep you posted.

Thanks again for reporting the issue.

**Comment by khorolets** [comment]
@wing328 Thank you!

**Comment by wing328** [comment]
@khorolets it's actually a quick fix: https://github.com/swagger-api/swagger-codegen/pull/3995

Note that I've filed it against 2.3.0 since it's breaking change.

**Comment by wing328** [comment]
PR merged into 2.3.0. Please pull the latest to give it a try.

**Comment by khorolets** [comment]
@wing328 Thank you very much, works as expected! You're awesome!
