### ISSUE TITLE
[JavaScript] ES6 modules without Typescript

### ISSUE THREAD

**Issue by bziorkiewicz** [swagger-api/swagger-codegen#4044]
Is there a way to use generated client with es6 modules but without installing typescript and core-js? My project is based on Webpack and Babel and I don't wan't to install typescript only for this one file. On the other hand pure JS client is based on old modules specification, and babel/webpack can't build this. Does somebody succeeded to run this with pure es6? Can you share your setup?

**Comment by triptec** [comment]
in our webpack config we have
```javascript
...
  resolve: {
    modulesDirectories: ['node_modules', '../node_modules/swagger-client/src'],
  },
...
```
and use it like
```javascript
import * as SwaggerClient from 'swagger-client'
```

**Comment by triptec** [comment]
But I'd love a es6 client, if you would like to create one I'd would love to help.

**Comment by tonyxiao** [comment]
Ideally we can support flowtype as well in addition to typescript. This makes it really awesome for all the react projects.

**Comment by dinukadesilva** [comment]
@wing328 @bziorkiewicz @triptec @tonyxiao 
Having ES6 support without typescript would be ideal especially for react projects. And even I'm looking for that.

Is there anyone who is working on this feature. If not, I would like to contribute. 

Regards,
Dinuka.

**Comment by wing328** [comment]
@dinukadesilva I don't think anyone is working so please contribute if you've time.

As discussed, we can add an option "enableES5Compatibility" (default to false) so that the generated code is compatible with ES5 (introduced back in 2012). If that option is not specified, the generated code will be compatible with ES6+ only. The change should be based on and submitted against 2.3.0 branch, which contains other breaking changes.

cc @triptec

**Comment by triptec** [comment]
No I'm not currently working on this but would be very happy to see it!
Go @dinukadesilva  ;)

**Comment by wing328** [comment]
@triptec when you 've time, you may want to take a look at https://github.com/swagger-api/swagger-codegen/issues/5470 to see if you've any feedback.

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/pull/5593 by @dinukadesilva has been merged into mastesr. Please pull the latest master to give it a try.

**Comment by frol** [comment]
Can anyone clarify why ES6 code generation is needed? I have been successfully using the module generated for "old" JS in my ES6 webpack-enabled project for over a half a year now (indeed, I had to configure webpack [#3466], but that is not hard at all). There must be a reason, but I don't see one.

P.S. The reason I ask is due to the fact that another JS implementation increased the maintenance complexity of all those JS variants...
