### ISSUE TITLE
Need upgrade scala version to 2.11 

### ISSUE THREAD

**Issue by netroby** [swagger-api/swagger-codegen#406]
[netroby@localhost swagger-codegen]$ ./bin/validate.sh 
Please set scalaVersion := "2.11" in build.sbt and run ./sbt assembly

**Comment by webron** [comment]
We're concentrating our work on the develop_2.0 branch which is just like the master, only much much better. It's also based on Java instead of scala and will help us rid of all the version compatibility support involving scala.

I'd suggest using using the develop_2.0 branch now and avoid all this hassle.
