### ISSUE TITLE
aspnet5 still apears as an available config even though it's deprecated

### ISSUE THREAD

**Issue by ogreenz** [swagger-api/swagger-codegen#4121]
when I try to generate with a nonexisting language I get the following message:
```
Exception in thread "main" java.lang.RuntimeException: Can't load config class with name **Available: android
aspnet5
aspnetcore
async-scala
cwiki
csharp
cpprest
dart
flash
python-flask
go
...
```
aspnet5 should be removed from that list since it's deprecated and doesn't work.

**Comment by jimschubert** [comment]
@ogreenz Thanks for reporting this.

The intention was to deprecate aspnet5 with a message that it's been deprecated. Unfortunately, I didn't set the template directory for the `aspnet5` generator to be the renamed `aspnetcore` directory.

Ideally, we'd want to maintain the deprecation for at least one minor release to give users time to update any automated build processes. You're seeing it because you're either working off master or a SNAPSHOT, or generating from editor.swagger.io/generator.swagger.io which I believe are deployed from master.

I'll fix this up and open a PR.

**Comment by wing328** [comment]
PR merged. Issue closed.
