### ISSUE TITLE
[Python] (question) How to connect to two different hosts

### ISSUE THREAD

**Issue by jdevera** [swagger-api/swagger-codegen#4240]
The Configuration object is a singleton in the generated swagger_client. I am trying to write code that connect to two servers serving the same API, but if I change the configuration:

```python
swagger_client.configuration.host = 'http://server2/api'
```

It changes for everything.

How do I get to talk to two different servers?

**Comment by wing328** [comment]
A workaround is to generate 2 Python SDKs with different `packageName`.

Ideally we should move away from singleton in Python to configuration per instance of API client similar to what we've done to Ruby, PHP, C#, etc. Please let me know if you've time to contribute the refactoring.

**Comment by jdevera** [comment]
Is there another open issue to track that refactoring? Otherwise it will get forever forgotten. I do not have time right now but if it is open and labelled in need of community contrib maybe somebody can tackle it in the future.

**Comment by wing328** [comment]
@jdevera good idea. Opened #4986 for tracking.

**Comment by jdevera** [comment]
Thanks @wing328 !

**Comment by qsorix** [comment]
Hi. I want to connect to many servers as well. The refactoring will help, but it will also require to change user's code, so that whenever API client is created, appropriate config is provided. A lot of hassle.

I have two use cases to cover. I can tackle them with customized templates, but if I succeed, I'd like to contribute it back, so let me know what you think the proper approach should look like. I'm generating clients to be used by developers and QAs, where swagger aims and API for end-users, so I can't easily get what I need.

Let's say the generated code makes all requests go to `https://example.com/`. That's fine for external end-users. Our API is based on microservices, and we use a URL prefix to route requests.

`https://example.com/service1/api/v1/endpoint` goes to `service1` which has `/api/v1/endpoint`.

Note that if I talk with a service directly, I do not want to include that prefix.

First use case: As an internal microservice developer, I want to use generated code to connect to my deployed API, with an exception of one backend service which I run locally. So all requests should go to `https://example.com/service*/api/...`, but one client should send requests to `http://localhost:8080/api/...` (different host, prefix stripped).

Second use case: As a developer, I want to use generated client to talk with services as another service on kubernetes. So now no request should go to `https://example.com/`. Instead, they should go to `http://service1/` and `http://service2/`. (again, stripping prefixes).

Have you thought about having some layer that captures the notion of environments, deployments, backends? Configuring that layer should be easier than configuring each instance of API client.
