### ISSUE TITLE
defaultValue cannot be set to empty string

### ISSUE THREAD

**Issue by hsanjuan** [swagger-api/swagger-codegen#43]
when a parameter type is 'string' a defaultValue of '' (empty string) does not get passed to the final generated [ruby] code.

**Comment by lugaru1234** [comment]
I believe 'default' values should not be used in the client at all, since 'default' is more of a way to tell the client - "if you don't provide the information
 , this is what's going to be used", so it ends up being redundant.
 In any way we can do one of the following things: 
 1. Leave default values without any processing at the clients side and clean up ruby templates;
 2. Leave things as is as we already don't have defaults processing in the generated code;
 3. Support processing of default values at the clients side for all languages as it's done for ruby.

**Comment by iushankin** [comment]
By the way in the core code annotation with empty default is simply ignored:
```java
          if(!param.defaultValue().isEmpty()){
            defaultValue = param.defaultValue();
          }
```
You can see https://github.com/swagger-api/swagger-core/blob/develop_2.0/modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java

**Comment by webron** [comment]
@fehguy - your opinion?

**Comment by xhh** [comment]
I agree with [lugaru1234](#issuecomment-91598368), default value should be for documentation purpose only, to simply the API client and let the API server handle it.

**Comment by fehguy** [comment]
@xhh @lugaru1234 Yes, ideally the default value should be applied by the server.  The codegen should probably not assume that the default value be passed if not supplied.

**Comment by hsanjuan** [comment]
Comments above are right. It's ugly and wrong to support defaultValue.

Either fully remove defaultValue from the swagger spec, or if it stays, then don't discriminate default values like empty strings or null... the whole point with default values is they came in handy with the default ruby-generated-code as they became optional method parameters.

Anyway, default Ruby code used to suck in many other places, so I guess its users' responsibility to take the example and fix it to avoid duplication and support optional parameters without default values (for example this issue can be addressed passing parameters in an opts Hash instead of separately)..
