### ISSUE TITLE
PowerShell module

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#4320]
##### Description

To add a code generator to generate PowerShell module for accessing REST API.

##### Swagger-codegen version

Future

##### Details

If anyone is interested in or has already started working on a code generator for PowerShell module, please reply to let us know.

**Comment by beatcracker** [comment]
Just FIY: since you already have a C# generator, you could just make a thin PowerShell wrapper around generated C# code. This could save some time.

**Comment by wing328** [comment]
@beatcracker thanks for the suggestion. May I know if you've time to contribute the PowerShell generator?

**Comment by beatcracker** [comment]
@wing328 Depends on what you need. I can help with PowerShell code, but unfortunately I can't do Java (which is actually used to write generators, right?).

**Comment by wing328** [comment]
@beatcracker We can work together on that 😃 

I think a good starting point is to create a PowerShell wrapper for [PetStore](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml) by focusing on a few endpoints.
- [GET](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L156-L183)
- [POST (form)](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L184-L218)
- [POST (JSON body)](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L31-L56)

The PowerShell code can be put in the folder `samples/client/petstore/powershell`.

Then we can reverse-engineer the PowerShell code to create the templates and the generator in Java.

What do you think?

**Comment by beatcracker** [comment]
I had a look at C# generators, and it's dawned on me, what a can of worms I just opened 😰. 

I'll try summarize my thoughts here, at least for my own sake, before I try to do some kind of MVP PowerShell module example.

---

## How do we generate a PowerShell code?

### Using PowerShell wrappers for C#

#### Pros:

Since we have C# generators for almost every .NET targets available (2.0, 4.0, etc...), this makes it easy to support down-level (PS 2-4) and constrained ([PowerShell Core](https://technet.microsoft.com/en-us/windows-server-docs/get-started/developing-powershell-cmdlets-for-nano-server#porting-powershell-script-cmdlets)) platforms. Given the fact, that [Invoke-RestMethod](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.utility/invoke-restmethod)/[Invoke-WebRequest](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.utility/invoke-webrequest) cmdlets that allow to make web API calls are only PS 3.0+, this seems like a way to go.

#### Cons:

We have to include NuGet dependencies in the module package and generate a module manifest accordingly.

### Native PowerShell

#### Pros:

With native PowerShell code it makes sense to support at least PS 3.0+. Additionally, for PS 5.0+ we could generate code based on [clasess](https://xainey.github.io/2016/powershell-classes-and-concepts/), instead of traditional function-based approach.

#### Cons:

Somewhat limited platform support, harder to make one-size-fits all code, since we have to account for different engine behavior and cmdlet availability on various PS versions.

## How do we build a PowerShell module?

### Use C# sources as-is, compile at the runtime

#### Pros:

PowerShell can compile C# code at the runtime using [Add-Type](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.utility/add-type) cmdlet, so we don't have to build assemblies ourselves.

#### Cons:

This will add noticeable delay during module import and requires end user to have [.NET Framework 3.5 to be installed](https://github.com/beatcracker/Ori-Controller-Remap/issues/1#issuecomment-176254354) for `csc.exe` (which is not by default on Windows 8+).

### Use pre-built binaries

#### Pros:

C# client API libraries can be built in-place and added to the module manifest. During module import PowerShell will load required assemblies automatically. Much faster then building from C# source at the runtime.

#### Cons:

We have to build assemblies ourselves while generating PS module and add them to the module manifest.

## How do we generate module manifest?

### Using some sort of template in Java code inside the generator itself

#### Pros:

No external dependencies.

#### Cons:

Error-prone, reinventing the wheel, since PowerShell can do it for us with [New-ModuleManifest](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/new-modulemanifest) cmdlet.

### Using native PowerShell cmdlets

#### Pros:

Native, no NIH syndrome.

#### Cons:

Requires PowerShell to build the module, which limits platforms where module can be built (Linux) while PS 6.0 is still in alpha. Even when PS  6.0 is released, this is still an external dependency.

## How do we build a module package?

Well-written PowerShell module requires good amount of scaffolding, especially if it's to be uploaded to the PowerShell Gallery.

* Producing well-formed module structure
* Creating help files and/or heredoc help for functions
* Providing [Formats](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/about/about_format.ps1xml)/[Types](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/about/about_types.ps1xml)
* Modifying module manifest. E.g.: `FunctionsToExport` should be explicitly defined to make module more discoverable in PowerShell Gallery.
* Module versioning.
* Module [GUID](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/new-modulemanifest#-guid)

This scaffolding is already available, but usually requires some kind of CI system (AppVeyor, Jenkins, TeamCity, etc..). Should we go full frontal and support all this stuff, which could require us to write our own scaffolding, or do we take a minimal approach and just ignore this issue for now?

Here is good write-ups on module building:

* [Building a PowerShell Module](http://ramblingcookiemonster.github.io/Building-A-PowerShell-Module/)
* [Hitchhikers Guide to the PowerShell Module Pipeline](https://xainey.github.io/2017/powershell-module-pipeline/)

---

**Comment by wing328** [comment]
> Should we go full frontal and support all this stuff, which could require us to write our own scaffolding, or do we take a minimal approach and just ignore this issue for now?

I prefer the latter - minimal approach as the MVP (minimum viable product) version will serve as a good starting point for PowerShell community to further enhance it.

**Comment by beatcracker** [comment]
@wing328 Ok, I'm on it. I already have a working prototype and I expect to share it in a day or two.

**Comment by beatcracker** [comment]
I've pushed MVP [PowerShell module](https://github.com/beatcracker/swagger-codegen/tree/posh/samples/client/petstore/powershell/PowerShellClient) to my fork.

You can build it using `Build.ps1` script. This is what's done for now:

Functions for:

- [x] [GET](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L156-L183)
- [x] [POST (form)](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L184-L218)
- [x] [POST (JSON body)](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L31-L56)

Module manifest:

- [x] Well-formed module structure
- [X] Generate `FunctionsToExport`
- [x] Comment-based help for functions
- [x] Basic `about` help file
- [x] Module GUID (static)
- [ ] Formats
- [ ] Types
- [ ] Module versioning

The API objects are [created on the module import](https://github.com/beatcracker/swagger-codegen/blob/posh/samples/client/petstore/powershell/PowerShellClient/src/IO.Swagger/IO.Swagger.psm1#L31-L36) and functions reuse them internally, since I don't think that we should create them on every function call.

Authorization is handled via [Set-ApiCredential](https://github.com/beatcracker/swagger-codegen/blob/posh/samples/client/petstore/powershell/PowerShellClient/src/IO.Swagger/Public/Set-ApiCredential.ps1) function, which modifies default client configuration.

I've tried to write a module with code generation in mind, so it's feels a bit "mechanistic". For example, functions for `UpdatePet` and `UpdatePetWithForm` methods, should be combined to one function that accepts either separate arguments or `IO.Swagger.Model.Pet` object. I'm not sure how this should be handled on the generator's side, but I've included [Update-PetUsingParameterSet](https://github.com/beatcracker/swagger-codegen/blob/posh/samples/client/petstore/powershell/PowerShellClient/src/IO.Swagger/Public/Update-PetUsingParameterSet.ps1) function to illustrate this approach.

Functions in the `Private` folder are internal and not exported from module. They're used to format debug output.

Variables names that are supposed to be generated are wrapped in the [curly braces](http://stackoverflow.com/questions/36773800/do-curly-braces-mean-anything-in-powershell-variable-declaration), e.g.: `${Id}`.

**Comment by wing328** [comment]
> For example, functions for UpdatePet and UpdatePetWithForm methods, should be combined to one function that accepts either separate arguments or IO.Swagger.Model.Pet object. 

Currently, other generators do not such functionality either because it's hard to tell which methods can be combined into one. If the REST API owner wants to provide a high level operation A to do both B and C, the best they can do at the moment is to define another endpoint "A" in the OpenAPI spec and manually update the auto-generated code to call B, C directly instead.

**Comment by wing328** [comment]
@beatcracker I would recommend you to create a PR to add the PowerShell generator at this stage so as to collect feedback from the PowerShell community.

Let me know if you need help with the PR.

**Comment by wing328** [comment]
@beatcracker https://github.com/swagger-api/swagger-codegen/issues/5509 has been merged into mster.

**Comment by wing328** [comment]
@beatcracker as #5509 only contains the Petstore sample (PowerShell), do you need help adding the PowerShell generator and templates to Swagger Codegen?

We'll release 2.3.0 soon so we hope to include the PowerShell generator as well. (new generators added to current master will be sync'd to 2.3.0)

**Comment by wing328** [comment]
@beatcracker if you don't mind, please drop me an email (in my Github profile) when you've time as I got a question for you.

**Comment by beatcracker** [comment]
@wing328  Hi, sorry for abrupt disappearing, I've got tangled up with work. I've dropped you a email.

> ...do you need help adding the PowerShell generator and templates to Swagger Codegen?

As I've already said, I can't do Java, but I had a look at the mustache and while I don't have any experience with it, it looks like something I'm able to help with (at least partially).

**Comment by wing328** [comment]
I've filed #5789, which is still work-in-progress. Let's continue the discussion in that PR.
