### ISSUE TITLE
Regression: Files specified in .swagger-codegen-ignore is being overwritten in 2.2.2 (master). Its was working in 2.2.1 

### ISSUE THREAD

**Issue by sathya-bhat** [swagger-api/swagger-codegen#4452]
##### Description
Files specified in '.swagger-codegen-ignore' is being overwritten in the latest master. It was working in 2.2.1.

I had to pull master due to another issue :https://github.com/swagger-api/swagger-codegen/issues/3612

##### Swagger-codegen version
2.2.2 (master). Its a regression from 2.2.1

##### Swagger declaration file content or url

swagger-codegen-ignore file

# Swagger Codegen Ignore
AboutApiServiceImpl.java

##### Command line used for generation
java -jar c:/swagger-codegen-cli-2.2.1/swagger-codegen-cli.jar generate -l jaxrs -i ./Test.json -o ./build
....
[main] INFO io.swagger.codegen.DefaultGenerator - Skipped overwriting c:\Temp\test\.\build/src/main/java/io/swagger/api/impl/AboutApiServiceImpl.java
.....
+++++++++++++++++++++++++++++++++++++++++++
java -jar c:/swagger-codegen-cli-2.2.2/swagger-codegen-cli.jar generate -l jaxrs -i ./Test.json -o ./build

[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\Temp\test\.\build/src/main/java/io/swagger/api/impl/AboutApiServiceImpl.java
##### Steps to reproduce
Add a pattern to ignore (sa: *Impl.java) in .swagger-codegen-ignore file. Generate jaxrs server code using 2.2.1 swagger cli and latest master. Latest master unconditionally overwrites the *Impl.java generated file.

**Comment by wing328** [comment]
@sathya-bhat thanks for reporting the issue. Using latest master, I did a test with `./bin/csharp-petstore.sh` and got the following (last line in the output):
```
[main] INFO io.swagger.codegen.DefaultGenerator - Skipped generation of /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger.Test/IO.Swagger.Test.csproj due to rule in .swagger-codegen-ignore
```
If you run `.\bin\windows\csharp-petstore.bat`, did you get something similar to prove that the file has not been overwritten due to rule in .swagger-codege-ignore?

(I'm using Mac, not Windows)

**Comment by sathya-bhat** [comment]
Thanks for quick response. If you observe, one difference is that in 2.2.2, its io.swagger.codegen.AbstractGenerator vs io.swagger.codegen.AbstractGenerator in 2.2.1.

**Comment by wing328** [comment]
Was `.swagger-codegen-ignore` overwritten as well?

**Comment by sathya-bhat** [comment]
No, '.swagger-codegen-ignore' file was not overwritten. Also the POM.XML file was also left there. Only the generated code stubs got overwritten.

**Comment by jimschubert** [comment]
From the log messages you posted, it looks like this is getting processed before the swagger-codegen-ignore handles the overwrite in 2.2.1.

Messages from swagger-codegen-ignore preventing overwrite clearly indicate the cause is the ignore file:

```
LOGGER.info("Skipped generation of " + outputFilename + " due to rule in .swagger-codegen-ignore");
```

It looks like this was getting stopped by `config.shouldOverwrite` and not the .swagger-codegen-ignore entry in 2.2.1. I haven't been able to track down where there would be a breaking change with respect to that default behavior.

For 2.2.2, could you try the command without a relative output path?

```
java -jar c:/swagger-codegen-cli-2.2.2/swagger-codegen-cli.jar 
    generate -l jaxrs -i ./Test.json -o build
```

Since the rules in `.swagger-codegen-ignore` are processed through Java's FileSystems API, I'm wondering if the `./` is being processed oddly by the glob. I'll test out these assumptions locally, but I may not get a chance over the next week or so.

**Comment by sathya-bhat** [comment]
No change in behavior after specifying absolute path for output.
My .swagger-codegen-ignore file has following entries at the end.
pom.xml
*Impl.java

With swagger 2.2.1
java -jar c:/Temp/test/2.2.1/swagger-codegen-cli.jar generate -l jaxrs -i ./Test.json -o c:/Temp/test/221build

[main] INFO io.swagger.parser.Swagger20Parser - reading from ./Test.json
[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting pom.xml as the file already exists in c:\Temp\test\221build\\pom.xml
....
[main] INFO io.swagger.codegen.DefaultGenerator - Skipped overwriting c:\Temp\test\221build/src/main/java/io/swagger/api/impl/AboutApiServiceImpl.java
...

With swagger 2.2.2
java -jar c:/Temp/test/2.2.1/swagger-codegen-cli.jar generate -l jaxrs -i ./Test.json -o c:/Temp/test/221build

[main] INFO io.swagger.codegen.DefaultCodegen - Skipped overwriting pom.xml as the file already exists in c:\Temp\test\222build\\pom.xml
....
[main] INFO io.swagger.codegen.AbstractGenerator - writing file c:\Temp\test\.\222build/src/main/java/io/swagger/api/impl/AboutApiServiceImpl.java
....

**Comment by jimschubert** [comment]
@sathya-bhat I've opened PR #4476 to fix an issue with the path separator in Windows.

Thanks for sharing your `.swagger-codegen-ignore` contents, it helped.  The implementation of the ignore pattern handling is based directly off of git's man page, which says a pattern like `*Impl.java` is treated as a shell glob pattern at the same level as the `.gitignore` (in our case, `.swagger-codegen-ignore`). So, this is working as intended. I realized while investigating that the relevant tests were missing, so the intention wasn't explicit. Sorry about that.

To resolve your issue, you should be able to update your pattern to `**/*Impl.java`. You're welcome to evaluate the branch on my pull request in case the POSIX-compliant path separator is causing problems. I know it used to be fully supported, but I haven't used Windows as my OS for a while and I'm not sure if this is still the case in Windows 8 and higher. I did some local testing and didn't notice a difference, so the fix may only be cosmetic.

**Comment by jimschubert** [comment]
@wing328 This issue is referenced as a regression in `.swagger-codegen-ignore`, but as I mentioned in an earlier comment, the regression would be with `shouldOverwrite` since neither case was triggering the ignore rule. That regression should still be evaluated, or documented as a breaking change if it was intentional.

**Comment by jimschubert** [comment]
I've run `git bisect start master v2.2.1` with the following evaluation script:

```
#!/bin/bash

set -exo pipefail

SWAGGER_DIR="/Users/${USER}/projects/swagger-codegen"
SWAGGER_DEF="${SWAGGER_DIR}/modules/swagger-codegen/src/test/resources/2_0/petstore.json"
SWAGGER_CLI_JAR="${SWAGGER_DIR}/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar"
SWAGGER_OUT_DIR="/Users/${USER}/temp/issues/swagger-codegen/4452/out"

# Build and run current swagger-codegen
cd ${SWAGGER_DIR} && \
mvn clean package -Dmaven.test.skip=true -DskipTests && \
echo "First pass" && \
java -jar ${SWAGGER_CLI_JAR}  generate -l jaxrs -i ${SWAGGER_DEF} -o "${SWAGGER_OUT_DIR}"

# Checks
CHECK_FILE=${CHECK_FILE:-${SWAGGER_OUT_DIR}/src/main/java/io/swagger/api/impl/UserApiServiceImpl.java}
LAST_MOD=$(stat -f "%m" "${CHECK_FILE}")

echo "Last modified: ${LAST_MOD} (${CHECK_FILE})"

echo "Second pass" && \
java -jar ${SWAGGER_CLI_JAR}  generate -l jaxrs -i ${SWAGGER_DEF} -o "${SWAGGER_OUT_DIR}"

if (( ${LAST_MOD} < $(stat -f "%m" ${CHECK_FILE}) )); then
    echo File was modified. Regression found.
    exit 1
fi

echo File was not modified
exit 0
```

Then, run `git bisect run /path/to/the/above/script`.

This script runs the `jaxrs` generator against the sample petstore.json definition from the test directory, then checks the file mtime between two runs of the generator. It considers the currently evaluated commit as a regression if the mtime is different (because the file generation was not skipped as it was in v2.2.1).

I've found a commit that bisect considers the first commit of the regression, however I don't have time to dig through the commit right now because it's pretty large. I'm sharing this in case someone can evaluate before I get to it.

```
a5eff7e571cc22d4148ef0073824f35c8ceee342 is the first bad commit
commit a5eff7e571cc22d4148ef0073824f35c8ceee342
Author: scannerscan <alexey.pustovoyt@gmail.com>
Date:   Tue Nov 1 19:36:56 2016 +1100

    Jdk6 jersey2 support (#4074)

    * hashCode and equals support for jdk6 for jersey2

    * supportJava6 moved to the base abstract class to support server side code generation,
    supportJava6 flag was added to the server side model classes generators,
    licenseInfo ttemplate was added to JavaJaxRS section,
    javaJaxRS templates jdk6 suport was added,
    shouldOverride method was commented out to allow server classes to be overriden - what if new methods or signatures changes?

    * fix for the build.

    * supportJava6 moved to the base abstract class to support server side code generation,
    supportJava6 flag was added to the server side model classes generators,
    licenseInfo ttemplate was added to JavaJaxRS section,
    javaJaxRS templates jdk6 suport was added,
    shouldOverride method was commented out to allow server classes to be overriden - what if new methods or signatures changes?

    * fix for the build.

    * Merge remote-tracking branch 'remotes/origin/master' into jdk6-jersey2-support

    Conflicts:
            modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
            modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
            modules/swagger-codegen/src/main/resources/Java/pom.mustache

    * add msf4j author

    * [Java] Fix outputFolder in java-related server stub generators (#4076)

    * fix outputFolder in java-related server stub generator

    * fix style in JavaJAXRSCXFCDIServerCodegen

    * hashCode and equals support for jdk6 for jersey2

    * supportJava6 moved to the base abstract class to support server side code generation,
    supportJava6 flag was added to the server side model classes generators,
    licenseInfo ttemplate was added to JavaJaxRS section,
    javaJaxRS templates jdk6 suport was added,
    shouldOverride method was commented out to allow server classes to be overriden - what if new methods or signatures changes?

    * fix for the build.

    * supportJava6 moved to the base abstract class to support server side code generation,
    supportJava6 flag was added to the server side model classes generators,
    licenseInfo ttemplate was added to JavaJaxRS section,
    javaJaxRS templates jdk6 suport was added,
    shouldOverride method was commented out to allow server classes to be overriden - what if new methods or signatures changes?

    * Merge remote-tracking branch 'remotes/origin/master' into jdk6-jersey2-support

    Conflicts:
            modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
            modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
            modules/swagger-codegen/src/main/resources/Java/pom.mustache

    * Merge remote-tracking branch 'remotes/origin/master' into jdk6-jersey2-support

    Conflicts:
            modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaCodegen.java
            modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaClientCodegen.java
            modules/swagger-codegen/src/main/resources/Java/pom.mustache

:040000 040000 87ba69df632b2d1436e1d8cf5a5f54efee2af775 ea4023e059a96b4ac6070e4874650c582e45e9a8 M	modules
bisect run success
```

**Comment by jimschubert** [comment]
The changes from that commit weren't actually that bad to look through…

```diff
diff --git a/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaJAXRSServerCodegen.java b/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaJAXRSServerCodegen.java
index 9ed9648..de0812c 100644
--- a/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaJAXRSServerCodegen.java
+++ b/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaJAXRSServerCodegen.java
@@ -200,10 +200,4 @@ public abstract class AbstractJavaJAXRSServerCodegen extends AbstractJavaCodegen
     private String implFileFolder(String output) {
         return outputFolder + "/" + output + "/" + apiPackage().replace('.', '/');
     }
-
-    @Override
-    public boolean shouldOverwrite(String filename) {
-        return super.shouldOverwrite(filename) && !filename.endsWith("ServiceImpl.java") && !filename.endsWith("ServiceFactory.java");
-    }
-
 }
```

It looks like that change removed the exclusion of any files ending in `ServiceImpl.java` or `ServiceFactory.java`.

> shouldOverride (sic) method was commented out to allow server classes to be overriden - what if new methods or signatures changes?

@wing328 I had considered opening a new PR to add this back in. However, I somewhat agree with the removal. It seems a little heavy handed to never allow `*ServiceImpl.java` or `*ServiceFactory.java` to be regenerated.

With the support of `.swagger-codegen-ignore`, I think we would be better off documenting the explicit skip via an ignore rule in a wiki tutorial rather than forcing this directly in the generator. The reasoning being that a user can comment/uncomment the ignore file and re-run the generator while adding and removing the above constraints require a code change. Although I haven't looked through the template's code to see if the built-in templates have much logic in these files, hard-coding these exclusions could be a surprise to users who provide their own templates.

We may want to include this as a breaking changes note in the v2.2.2 release notes.

@sathya-bhat Does the breaking change and my explanation above about why it's preferable to use `.swagger-codegen-ignore` make enough sense? Let me know if you need additional help with the workaround I mentioned above (changing `*Impl.java` to `**/*Impl.java`).

**Comment by wing328** [comment]
>  It seems a little heavy handed to never allow *ServiceImpl.java or *ServiceFactory.java to be regenerated.

Yes, the `swagger-codegen-ignore` file can replace the logic and eventually `swagger-codegen-ignore` should be the only place to determine if a auto-generated file should be overwritten.

I totally agree a tutorial to walk through a use case will better explain the usage of `swagger-codegen-ignore`

**Comment by wing328** [comment]
@sathya-bhat https://github.com/swagger-api/swagger-codegen/pull/4476 has been merged into master. Please pull the latest to give it another try.

**Comment by sathya-bhat** [comment]
Thanks for the suggestion. I changed
*Impl.java to **/*Impl.java in .swagger-codegen-ignore file and the files are not being overwritten. I tested this with 2.2.2 latest master.

[main] INFO io.swagger.codegen.DefaultGenerator - Skipped generation of c:\Temp\test\.\2221build\src\main\java\io\swagger\api\impl\AboutApiServiceImpl.java due to rule in .swagger-codegen-ignore

We can close this issue.
