### ISSUE TITLE
[Maven-Plugin] Specify location of swagger-codegen-ignore 

### ISSUE THREAD

**Issue by jfiala** [swagger-api/swagger-codegen#4514]
##### Description

For the Swagger swagger-codegen-maven-plugin it would be nice to be able to specify the location of the .swagger-codegen-ignore file, as the generated files always go to "target/..." and thus the .swagger-codegen-ignore file cannot be used at the target location.

Right now, the generated files can only be influenced using CLI flags as available.

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Suggest a Fix

add a CLI-parameter to specifiy the location of the .swagger-codegen-ignore file (maybe this is usable for the CLI as well as the maven task)

**Comment by jimschubert** [comment]
@jfiala the .swagger-codegen-ignore is really intended to prevent the generator from overwriting pre-existing files in your target directory.

It sounds like you're looking for the [selective generation](https://github.com/swagger-api/swagger-codegen#selective-generation) options, which I'm not sure if this is what you're referring to by "files can only be influenced using CLI flags as available". If that's the case, are you more interested in the .swagger-codegen-ignore over the supported system properties specifically for the pattern support?

I'd like to suggest rather than specifying an override location, that the location be additive to the existing .swagger-codegen-ignore. What are your thoughts on this?

I'd also considered adding support for evaluating rules from .swagger-codegen-ignore files in parent directories in the same way .gitignore works, but I have concerns about this approach solely based on how many times a .gitignore in my home directory has caused a lot of grief.

**Comment by jfiala** [comment]
@jimschubert thx for your comment, I want to use maven and only want the api interfaces generated to the target folder, without any clutter (config files etc.). Currently there is no way to remove the unwanted files from the target folder. 

I also discussed this with @wing328, I think it would be good to have an option to generate only interfaces for all languages that provide ones. 

However, I think it is still necessary to support an ignore file to fine-tune the configuration. People who don't like this don't have to use it, but the end-of-pipe solution gives the biggest flexibility.
The current behaviour of having to put the .swagger-codegen-ignore file to the target directory is unsatisfying.

So my suggestion would be:
1.) add a cross-language option to generate only interfaces without impl/tests/config whatsoever
(for Jaxrs languages this will in fact mean that the interfaces should be identical finally!)
2.) allow to specify the location of the .swagger-codegen-ignore file at least for the maven task

**Comment by jimschubert** [comment]
@jfiala I've opened a PR for the override of the ignore file. When you get a chance, can you test it out?

**Comment by jimschubert** [comment]
Also, I think suggest \#1 should probably be a separate issue because I don't think it'll be a trivial pickup.

**Comment by jfiala** [comment]
@jimschubert number 2 works great, yes lets move number 1 to a separate issue.

**Comment by wing328** [comment]
PR by @jimschubert merged into master. Closing this one.

For 1, please open a new issue for tracking.

**Comment by jfiala** [comment]
created #4610 to track number 1, so we can close this one.

**Comment by sompa** [comment]
Any update on number 1 that was requested ? I am having a similar situation where I only want to generate the api interfaces and models and not the implementation files. Please suggest. I am using the swagger-codegen-maven-plugin and would want it to not generate any implementation files. Would be good to have a flag to do so.

**Comment by jimschubert** [comment]
@sompa The option for number 1 was found to work well enough with the -Dmodels switch for selectively generating models only (see #4610). If you name interfaces by convention (I-prefixed or separate namespace), you should be able to use the ignore file.
