### ISSUE TITLE
Create swift templates

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-codegen#471]

**Comment by dag-io** [comment]
Yes please ! I can not wait to have it

**Comment by SixArm** [comment]
+1

**Comment by yissachar** [comment]
I started work on this here: https://github.com/yissachar/swagger-codegen/tree/swift

Current limitations:
- File upload doesn't work
- Only JSON is supported
- id properties not serialized/deserialized

There may be other issues as well - this is a WIP.

**Comment by olensmar** [comment]
awesome - i'll have a look as soon as I get some time

**Comment by joelparkerhenderson** [comment]
Excellent, thank you. 

If you're open to feedback, here are two small items that I see:

   * Is it possible to use capitalization "API" instead of "Api"? This is because of Swift naming conventions (e.g. abbreviations are all caps, such as API, URL, HTTP), and also because of editors with case-sensitive tab completion and searching.

   * I suggest error message strings that are very short, similar to HTTP error titles. E.g. prefer "Deserialization Failure" instead of "Could not deserialize response". This is because it's the short messages are easier to search, and easier to localize, and easier for non-native-English speakers to use.

Thanks again, this is terrific.

**Comment by fehguy** [comment]
To change the name of the API class, simply add this to your generator:

```java
  @Override
  public String toApiName(String name) {
    return initialCaps(name) + "API";
  }
```

**Comment by yissachar** [comment]
@joelparkerhenderson Thanks for the feedback! Both are valid suggestions, and I've implemented them.

@fehguy Thanks, worked like a charm.

I've also fixed the serialization/deserialization errors that were occurring.

**Comment by andreaskumlehn** [comment]
+1

**Comment by wing328** [comment]
Closing this as the Swift template has been added.
