### ISSUE TITLE
[ANDROID] Bug reserved words in enums not escaped

### ISSUE THREAD

**Issue by Hermanya** [swagger-api/swagger-codegen#5009]
##### Description

I have an enum which has a value of "transient". That is a reserved word on android. Generated project does not compile, because a reserved word used in enum value.

##### Swagger-codegen version

I'm using 2.3.0

##### Swagger declaration file content or url

    ```json
    {
      "definitions": {
        "Person": {
          "type": "object",
          "properties": {
            "quality": {
              "type": "string",
              "enum": [
                "something",
                "transient"
              ]
            }
          }
        }
      }
    }
    ```

##### Command line used for generation

java -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
    -i "swagger.json" \
    -l "android" \
    -o "output"

##### Related issues

https://github.com/swagger-api/swagger-codegen/issues/2362

**Comment by wing328** [comment]
@Hermanya thanks for reporting the issue. Can you also try the Java API client to see if it has similar issues?

https://github.com/swagger-api/swagger-codegen/wiki/FAQ#android

**Comment by Hermanya** [comment]
@wing328 Java client does not have this issue

**Comment by jitinsharma** [comment]
I tried debugging around this. Tried to generate java and android sdk with a .yaml file. The override method  `public String toEnumVarName(String value, String datatype)` should give enum variables so that escaping can be done. Tried printing all the values which came in this method. When doing this in JavaClientCodegen all enum variables are printed but when doing the same in AndroidClientCodegen many of these variables are not printed. Could this be related to parsing of .yaml file?
