### ISSUE TITLE
[C#] C# API client (.net v3.5) failed to compile

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#5122]
##### Description

C# API client (v3.5) failed to compile while v4.0 and v5.0 work fine.

The error message is as follows:
![screen shot 2017-03-20 at 5 14 30 pm](https://cloud.githubusercontent.com/assets/934260/24094535/159b006a-0d94-11e7-9e47-f37bf7012856.png)

##### Swagger-codegen version

Latest master

**Comment by Gronsak** [comment]
oh, looks like it doesn't support the IValidatableObject stuff, had to pull that same stuff out for the .NET Standard generation so the fix could be as easy as just changing the netStandard property used on [Line 8](https://github.com/swagger-api/swagger-codegen/blob/1c329483e47f1aad0fdb4e55cb457fb4467c02d0/modules/swagger-codegen/src/main/resources/csharp/modelGeneric.mustache#L8) & [Line 175-227](https://github.com/swagger-api/swagger-codegen/blob/1c329483e47f1aad0fdb4e55cb457fb4467c02d0/modules/swagger-codegen/src/main/resources/csharp/modelGeneric.mustache#L175-L227) in modelGeneric.mustache to filter it out for a more generic one so you can use it for both v3.5 and v.5.0

**Comment by wing328** [comment]
@Gronsak thanks for the feedback. I plan to introduce an additional tag "dotnet45" to output those lines if the target framework is v4.5 as later we want to merge c# 2.0 generator into the C# generator as well.

**Comment by jimschubert** [comment]
iirc, IValidatableObject wasn't an interface in .NET 3.5.

**Comment by jimschubert** [comment]
@wing328 there's already `targetFramework` and `targetFrameworkNuget` options, where `targetFramework` would hold an identifier like `v4.5` and `targetFrameworkNuget` would hold the nuget string such as `net45`. I think it would be overly confusing to have `dotnet45` which refers to  .NET 4.5 or higher, especially since .NET 4.5 and 4.6 aren't .NET Core and there will be many differences between .NET 4.5/4.6 and .NET Core.

Even if we went with the .NET Standard versioning, it would be confusing to define the "and higher" versioning in a meaningful way.

From https://docs.microsoft.com/en-us/dotnet/articles/standard/library: 
<table>
<thead>
<tr>
<th style="text-align:left">Platform Name</th>
<th style="text-align:left">Alias</th>
<th style="text-align:left"></th>
<th style="text-align:left"></th>
<th style="text-align:left"></th>
<th style="text-align:left"></th>
<th style="text-align:left"></th>
<th style="text-align:left"></th>
<th style="text-align:left"></th>
<th style="text-align:left"></th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">.NET Standard</td>
<td style="text-align:left">netstandard</td>
<td style="text-align:left">1.0</td>
<td style="text-align:left">1.1</td>
<td style="text-align:left">1.2</td>
<td style="text-align:left">1.3</td>
<td style="text-align:left">1.4</td>
<td style="text-align:left">1.5</td>
<td style="text-align:left">1.6</td>
<td style="text-align:left">2.0</td>
</tr>
<tr>
<td style="text-align:left">.NET Core</td>
<td style="text-align:left">netcoreapp</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">1.0</td>
<td style="text-align:left">2.0</td>
</tr>
<tr>
<td style="text-align:left">.NET Framework</td>
<td style="text-align:left">net</td>
<td style="text-align:left">→</td>
<td style="text-align:left">4.5</td>
<td style="text-align:left">4.5.1</td>
<td style="text-align:left">4.6</td>
<td style="text-align:left">4.6.1</td>
<td style="text-align:left">4.6.2</td>
<td style="text-align:left">vNext</td>
<td style="text-align:left">4.6.1</td>
</tr>
<tr>
<td style="text-align:left">Mono/Xamarin Platforms</td>
<td style="text-align:left"></td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">vNext</td>
</tr>
<tr>
<td style="text-align:left">Universal Windows Platform</td>
<td style="text-align:left">uap</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">10.0</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">vNext</td>
</tr>
<tr>
<td style="text-align:left">Windows</td>
<td style="text-align:left">win</td>
<td style="text-align:left">→</td>
<td style="text-align:left">8.0</td>
<td style="text-align:left">8.1</td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">Windows Phone</td>
<td style="text-align:left">wpa</td>
<td style="text-align:left">→</td>
<td style="text-align:left">→</td>
<td style="text-align:left">8.1</td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
</tr>
<tr>
<td style="text-align:left">Windows Phone Silverlight</td>
<td style="text-align:left">wp</td>
<td style="text-align:left">8.0</td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
<td style="text-align:left"></td>
</tr>
</tbody>
</table>

**Comment by Gronsak** [comment]
Just want to add that I discovered that `IValidatableObject` is a thing in .NET Standard just with an added dependency (thought it might be the case but couldn't find it before).

So I would personally go with a more generic exclusion tag like `Validatable` or something similar so you can switch it on where supported.

**Comment by wing328** [comment]
> I think it would be overly confusing to have dotnet45 which refers to .NET 4.5 or higher, especially since .NET 4.5 and 4.6 aren't .NET Core and there will be many differences between .NET 4.5/4.6 and .NET Core.

@jimschubert ok. I won't use `dotnet45`then. What about using something like `Validatable` as suggested by @Gronsak ?

**Comment by jimschubert** [comment]
@wing328 yeah I think a validatable option makes more sense.

**Comment by wing328** [comment]
Fixed via https://github.com/swagger-api/swagger-codegen/pull/5544
