### ISSUE TITLE
[TypeScript] fix class filename in import/export

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#5136]
##### Description

Currently, TS generators use {{classname}} instead of {{classFilename}} for import/export.

We've filed https://github.com/swagger-api/swagger-codegen/pull/5131 to fix the issue for TS Angular2 and we need similar fix for TS Node, Fetch, Angular, jQuery (if these templates have the same issue)

##### Swagger-codegen version

Latest master

##### Related issues

https://github.com/swagger-api/swagger-codegen/pull/5131

##### Suggest a Fix

Similar to https://github.com/swagger-api/swagger-codegen/pull/5131

**Comment by TiFu** [comment]
TS Node doesn't have this issue. It uses only 1 file (`api.mustache`) and all exports are declared using `export class {{className}}`

**Comment by wing328** [comment]
@TiFu thanks for reviewing. May I know if you've time to review other TS generators and file a fix using `classFilename` accordingly?

**Comment by TiFu** [comment]
I'll review it next week.

**Comment by TiFu** [comment]
I have looked into this today.

TS-Fetch & JQuery do not have this issue because they use only 1 file for the api & model code (api.mustache).

I have worked on a fix for Angular and noticed that [models.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular/models.mustache) also uses `classname` (as does Angular2, see [models.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-angular2/models.mustache))

May I know if this needs to be changed to `{classFilename}` too? It wasn't changed in #5131.

**Comment by wing328** [comment]
@TiFu thanks for working on this issue.

> May I know if this needs to be changed to {classFilename} too? It wasn't changed in #5131.

I would think so since that line requires the file name.
