### ISSUE TITLE
[JavaSpring] cascaded bean validation not implemented.

### ISSUE THREAD

**Issue by ebelanger** [swagger-api/swagger-codegen#5360]
##### Description

When activated, Hibernate Bean Validation only applies the first level properties.

##### Swagger-codegen version

2.2.0

##### Suggest a Fix

@Valid needs to be added on properties which contains RefProperty, Map of RefProperty and List of RefProperty.

**Comment by wing328** [comment]
@ebelanger thanks for the suggestion. May I know if you've time to contribute the enhancement? If yes, I can show you some good starting points.

**Comment by kenjones-cisco** [comment]
If we could just modify #4850 and simply make the following changes:

modules/swagger-codegen/src/main/resources/JavaSpring/beanValidation.mustache
append the following to the end of the file:
```
   @Valid
```

modules/swagger-codegen/src/main/resources/JavaSpring/model.mustache
insert after `{{#useBeanValidation}}`
```
import javax.validation.Valid;
```

I've done this previously (recently rebased) at https://github.com/kenjones-cisco/swagger-codegen/tree/features/validation

But since the existing PR has additional testing, the 2 extra lines being added to those templates should handle validation from API through Model.

**Comment by wing328** [comment]
@kenjones-cisco I've merged #4850 into master. Please submit a PR on top of the latest master so that we can review the enhancement.

**Comment by ebelanger** [comment]
@wing328 I just opened a PR with the fix.  Like I mentioned it only contains template modifications.  If you need more testing, I am open to suggestions.
