### ISSUE TITLE
[QT5CPP] missing SWGUUID when generating client based on swager.yaml containing a string with format 'uuid'

### ISSUE THREAD

**Issue by sabras75** [swagger-api/swagger-codegen#5463]
##### Description

When specifying the format of a string property, the generated C++ code includes a "SWGUUID.h" file which is not found anywhere in the generated code.

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url
a swagger file illustrating the problem can be found there :  https://gist.github.com/sabras75/e0ee03cf3c639ba835738d0358f63382

The interesting part is 
```yaml
        properties:
            id:
              type: "string"
              format: "uuid"
```

##### Command line used for generation

sorry, done through gradle swagger plugin instead of command line. Here is the section 
```
...
project('swagger-qt5cpp') {
    apply plugin: 'org.hidetake.swagger.generator'
    dependencies {
        swaggerCodegen "io.swagger:swagger-codegen-cli:2.2.2"
    }
    generateSwaggerCode {
        language = 'qt5cpp'
        inputFile = file('../src/model/rest-api/swagger.yaml')
        configFile = file('../src/model/rest-api/config-qt5cpp.json')

        dependsOn clean
    }
}
...
```

##### Steps to reproduce

Generate qt5cpp code based of the provided swagger. Then look in "SWGPet.h". This file contains 
```
#include "SWGUUID.h"
```
which is non-existent.

##### Suggest a Fix

I can see several possible fix :

- ignore the format when in the type is a string and stick to the QString type
- rely on the QUuid (http://doc.qt.io/qt-5/quuid.html) class from the QT library
- provide the missing SWGUUID.h

I can't just remove the format uuid from my API since a java client depends on it and swaqgger-code-gen generates a correct code for this platform.

**Comment by wing328** [comment]
@sabras75 thanks for reporting the issue. I think that's because `UUID` is not mapped to anything at the moment (so UUID becomes a model in codegen): https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/Qt5CPPGenerator.java#L128

If you add something similar to https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/RubyClientCodegen.java#L128 (map it as string for the time being), that should work.

May I know if you've time to contribute a fix?

**Comment by sabras75** [comment]
that's what I concluded after analysing the code :)
I hope to have some time this week to contribute a fix.
