### ISSUE TITLE
[GOLANG] Resty client uses HEAD of resty repository instead of release version

### ISSUE THREAD

**Issue by marcusljx** [swagger-api/swagger-codegen#5578]
##### Description
Generated client code imports `"github.com/go-resty/resty"`, which uses the latest master version of resty in the users GOPATH, whether or not it is stable. 

Resty provides stable release candidates through Gopkg: `"gopkg.in/go-resty/resty.v0"`

##### Swagger-codegen version
2.2.3-SNAPSHOT

##### Swagger declaration file content or url
Any swagger file

##### Command line used for generation
```
java -jar $SWAGGER_CODEGEN_ROOT/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l=go -i=api.yml -o=client -DpackageName=client
```

##### Steps to reproduce
* Run the command to generate the client package
* HTTP Client imports resty.

##### Suggest a Fix
Change the import path in the templates to use the release candidate of resty instead: `"gopkg.in/go-resty/resty.v0"` instead of `"github.com/go-resty/resty"`.

**Comment by wing328** [comment]
@marcusljx yup, I think it's definitely reasonable to use the latest stable version of the dependency.

Would you have time to file a PR so that we can review the enhancement?

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/go/api_client.mustache#L12 is a good starting point.
