### ISSUE TITLE
[HTML2]html2 api documentation consolable sections start with open curly brace '{' but do not end with close curly brace '}'

### ISSUE THREAD

**Issue by leonluocheng** [swagger-api/swagger-codegen#5779]
##### Swagger-codegen version

swagger-codegen master branch 2.3.0

##### Issue description

As you can see from the screenshot, the EventColor do not have close curly brace "}"
![image](https://cloud.githubusercontent.com/assets/8879694/26796889/b1606ad8-49f0-11e7-8ba4-1f7e2c05b5f9.png)

It is easy for us to fixed it by manually modify the html2 file. but I am looking for a better way to fix this issue since we want to add this documentation into our automation working flow

**Comment by wing328** [comment]
@leonluocheng thanks for reporting the issue. I agree that the issue should be fixed in the `html2` templates: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/htmlDocs2/index.mustache

May I know if you've time to contribute the fix by filing a PR?

**Comment by leonluocheng** [comment]
@wing328 sure, I am going to look at it to see what I can do for this issue

**Comment by leonluocheng** [comment]
@wing328  a new PR has been filled in to fix this issue. Please double check and let me know if you have any questions.  https://github.com/swagger-api/swagger-codegen/pull/5894
