### ISSUE TITLE
C# PCL version of the application

### ISSUE THREAD

**Issue by HappyTreesDev** [swagger-api/swagger-codegen#5889]
##### Description

I am developing a Xamarin application and had to make some edits to the generated code, so I decided to include the generated project in my solution and then make a reference to it. The generated code was created using the .NET standard version in hopes that it would work with my PCL based Xamarin project.

After adding the project to my solution, I had to convert the project to a PCL so that visual studio would let me make a reference to it. After converting it to a PCL that included support for Xamarin.Android, Xamarin.iOS, Xamarin.Mac, Xamarin.iOS (Classic), .NET Framework 4.5, ASP.NET Core 1.0, and Windows 8 (Which I believe is the default for xamarin projects) I found that there were issues with some File and Path methods that were used for Deserilization. I made some local changes to use the PCLStorage nuget package, but I believe it would be nice to fix this.

##### Swagger-codegen version

Master pulled from a few days ago

##### Suggest a Fix

I think to work on this I have a few ideas that I was going to look into in maybe a month's time when I have the availability.

The first would be to make a new build type that creates a PCL rather than a .NET Standard. I would think the PCL would be based on the broadest subset possible, but still not include Silverlight, as that is being discontinued.

Then I think it would be nice to choose a library for deserilization so that a file system (PCLStorage) could be used or maybe just basic JSON (Newtonsoft) could be used. I am not 100% sure how the deserilization works exactly (I didn't have time to look into it too much right now) but it would be nice for this project to support PCL more thoroughly.

**Comment by Gronsak** [comment]
Technically .NET standard should work with Xamarin without any issues. 
What version of Visual Studio are you using?

**Comment by HappyTreesDev** [comment]
I am using 2015 Professional. I was able to include the DLL compiled fine, but if I attempted to include a reference to the project itself, I was forced to switch it to a PCL. Also, there are System.IO functions that are used in the serialization stuff that are used that do not exist in Xamarin.Android or Xamarin.iOS due to file structure being so different. https://github.com/dsplaisted/PCLStorage

**Comment by Gronsak** [comment]
Okay just so we aren't missing anything obvious before moving on, could you confirm what version of Xamarin.Android and Xamarin.IOS you are running?

I'm asuming you've you installed the .NET core update for Visual Studio since you mentioned it before.

**Comment by Gronsak** [comment]
I've done some testing and would like to clarify some more things, when you say you can't reference the project it self do you mean Visual Studio refuses to add it to the solution?
Technically the VS2015 .NET Standard project file is already a PCL due to it being kind of a patchwork by Microsoft, when you say you have to switch it to a PCL do you mean you have to make a new project and copy over the code files?

**Comment by HappyTreesDev** [comment]
I had issues adding the project as a reference to my xamarin pcl. I was able to add the project to the solution.

As for switching the project to a PCL, there is an option to do so in the project properties that I used.

I think the main issue I was encountering is that the .NET Standard project does not have definition to support Xamarin stuff, and does not support the lowest common denominator that would include those projects.

Also, I feel supporting the PCL standard would just be a nice have as well, considering the PCL information more clearly states what is supported.

**Comment by Gronsak** [comment]
Does it refuse to add the reference or do you just get an error when compiling?

**Comment by Gronsak** [comment]
The reason I'm asking is because when I did my tests I had no real issues adding the references to a Xamarin project but when compiling I discovered I had to add references to the Swagger libraries two dependencies (and all their dependencies) directly to the Xamarin project. After doing that I had no issues getting it to work.
To be clear though this was in VS2017 and directly to a Android Xamarin project since I can't get my VS2015 to install Xamarin at all. From what I've understood you're referencing it from a helper library not directly from your main projects

**Comment by HappyTreesDev** [comment]
VS2015 refused to when attempting to add a reference to my PCL the IO.Swagger project. The message given was

> Unable to add a reference to project 'IO.Swagger'. The targets of Portable Library project 'IO.Swagger' are not the same or compatible with the targets of the current Portable Library project.
>
> A Portable Library project's targets can be changed via the Library tab in the project's properties.`

**Comment by Gronsak** [comment]
I assume this was before you switched the swagger library over to PCL. From what I can see it isn't really a problem between .NET Standard and Xamarin but rather a problem with compability between the two PCLs which masquerades as a .NET Standard problem thanks to how Microsoft implemented .NET Standard library support in VS2015. 

I would like to point out that most libraries that used to use PCL on other platforms (I'm not really a Xamarin guy) is either already supporting .NET Standard or is being changed to do so in the near future. PCLs are a bit of a dying standard which will be replaced with .NET Standard sooner rather than later.

**Comment by HappyTreesDev** [comment]
Okay, I have not done much research on .NET Standard and after looking up a bit, I see where you are coming from. .NET Standard sounds like the way to go. I guess there is just an issue with how VS2015 will block the reference between a PCL and .NET Standard. From my reading, what you say is correct and this should likely be kept how it is.

I do still wonder how the Path.TempPath() function was ported over to a mobile environment.
