### ISSUE TITLE
[2.3.0] Set ES6 as the default for JS generator

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#5909]
##### Description

Currently, both master and 2.3.0 are using ES5 as the default for JS generator (useES6=false)

In 2.3.0, we want to set ES6 as the default while keeping ES5 as the default in "master".

##### Swagger-codegen version

2.3.0

If anyone does *not* want to change the default in 2.3.0, please reply to let us know.

cc @frol @CodeNinjai @dinukadesilva

**Comment by frol** [comment]
> Currently, both master and 2.3.0 are using ES5 as the default for JS generator (useES6=false)

@wing328 NO, it is [ES**6** by default now (`USE_ES6=true`)](https://github.com/swagger-api/swagger-codegen/blob/69ce9213719e1b804fbfdf7189d20c257280d201/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.java#L198-L200), and this was the point of my #5888. I consider this default as a BREAKING CHANGE for JavaScript generator since using the same configuration for 2.2.x release and the master branch I get completely different outputs (it used to be ES5, and given the current master state, it generates ES6 now). I am OK with leaving `USE_ES6=true` in the 2.3.x branch, but given the promise of non-breaking releases for 2.2.x line, I would switch it to `USE_ES6=false` default in the master branch.

**Comment by wing328** [comment]
@frol I think I understand what the confusion was (because I've sync'd the change from master to 2.3.0 and the fix to restore ES5 as default will be sync'd to 2.3.0)

To make it simpler, we'll have the following:
master - default to ES5
2.3.0 - default to ES6

OK with everyone?

**Comment by frol** [comment]
> To make it simpler, we'll have the following:
> master - default to ES5
> 2.3.0 - default to ES6

OK with me.

**Comment by CodeNinjai** [comment]
Fine for me of too.

Am 23.06.2017 um 12:08 schrieb Vlad Frolov <notifications@github.com<mailto:notifications@github.com>>:


To make it simpler, we'll have the following:
master - default to ES5
2.3.0 - default to ES6

OK with me.

**Comment by wing328** [comment]
Closed via #5915
