### ISSUE TITLE
[Java-PlayFramework] Update to use Play 2.6

### ISSUE THREAD

**Issue by edrevo** [swagger-api/swagger-codegen#6096]
##### Description

Would a PR to update the Java-PlayFramework server stub generation to use Play 2.6 be a welcome addition?

**Comment by wing328** [comment]
Sounds good to me. We usually update the dependencies after a stable release (and we just released v2.2.3)

cc  @JFCote

**Comment by JFCote** [comment]
@edrevo @wing328 
The version of Play Framework must be a parameters in the generator since it will probably impact most of the mustache file.  Play Framework has a bad habit to break everything between releases, it's not just a "version" to change, it will probably impact a lot of files. 

Maybe it's not that bad and this time it will be ok, but it would be the first time.

**Comment by wing328** [comment]
@JFCote thanks for sharing more about how Play framework handles version upgrade. I would imagine it would take a lot of effort to support different Java Play version within the same generator.

If the Play framework community gets used to breaking changes between releases, shall we follow the same pattern and only support the latest stable version in the generator? (If the user needs an old version, they can use previous stable version of Swagger Codegen)

**Comment by JFCote** [comment]
@wing328 That's a possibility. 
I'm going in vacation for 2 weeks at the end of the week, but when I come back, I could check exactly what is the impact on the mustache file of this change of version. Maybe it's not that bad.

**Comment by JFCote** [comment]
@wing328 
But the more I think about it, it might make sense to just support the latest version. If it can wait, I will check that more in depth when I come back from vacation :)

**Comment by wing328** [comment]
@edrevo enjoy the vacation. Let's resume this discussion when you're back.

**Comment by laguiz** [comment]
# Note about upgrading libraries
Would also be interesting to update version of swagger-ui (eg. `"org.webjars" % "swagger-ui" % "3.0.19"`). I tried and it works properly. I just needed to change the path that should now be `?url=` instead if `/?url=` in generated `ApiDocController.java` (no slash before).

# About breaking changes
As a Play2 user I think maintaining only the last version of Play make totally sense as we probably will have a previous version of that plugin created in the past that would do the job. It also looks more realistic if we hope to have this plugin supported in the long term.

# Feedback from a quick test (Bean Validation)
Overall it looks very good! I'm only wondering how to `trigger` Bean Validation annotation. Currently testing a required query string parameter that have autogenerated `@NotNull` in method implementation. Example here https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/java-play-framework/app/controllers/PetApiControllerImp.java#L28

**Comment by JFCote** [comment]
@laguiz 

- Please create an issue asking for the upgrade (swagger-ui). I will create a PR later with the update. This needs some testing because sometimes the jars are broken or change how they work.

- Yes, the more I think about it, the more it makes sense. I don't see a mustache file with like 10 versions with strange condition everywhere over time. @wing328 , do you have any documentation on swagger-codegen about which version generate which version? For example, 2.2.3 generate play framework 2.5, 2.3 will generate 2.6. It would be interesting for future user to know which version to download for their project.

- For the bean validation, I have just realized that I never submitted my PR with the automatic validation! I will do this this morning so it should end up in the master pretty soon. Sorry about that.

**Comment by JFCote** [comment]
@laguiz : About the bean validation, here is the PR: https://github.com/swagger-api/swagger-codegen/pull/6125

**Comment by JFCote** [comment]
@laguiz : Please discard my comment about creating an issue for the swagger-ui. It will be updated in this PR: #6097

**Comment by laguiz** [comment]
@JFCote Looks very promising!

**Comment by JFCote** [comment]
@wing328 Since it was fixed and merged on Aug 22, should we close this bug?

**Comment by tzimisce012** [comment]
Yes, you can close this bug. We have been using the updated version couple months ago and it works great.
