### ISSUE TITLE
[C#] prepends the controller name to all API method names

### ISSUE THREAD

**Issue by cameronwh** [swagger-api/swagger-codegen#6164]
Hi all,

We are using swagger-codegen to create C# classes that we use when writing functional tests. In an effort to make our code as clean as possible, we are looking to change some things within a swagger-codegen template. We have our own fork of the repo, so if you know of a quick fix please say!

Say, for instance, we have a PeopleController with the method GetPerson. When we generate the C# classes, the method will come out as PeopleGetPerson(). This is a little untidy, as we usually name our variables by the api name, or their types are explicitly defined.

##### Swagger-codegen version

2.3.0

##### Steps to reproduce

Just have a C# class with an API method in it, and it will prepend the name of the controller onto any methods.

##### Suggest a fix/enhancement

I took a quick look through the code and it seems the method name is called 'operationId' within the templates. Not sure where this is generated, but if someone could point me in the right direction I can just hard code it to remove the controller name within our fork. Thanks!

**Comment by wing328** [comment]
@cameronwh can you please share a spec? Are you referring to `aspnetcore` or `nancyfx` generator?

**Comment by cameronwh** [comment]
@wing328 I am referring to the csharp generator. And sorry - what do you mean by spec?

**Comment by jimschubert** [comment]
@cameronwh by "spec", we mean the swagger.json or swagger.yaml file which you're using to generate your client code.

If your definitions in your spec are missing `operationId`, I believe we're fixing that by generating an operationId of `class + method`. I don't think this is specific to the C# generator.

As a quick-fix, you can copy the contents of the csharp generator's template directory (that is, https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/csharp), and change the `{{operationId}}` in the template to a more appropriate variable that suits your needs. You can then pass the custom template directory on the command line to swagger-codegen. See https://github.com/swagger-api/swagger-codegen/wiki/FAQ for the debug options and the `-t` switch.

I say it's a "quick-fix" because templates may change between versions. I try not to make changes between minor versions to the variables we pass to templates.

**Comment by NanoWar** [comment]
You should provide a better operationId.

If you use Swashbuckle nuget to generate your api spec, you can add an OperationFilter in your SwaggerConfig:
```c#
public class RemoveTagPrefixOperationFilter : IOperationFilter
{
    public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
    {
        string prefixToCheck = apiDescription.ActionDescriptor.ControllerDescriptor.ControllerName + "_";
        if (operation.operationId.StartsWith(prefixToCheck))
        {
            operation.operationId = operation.operationId.Remove(0, prefixToCheck.Length);
        }
    }
}
```

This will remove your controller name prefix. Note that the operationId could now be non-unique.
