### ISSUE TITLE
[JavaScript][ES6] Add additional property useES6Modules

### ISSUE THREAD

**Issue by advance512** [swagger-api/swagger-codegen#6248]
##### Description

Currently, [Node.js does not support ES6 modules](https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c).

> At the current point in time, there are still a number of specification and implementation issues that need to happen on the ES6 and Virtual Machine side of things before Node.js can even begin working up a supportable implementation of ES6 modules. Work is in progress but it is going to take some time — We’re currently looking at around a year at least

So we're talking about at least 6 months from now, as I create this issue. And that is for new Node.js versions (e.g. 9+).

This means that using the default JavaScript generator (ES6), the generated client is not usable with Node.js, unless the code is transpiled (e.g. via Babel).

As many projects (for the sake of simplicity and agility) don't transpile their code, we end up with having to choose between simple ES6 code that one can not use, or complex ES5 code that is harder to reason about.

##### Swagger-codegen version

All of them. Last check on 3.0.0 trunk a few days ago.

##### Command line used for generation

Normal generation of JavaScript client with ES6 (now the default) and promises.

##### Steps to reproduce

Generate any JS client.

##### Suggest a fix/enhancement

Add an additional property useES6Modules that is by default true, that when set to false uses CommonJS modules instead of ES6 modules. 

e.g. Instead of:

```
import superagent from "superagent";
import querystring from "querystring";
```

It'll generate code of this style:

```
const superagent = require('superagent');
const querystring = require('querystring');
```

**Comment by kenisteward** [comment]
@advance512 you can try using the typescript node one instead and tell it to compile to es5.  I'm actually going to make an issue to retire existing javascript clients in the near future as any typescript client can be templated to compile to whatever you want.

**Comment by advance512** [comment]
Why not keep it ES6, just with require()s? much easier to debug, to follow around.

**Comment by advance512** [comment]
Any comment, devs?

**Comment by joyfulelement** [comment]
Hi @kenisteward , base on your comment about retiring JavaScript client in favour of typescript client:

> retire existing javascript clients in the near future

**May I know if that is the direction where swagger-codegen is going?** i.e. the roadmap of swagger-codegen supporting JavaScript Client will be replaced by Typescript clients completely? 

Base on [Node.js's release schedule](https://github.com/nodejs/Release#release-schedule), the official support for ES6 Module is likely going to be happen in `v10.x LTS` later this year, if that is the case, in order to provide support to `Node.js v10.x LTS`, would swagger-codegen consider keeping the existing JavaScript Client with ES Module support as @advance512 had pointed out earlier?

While at a crossroads, and trying to figure out the appropriate flavour of swagger JavaScript SDK for node.js client, do you guys happen to know if the swagger typescript SDK is what most node.js developer would be looking for for SDK integration over swagger Javascript SDK (i.e, ES5, since ES6 won't work for node.js)? i.e. if there is a data showing how widely adopted for the different flavour of swagger Javascript SDK.

**Comment by kenisteward** [comment]
@wing328 suggested we leave them as is and I stand by that.

I only considered retiring the job ones because

1. Ts obviously compiles to js so we could just set a compilation target
for languages
2. It would make it so we don't have to maintain multiple libs per
framework.

**Comment by advance512** [comment]
@kenisteward 
So v3.0.0 will not have JavaScript support?

I see that there's a typescript-angular generator - but what if I don't want angular, rather, just simple node?

Is there a roadmap? What is the future of this project?

**Comment by HugoMario** [comment]
Yes, it will support it, i’m planning to add it in next two weeks. Once i’m
back from vacations :/

**Comment by tomchiverton** [comment]
So what's happening here ? What's codegen's plan for this 5 year old issue? Is the project even maintained any more ?

I was expecting to be able to "just" run a API definition through `java -jar swagger-codegen-cli-*.jar generate -i api.json -l javascript -o mesh-client --additional-properties useES6=true` and get a functioning client for modern Node/JavaScript.

It appears this isn't the case, the `index.js` has a missing 'default' keyword on the export, and all the files are named .js instead of .mjs despite using 'import'

**Comment by HugoMario** [comment]
@tomchiverton the option is been there a while ago.

Sorry for no update this ticket. This issue has been already addressed.
