### ISSUE TITLE
[Java-Playframework] Private methods on the controllers

### ISSUE THREAD

**Issue by tzimisce012** [swagger-api/swagger-codegen#6380]
##### Description

The generated controllers have private methods for the different endpoints. This does not allow to create for your controllers. An example of how these tests should be can be found here:

https://www.playframework.com/documentation/2.5.x/JavaTest#unit-testing-controllers

Even though the controllers are autogenerated, it is interesting to have the possibility of testing your application from the controllers and check all the status code possible, different kind of responses, etc. 

##### Swagger-codegen version

2.3.0

##### Suggest a fix/enhancement

Making public the methods of the controllers.

**Comment by tzimisce012** [comment]
@JFCote, take a look here! I do not know if there is a further reason to put those methods as private. Maybe you know something there.

**Comment by JFCote** [comment]
Hi @tzimisce012 ,

I don't know why you have private endpoint in your controller. As you can see in this generated sample, all the endpoint are public:

https://github.com/swagger-api/swagger-codegen/blob/master/samples/server/petstore/java-play-framework/app/controllers/PetApiController.java#L38

The only thing that is private is the constructor and that is normal since it is injected by Guice.

I don't know how it is possible to have `private` method in a controller. Can you please provide the generation command you used to have this result?

Thanks

**Comment by tzimisce012** [comment]
Hi thanks!

I just saw couple examples in play where the constructor from the controllers were public. On the other side, [KeepConstructorsHidden
](https://github.com/google/guice/wiki/KeepConstructorsHidden
) suggest the opposite. 

I guess guice suggestion overrides playframework examples :)
