### ISSUE TITLE
When is 'modelPropertyNaming' config option necessary?

### ISSUE THREAD

**Issue by will-beta** [swagger-api/swagger-codegen#6632]
I have some APIs coded with c#, conforming to PascalCase naming conversion for the property of classes (also in the swagger document).
After I generated a Typescript-Node client library with [swagger-online-editor](https://swagger.io/swagger-editor/) , to my surprise I found that the generated properties of classes are camelCase.
So after some researching, I found the 'modelPropertyNaming' config option, which can be set as camelCase | PascalCase | Original.
My question is: In what kind of scenarios, is 'modelPropertyNaming' config option necessary?

Thanks in advance !

**Comment by wing328** [comment]
@will-beta Some generators (e.g. JavaScript) do not have a proper way to map between JSON key names and object property names (JSON serialization/deserialization) and therefore we introduced the 'modelPropertyNaming" option to let the users specify the naming convention instead of following the style guide of the respective language.

If I remember correctly, the community has added proper JSON serialization/deserialization to TS-node so please give it a try and let us know if you find any issue.
