### ISSUE TITLE
[Java-Jersey] Swagger Codegen + Jersey 2.26: LoggingFilter -> LoggingFeature

### ISSUE THREAD

**Issue by wienczny** [swagger-api/swagger-codegen#6715]
The latest release of Jersey (2.26) removed org.glassfish.jersey.filter.LoggingFilter which had been deprecated since 2.23. The generated code should be migrated to use org.glassfish.jersey.logging.LoggingFeature

**Comment by raner** [comment]
If someone were to make a pull request that addresses this issue, how long would it take to have the fix in an official release? Is there a planned release date for swagger codegen 2.2.4, or are the release done in more of an ad hoc fashion?

**Comment by SergeyLyakhov** [comment]
@wing328 
This issue has already been fixed and merged into master in 
SHA-1: 2d19776caf4c06cf98627b5a2a228af9a82346b7  * Merge branch 'mobreza-jersey-logging-deprecated'
However this change breaks jersey2 + java6, because jersey v.2.6 doesn't support LoggingFeature.
I prepared a fix for this case and will create PR if needed.

**Comment by wing328** [comment]
> I prepared a fix for this case and will create PR if needed.

@wienczny Please kindly a file a PR to fix it. I'll see if I can setup CI for Java6.
