### ISSUE TITLE
[TypeScript-Angular2] Swagger Codegen Get Methods not Including Parameters

### ISSUE THREAD

**Issue by gabrielfuller** [swagger-api/swagger-codegen#6723]
##### Description

I am using Codegen Java file to create the Typescript-Angular 2 API for my C# web api.  The code gen tool creates the correct code for post and put, but get and delete do not include the parameters correctly.

Here is the generated put method:
```
public organizationsUpdatePut(command?: UpdateOrganizationCommand): Observable<UpdateOrganizationCommandResult> {

        let headers = this.defaultHeaders;

        return this.httpClient.put<any>(`${this.basePath}/Organizations/Update`, command, {
            headers: headers,
            withCredentials: this.configuration.withCredentials,
        });
    }
```
Here is the read method:
```
public organizationsReadGet(command?: ReadOrganizationCommand): Observable<ReadOrganizationCommandResult> {

        let headers = this.defaultHeaders;

        return this.httpClient.get<any>(`${this.basePath}/Organizations/Read`, {
            headers: headers,
            withCredentials: this.configuration.withCredentials,
        });
    }
```

As you can see, in the read method, the command parameter is never added to the HttpClient Get method so my call to the API always fails.  Any ideas how to fix it?  Am I doing something wrong?

##### Swagger-codegen version
3.0.0-20171009.075709-6

##### Command line used for generation
java -jar C:\SimOpSolutions\SOSBrowserClientApp\files\swagger-codegen-cli-3.0.0-20171009.075709-6.jar generate -i http://localhost:5000/swagger/v1/swagger.json -l typescript-angular -o C:\SimOpSolutions\SOSBrowserClientApp\sos-app\src\app\sos-api
pause

**Comment by macjohnny** [comment]
@gabrielfuller can you post the relevant parts of your swagger.json?

**Comment by wing328** [comment]
>3.0.0-20171009.075709-6

3.0.0 is still being worked on to support OAS (OpenAPI spec) 3.0

I would suggest you to use the 2.3.0 SNAPSHOT version for the time being.

**Comment by defmonk0** [comment]
While this is still open, I also want to mention that `httpClient.delete` is not always properly configured either. When generating a delete call that takes body data, it adds it as a parameter to `httpClient.delete`, but the signature of that function only accepts url and options. 

You can reproduce by generating typescript-angular from [this spec](https://esi.tech.ccp.is/latest/swagger.json?datasource=tranquility). In the contacts.service.ts file, there is a function `deleteCharactersCharacterIdContacts`. The return statement there calls `this.httpClient.delete<any>(url, contactIds, options)`, when it can only take 2 parameters.

**Comment by defmonk0** [comment]
@macjohnny So, just got around to testing that particular branch. It technically fixes the bug, allowing the error to go away. That said, it does so by simply not passing the body data at all, even if there is some.

For example, the same delete function as before has this signature:

```typescript
public deleteCharactersCharacterIdContacts(characterId: number, contactIds: Array<number>, datasource?: string, token?: string, userAgent?: string, xUserAgent?: string): Observable<{}> {}
```

The `contactIds` there are meant to be sent via the request body when it does delete. The return statement now properly has `this.httpClient.delete<any>(url, options)`, which is valid, but in no way does it pass the `contactIds`.

Since this bug is a side affect of that branch, I assume it's not best to open a general issue for it. Should I comment and explain the situation in the PR thread?

**Comment by macjohnny** [comment]
@defmonk0 please state your issue in the PR #6754
however, looking at the API docs https://angular.io/api/common/http/HttpClient , the delete method does not take any body argument:
```
delete(url: string, options: {...}): Observable<any>
```
so how is your parameter supposed to be transmitted?

**Comment by defmonk0** [comment]
[This is the API I've been using](https://twitter.com/julieeeaustinnn/status/920721266864197632), if you wanna take a look. Inside contacts->delete, it takes a list of contact IDs in the body of the call. I was aware of HttpClient not supporting body data on their delete calls, so I'm unsure how we'd best go about doing it. Technically, if you we use the request method instead of delete, we can do a delete while we pass body data.

I'll post over in the PR, so we can get more eyes on it.

**Comment by gabrielfuller** [comment]
I used the latest 2.3.0 SNAPSHOT and it fixed my issue.

**Comment by a-ludi** [comment]
I'm using 2.3.0 SNAPSHOT and have the same issue, that the "parameter" are not generated at all.

**Comment by gabrielfuller** [comment]
Something I discovered is that I realized I needed to do was make sure that
the Routes in my API (in my case, C# Web Api) had the correct parameters
defined in the route.  Once I added the parameters into the route string
like below, they started appearing when I generate the API.

I went from this:
[HttpGet("GetUser")]
public object GetUser(string userId)

to this:
[HttpGet("GetUser/{userId}")]
public object GetUser(string userId)

That fixed that issue for me.
