### ISSUE TITLE
[NancyFx] Support Async

### ISSUE THREAD

**Issue by craffael** [swagger-api/swagger-codegen#6734]
##### Description

Currently the NancyFx codegen generates synchronous endpoints. I suggest to add a new nancyfx specific `--additional-property async=true` that can be used to generate async endpoints.

##### Swagger-codegen version

2.3.0-SNAPSHOT

##### Suggest a fix/enhancement

if `async=true` I suggest to do the following modifications:

- add `async` keyword to every route and set second parameter in the square brackets to `true` to mark it as an asynchronous route.
- Make interface methods of Services and the abstract methods in in the abstract service(s) return Tasks + add `async` keyword where necessary.
- add the corresponding `using` statements.

See e.g. [this blogpost](http://blog.jonathanchannon.com/2013/08/24/async-route-handling-with-nancy/) for more details.

@mandrean @jimschubert What do you think?

**Comment by wing328** [comment]
@craffael thanks for the suggestion.

It's worth sharing with you that most API clients (e.g C#, Java, Ruby, Python, etc) come with both sync (e.g. [AddPet](https://github.com/swagger-api/swagger-codegen/blob/c66a0aaa07695276fc3fa6a24bb42d2176d0f5cc/samples/client/petstore/csharp/SwaggerClientNetCoreProject/src/IO.Swagger/Api/PetApi.cs#L36)) and async (e.g. [AddPetAsync](https://github.com/swagger-api/swagger-codegen/blob/c66a0aaa07695276fc3fa6a24bb42d2176d0f5cc/samples/client/petstore/csharp/SwaggerClientNetCoreProject/src/IO.Swagger/Api/PetApi.cs#L216)) methods

For the server generator, I thought the controller classes are just the HTTP handler, which means it must complete its operation (e.g. save a record to database, start a background job to generate reports, etc) in order to return a HTTP response (but I've to say I'm not familiar with the NancyFx generator)

**Comment by craffael** [comment]
@wing328 
1) Do these API clients have a common `optional-property` to use async terminology? If so I could reuse that property instead...

2) The first time that I heard about server side async terminology I was also a bit puzzled. But if you think about it longer it actually makes sense (especially in micro-service architectures): Server code also has to make IO bound operations to 3rd party services such as databases or other micro-services. By using async techniques you can avoid having to use an individual thread on the server for every request. Instead NancyFX can in principle work with one thread per cpu core but still handle possibly thousands of concurrent http requests. In comparison to one-thread-per-request, the one-thread-per-cpu approach can offer superior throughput (see e.g. [this blog entry](http://phillbarber.blogspot.ch/2016/01/choosing-between-ratpack-and-dropwizard.html))
In our case there is also another argument involved: Our Webserver will rely on some other code that was developed async/await (because it is used by UI code as well) and therefore it would be convenient to reuse that functionality. (Turning a non-blocking call into a blocking call is unfortuantely not so easy in C# :( )

**Comment by wing328** [comment]
> Do these API clients have a common optional-property to use async terminology? If so I could reuse that property instead...

Nope, we generate both async and sync methods in the same SDK.

I'll research into this a bit more before I comment further.

**Comment by craffael** [comment]
Thanks for looking into that! Of course it would be super nice to not have a switch. At the price of complicating the code quite a bit, this would be achievable (convert synchronous routes into asynchronous ones at runtime). However one problem would be that the code would not run anymore with .net framework <= 4.0 (see last paragraph of [this documentation](https://github.com/NancyFx/Nancy/wiki/Async) ). I'm therefore more in favor of introducing an additional swagger-codegen `optional-property`

**Comment by jimschubert** [comment]
I haven't used NancyFx for any real development, but it wouldn't make much sense to have both a sync and async implementations generated at the same time for the same endpoint from an API perspective.  It makes sense from client code because it's using an HTTP client that exposes both synchronous and asynchronous call methods, and we're basically just forwarding the sync/async signatures to the caller.  From the server generated code's perspective, it doesn't change the endpoint whether it's sync or async… it just changes how the framework handles request threads.

The implementation for this would start with changing api.mustache in nancyfx to this (or something similar):

```
{{httpMethod}}["{{{path}}}"{{#async}}, runAsync: true{{/async}}] = {{#async}}async {{/async}}(parameters{{#async}}, token{{/async}}) =>
```

Then you can add `async=true` to `bin/nancyfx-petstore-server.sh` and generate without rebuilding the project each time you make a template change.

From here, though, we'd need to decide how to proceed. The current implementation defines synchronous interfaces, so it wouldn't just make regenerated endpoints asynchronous. We could wrap service calls in an awaitable but then the cancellation token wouldn't get propagated down the stack. If we were to add the additional async methods as we have in the clients (both sync and async in the same interface), this would force all existing services to implement an async version of the synchronous service if they want to move to async endpoints. This would be frustrating from a user's perspective, so we couldn't really default to `async=true`. Personally, I'd want either/or in my services.

If we were to say "this server's code is either synchronous or asynchronous" on original generation, that would be preferable and is really the only solution I see. We'd then implement the interface with the async signature when the option is set (or current outputs when not set). We could even call it a breaking change and default to `async=true` because it should be obvious to users who are regenerating services from specs that the methods have become asynchronous and the breaking change could clarify that existing users regenerating just pass `async=false` to have zero impact.

@craffael would you like to take a stab at this?

I think implementing the async interface only when `async=true` like the example above above would be the ideal path forward. Keeping the default `async=false`, and ignoring that wiki paragraph about .NET 4.0 issues… you could get this in with just mustache template changes. It wouldn't be difficult to add the 4.5+ constraint, but I don't really know that it's necessary.

**Comment by craffael** [comment]
@jimschubert Thanks a lot for your comprehensive proposal. I fully agree with your arguments and have created a corresponding PR #6755 . Let me know what you think of it...

**Comment by wing328** [comment]
PR merged into master. Thanks for the contribution by @craffael
