### ISSUE TITLE
[CSharp] Issue Generating client when nonPublicApi = false

### ISSUE THREAD

**Issue by lunat** [swagger-api/swagger-codegen#6784]
Hi,

Csharp client generator creates all classes and methods as "internal" even if "nonPublicApi":"false".

I am using swagger-codgen version 2.3.0

Thanks,

lunat

**Comment by jimschubert** [comment]
@lunat how are you declaring `nonPublicApi`? This is an additional-property option.

**Comment by lunat** [comment]
I also tried with https://generator.swagger.io.
Setting both
```
"options":{  
      "nonPublicApi":false
}
```
or 
```
"options":{  
      "nonPublicApi":true
}
```
I get internal classes.
Note that if I exclude "nonPublicApi" setting from options, all classes are public.

**Comment by jimschubert** [comment]
Verified with

```
{
  "options": {
    "packageVersion": "1.0.1",
    "nonPublicApi": false
  },
  "swaggerUrl": "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore-expanded.json"
}
```

And classes are always internal.

However, I don't think this is C# specific. I've been working on another branch, and the true/false variables which previously processed correctly in Mustache are no longer being treated as true/false. This seems to be causing "false" to be treated as truthy.

I'd have to dig into this a bit to understand what changed, and when it changed. You can see that the visibility modifier in C# hasn't changed since I added it in January: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/visibility.mustache, so the expectation would be that this code works the same in 2.2.3 as it did in 2.2.2.

**Comment by jimschubert** [comment]
@lunat I opened #6899 to address this issue. However, regenerating all C# code produced a few issues that I'll need to follow up on:

* .NET 4.0 code doesn't compile with the `build.sh` script, complaining that RestSharp needs nuget 2.12 instead of the downloaded 2.8 (even though I have 2.12 installed globally).
* SwaggerClientWithPropertyChanged sample doesn't seem to compile or copy files into artifacts folders on build.
* SwaggerClientNetStandard sample doesn't build with msbuild locally (may be a config issue on my machine), and there are no build scripts included in the generated output.

I'll wait and see how CI handles things, and follow up on the above points later in the week.
