### ISSUE TITLE
[Swift 4] Cannot convert value of type 'RequestBuilder<_>.Type' to specified type 'RequestBuilder<MyGeneratedModel>.Type'

### ISSUE THREAD

**Issue by dsk1306** [swagger-api/swagger-codegen#7041]
##### Description

I've got a new project where all REST code is generated by swagger-codegen, which I've never used before. Everything seems to work fine except requestBuilder initialisation error

##### Swagger-codegen version

editor.swagger.io (2.2.3)

##### Steps to reproduce

Uploaded my .yaml file at editor.swagger.io.
Added files from .zip to my xCode project.
Got error

```
Cannot convert value of type 'RequestBuilder<_>.Type' to specified type 'RequestBuilder< TimeoutForNextRequestInSeconds >.Type'
```

at

```
let requestBuilder: RequestBuilder<TimeoutForNextRequestInSeconds>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()
```

requestBuilderFactory:

```
open static var requestBuilderFactory: RequestBuilderFactory = AlamofireRequestBuilderFactory()
```

AlamofireRequestBuilderFactory:

```
class AlamofireRequestBuilderFactory: RequestBuilderFactory {
func getNonDecodableBuilder<T>() -> RequestBuilder<T>.Type {
    return AlamofireRequestBuilder<T>.self
}
func getBuilder<T:Decodable>() -> RequestBuilder<T>.Type {
    return AlamofireDecodableRequestBuilder<T>.self
}
```

RequestBuilderFactory:

```
public protocol RequestBuilderFactory {
    func getNonDecodableBuilder<T>() -> RequestBuilder<T>.Type
    func getBuilder<T:Decodable>() -> RequestBuilder<T>.Type
}
```

##### Related issues/PRs

None found

**Comment by wing328** [comment]
@dsk1306 please try the latest master as there's been many enhancements, bug fixes to the Swift4 generator.

SNAPSHOT version of the latest master (2.3.0) can be found in the README.

**Comment by dsk1306** [comment]
I've tried SNAPSHOT version of the latest master and it works perfectly. Thanks for help.

**Comment by axello** [comment]
Currently running 2.4.0-SNAPSHOT according to the pom.xml file, but the problem either re-appeared or still exists. I get exactly the same error message. 
I generated code on editor.swagger.io, and installed a Docker container with the whole Maven shebang: both versions are for some reason not referencing the RequestBuilder correctly.

Error message:
```
cannot convert value of type 'RequestBuilder<_>.Type' to specified type 'RequestBuilder<Any>.Type'
        let requestBuilder: RequestBuilder<Any>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()
```

**Comment by dcchristopher** [comment]
@wing328 Can you please reopen this bug or do we need to create a new one? I'm having the same problem in 2.3.1 (installed via brew on OSX). I spent a lot of time and effort to regenerate and update a Swagger client and this is keeping me from putting the code on a path to production.

**Comment by axello** [comment]
Well, I have researched the issue some more, with the help of an API developer. 

It seems that, even with swagger specs that are working fine for e.g. C# deployments, the swift4 generated code gives compile errors.
Even with the Swagger editor showing zero warnings.

I guess something is wrong in the swift4 generation where the code generated is not checked for type-safety enough. Maybe the code generation should throw an error or a warning?

But I am not a java programmer.

**Comment by dcchristopher** [comment]
@axello, thank you for your input! To me it looks like nothing more than a compile time SNAFU due to lack of type inference (allegedly, "_" is the default generic type when there's not enough for Swift to go on; the compiler doesn't like that we're trying to return <Any> instead of <_>). Overall the code looks good but it just may need some additional "explicitness" to make the compiler happy. I am well versed in C# generics. I just need to figure out what the right amount of elegantly-crafted code is going to help the generator produce a proper build. Then I'll look into submitting that code with a PR. I'm sure that for someone who knows Swift well, this is child's play.

**Comment by dcchristopher** [comment]
Well, shucks. For anyone else who may come up against this problem, there are two avenues:
a) correct your API so that every endpoint returns _something_ (i.e., no RPC-style void return types); regenerating the Swagger proxy classes will eliminate the errors
b) manually update those generated methods that are causing the error (not all of them will since most should return a proper object) and change .getBuilder() to .getNonDecodableBuilder(); I haven't yet tested those but it at least produces a build you can validate.

If any change to codegen is to be made, it would be to either fail the generation if any of the endpoints return void or switch to .getNonDecodableBuilder() if the return type is void (pending validation that this wouldn't cause any other downstream artifacts).

**Comment by axello** [comment]
Thanks for the explanation @dcchristopher . I've looked through the generated code, but had a hard time making heads or tails of it. 
That is fixed now. 
However, an other thing cropped up, which is easy to fix in the final generated code, but is an annoyance nonetheless, as I would like it to be generated automatically. 

The following part of the JSON schema:
```
  Well.Presentation.Models.Wealth.AccountSelectionRequest:
    required:
      - container
    type: object
    properties:
      container:
        type: array
        items:
          $ref: '#/definitions/Well.Presentation.Models.Wealth.AccountSelectionItem'
```

Generates the following piece of swift4 code (superfluous linefeeds removed for brevity):
```
open class WellPresentationModelsWealthAccountSelectionRequest: Codable {
    public var container: [WellPresentationModelsWealthAccountSelectionItem]
    
    public init(container: [WellPresentationModelsWealthAccountSelectionItem]) {
        self.container = container
    }

    // Encodable protocol methods
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: String.self)

        try container.encode(container, forKey: "container")
    }
```

Now, the problem is that all the encode/decode functions use a local variable 'container', which is fine. Normally. Unless there is a *property* called container as well. Then suddenly you either need to rename the local instance to something else which does not conflict, or use 'self' in front of the instance variant.

Perhaps the latter is a more consistent option. Should I file a bug? 
I would love to create a pull request, but then I have to become a java ninja first.

**Comment by dcchristopher** [comment]
@axello Are you a template ninja, per chance? :) swagger-codegen appears to use [mustache](https://mustache.github.io)

Check out the [object template](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/swift4/modelObject.mustache). Clone the master branch into your github account and "git" locally. Notice line 55 (as of the currently latest version). Just prepend "{{{name}}}" with "self.". Build swagger-codegen locally, then regenerate your API (the one containing an endpoint with an object containing a property named "container"). That ought to produce a compilation-error-free API client. Then commit/push your changes and submit a PR with your github branch.

I'm rooting for you ... :D
