### ISSUE TITLE
[C#] Generating models whose names start with "{operationId}" in the specification

### ISSUE THREAD

**Issue by david-rougier** [swagger-api/swagger-codegen#7252]
I want to generate C# models from an OpenAPI 2.0 specification.
The names of the data types start with "{operationId}" in the specification.
Can the models be generated without the operationId in their names ?
If so, how ?

**Comment by jimschubert** [comment]
I don't understand how this is related to the C# generator. It sounds more like a general question about swagger codegen or swagger specification. I'll provide my concerns about such a feature as a contributor to the C# generator, since it's tagged with C#.

Currently, Swagger Codegen (as far as I know, see below \*) only supports adding a prefix and suffix to model names. This is a simpler thing to do than to remove an operationId from models because such support would mean we would then have to address conflicts.  This is is because `operationId` is required to be unique for the entire specification document, and the reason to prefix a model name with `operationId` is to guarantee unique models per operation.

As an example, suppose your data types are defined such as `postPeoplePerson` (for operationId = postPeople) and `putPeoplePerson` (for operationId = putPeople), and you want to remove the operation id from each model. You would end up with two instances of `Person` where the POST operation, if following good REST practices, wouldn't have an id property while the PUT model most likely has an id property. How would these get merged? Is there a response type of `Person` already? What logic would you follow when a property to be merged is `int32` in once place and `int64` in another place?

Also, there are pragmatic reasons for REST APIs to include additional properties only during creation of a resource and never again expose those properties on the domain model.

Rather than add (or fix) support for such a feature, I would suggest reaching out to the author of the specification you're consuming and trying to work toward a more consistent model to simplify client usage. If you own the specification, and you're generating it through Swashbuckle, create a document filter to remove the `operationId` from your models.

##  \* NOTE

There is a codegen property for `removeOperationIdPrefix`. This _may_ have previously been used to do what you're asking. However, it now sets a flag to sort parameters, which is unrelated:

https://github.com/swagger-api/swagger-codegen/blob/8e551a76b4ef2ec7ee1482829edbf6f1cc864f87/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L154

```
        if (additionalProperties.containsKey(CodegenConstants.REMOVE_OPERATION_ID_PREFIX)) {
            this.setSortParamsByRequiredFlag(Boolean.valueOf(additionalProperties
                    .get(CodegenConstants.REMOVE_OPERATION_ID_PREFIX).toString()));
        }
```

**Comment by david-rougier** [comment]
I thank you for your detailed comment.
You have given me the explanations I needed so I close this issue.

**Comment by jimschubert** [comment]
@david-rougier sounds good!

@wing328 can you see my note above about `removeOperationIdPrefix`? Is this a big or possible merge conflict somewhere?

**Comment by wing328** [comment]
> @wing328 can you see my note above about removeOperationIdPrefix? Is this a big or possible merge conflict somewhere?

Let me try to fix it later today.

**Comment by wing328** [comment]
Filed https://github.com/swagger-api/swagger-codegen/pull/7301 to fix the issue. Thanks @jimschubert again for spotting the issue.

**Comment by jimschubert** [comment]
@david-rougier please generate against #7301 with the 
`removeOperationIdPrefix` option. If it works for you, that's ideal. If not, my comments about the complexity of the use case and recommendations for spec follow up are still relevant.

**Comment by david-rougier** [comment]
@jimschubert What is the Maven URL of the version containing the fix ?

**Comment by jimschubert** [comment]
@david-rougier it's not released yet. You'd have to pull the branch and build it. Let me know if you're unable to do that, and I can build the jar locally and get it to you.

**Comment by david-rougier** [comment]
@jimschubert I do not know how to build the jar.
Can you please do it and give me the jar ?

**Comment by jimschubert** [comment]
Sure. I've built the jar from that PR, and included an MD5 sum to verify. It's available at this gist: https://gist.github.com/jimschubert/edd53ded5cd826e5a924fffb0b5c5aa9. Sorry I didn't know of a better way to build and share the jar. If you need a stronger checksum verification, let me know. I've only had this new machine for a few weeks, and the newer OS X apparently doesn't include sha1sum/sha256sum.

That PR targets the master branch, so it may include some other breaking changes.

**Comment by david-rougier** [comment]
@jimschubert I thank you for building and sharing the jar.
I have generated the models with the jar and the `remove-operation-id-prefix` option.
The names of the models unfortunately start with the operationId.
I thank you for your help and your explanations anyway.

**Comment by iamsubhishek** [comment]
Hello @jimschubert ,
                 How can i use remove-operation-id-prefix option. I am not able to use.
