### ISSUE TITLE
[C#] Error	CS0506 'Account.ToJson()': cannot override inherited member 'BaseAccount.ToJson()' because it is not marked virtual, abstract, or override

### ISSUE THREAD

**Issue by Jericho** [swagger-api/swagger-codegen#7358]
I used SwaggerHub to define my API and used their built-in feature to generate a C# client. My understanding is that Swaggerhub uses the templates defined in this github repo, that's why I'm opening an issue here but let me know if I'm mistaken.

The issue I'm facing is when the generated code results in a model class deriving from a base model class (in my case, they are called `BaseAccount` and `Account`). In this scenario, both classes end up with a `ToJson()` method which Visual Studio flags as invalid with the following error:

> Error CS0506 'Account.ToJson()': cannot override inherited member 'BaseAccount.ToJson()' because it is not marked virtual, abstract, or override

I can fix this problem manually by adding the `virtual` flag to the method in the base class but my model has more than 25 base classes which means that this manual process would be very tedious, especially since I would need to apply the same modifications every time I regenerate the csharp code. 

Here's a simplified version of my API definition to reproduce the problem:

```yaml
swagger: '2.0'
info:
  title: Simplified API for error repro
  version: "1.0.0"
paths:
  /account:
    parameters:
      - $ref: '#/parameters/account_id'
    get:
      consumes: []
      tags:
        - myapi
      operationId: getAccount
      summary: Returns account informations
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Account'
parameters:
  account_id:
    name: account_id
    description: 'ID of the account on which to operate.  If omitted, the authenticated profile main account will be used.'
    in: query
    type: string
    format: uuid
    required: false
definitions:
  BaseAccount:
    type: object
    properties:
      name:
        type: string
      locale:
        type: string
      timeZone:
        title: time-zone used for this account.  UTC will be used if not specified.
        type: string
    required:
      - locale
  Account:
    allOf:
      - $ref: '#/definitions/BaseAccount'
      - type: object
        properties:
          id:
            type: string
            format: uuid
            readOnly: true
produces:
  - application/json
consumes:
  - application/json
```

And here's what the `ToJson` methods look like in the two generated classes:

```csharp
public partial class BaseAccount : IEquatable<BaseAccount>, IValidatableObject
{
    public string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}

public partial class Account : BaseAccount, IEquatable<Account>, IValidatableObject
{
    public override string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}
```

**Comment by jimschubert** [comment]
Thanks for reporting this.

I've looked into this, and I'll have a pretty simple fix but I wanted to explain the fix here in case others have a similar issue.

Open API 2.0 specification defines functionality for both composition and polymorphism. Your specification is defined in the composition form, and the C# templates at some point were limited on this generated method to only support polymorphism.

That is, the generator prior to current master expects any classes with a base class to be defined as polymorphic. The following would generate valid code:

```
definitions:
  BaseAccount:
    type: object
    discriminator: classType
    properties:
      classType:
        type: string
      name:
        type: string
      locale:
        type: string
      timeZone:
        title: time-zone used for this account.  UTC will be used if not specified.
        type: string
    required:
      - classType
      - locale
  Account:
    allOf:
      - $ref: '#/definitions/BaseAccount'
      - type: object
        properties:
          id:
            type: string
            format: uuid
            readOnly: true
```

Using a discriminator in this way is a pretty standard way to differentiate between types for persistence (like if your RDBMS structures are designed as TPH). This constraint is very limiting.

The fix is simply to remove the requirement that `discriminator` exists. However, the template appeared to have contradictory checks on parent and discriminator in the first place.

I've opened #7399 to resolve the issue.
