### ISSUE TITLE
[Scala] Invalid generated type for type=string, format=byte

### ISSUE THREAD

**Issue by gmarz** [swagger-api/swagger-codegen#7371]
##### Description

The below spec (which is valid) results `Option[ArrayByte]` in the generated Scala client, which is an invalid type. It should be `Option[String]` instead.

##### Swagger-codegen version

master (2.3.1-SNAPSHOT)

##### Swagger declaration file content or url
```json
"schema": {
  "type": "string",
  "format": "byte"
}
```

##### Related issues/PRs

#7286

**Comment by jimschubert** [comment]
This should get generated `Option[Array[Byte]]`, and instances would need to be modified to call `.getBytes` on the string.

I'm on mobile right now, but I believe a workaround for going back to strings is to pass the command line option:

```
--type-mappings ByteArray=String
```

I'm guessing the template has `{{{dataType}}}` rather than `{{dataType}}` here. If mustache is removing brackets, we may need to create a filter to prevent removing square brackets on generics.

**Comment by gmarz** [comment]
> If mustache is removing brackets, we may need to create a filter to prevent removing square brackets on generics.

This may be the case...I tried:

```
--type-mappings ByteArray=Option[String]
```

and this generated `OptionString`, so indeed looks like mustache is dropping brackets.

**Comment by jimschubert** [comment]
@gmarz I didn't see your last comment, and I opened #7378 with a fix. I just realized that I didn't say I'd take this up tonight, so I hope I didn't step on your toes with a fix.

**Comment by gmarz** [comment]
@jimschubert not at all, thanks for the quick fix!

**Comment by jimschubert** [comment]
No problem. it'll probably be about a week before I have a chance to evaluate against our client generation. let me know if you try the snapshot and still have issues.
