### ISSUE TITLE
[typescript-angular2] Datetime parameters are not correctly formatted in request path

### ISSUE THREAD

**Issue by arjuin** [swagger-api/swagger-codegen#7476]
##### Description

I'm using codegen with an angular4 project.
I made an api endpoint with a datetime in the path like /line/{line:int}/exploitation/{xpdate:datetime}/incident
          

>               {  
>                   "name":"xpdate",
>                   "in":"path",
>                   "required":true,
>                   "type":"string",
>                   "format":"date-time"
>                },

The code generated for the previous snippet a datetime parameter is: 
`encodeURIComponent(String(xpdate))`
Result is like 'Sat%20Dec%2024%202016%2001%3A00%3A00%20GMT%2B0100%20(Paris%2C%20Madrid)'
and the request fails !

I noticed datetime parameter is right generated for a query parameters: 

>                {  
>                   "name":"StartDate",
>                   "in":"query",
>                   "required":true,
>                   "type":"string",
>                   "format":"date-time"
>                },

Generated code for query parameter is like: 
if (startDate !== undefined) {
            queryParameters = queryParameters.set('StartDate', <any>startDate.toISOString());
        }

##### Swagger-codegen version

2.3.1

##### Suggest a fix/enhancement

Generate specific method call for datatypes instead of generic toString() method.

**Comment by macjohnny** [comment]
@arjuin the path is being compiled here:
https://github.com/swagger-api/swagger-codegen/blob/v2.3.1/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java#L260-L294

**Comment by macjohnny** [comment]
I had a quick look at it and it seems it is not that simple, since in the line I suggested to be changed
(https://github.com/swagger-api/swagger-codegen/blob/v2.3.1/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java#L279) we don't know about the parameter properties.
We might be better off by moving the compilation of the path from https://github.com/swagger-api/swagger-codegen/blob/v2.3.1/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/TypeScriptAngularClientCodegen.java#L260-L294
to the mustache template https://github.com/swagger-api/swagger-codegen/blob/v2.3.1/modules/swagger-codegen/src/main/resources/typescript-angular/api.service.mustache#L294

@bedag-moo @defmonk0 what is your suggestion?

**Comment by bedag-moo** [comment]
If the runtime type of the value is sufficient information, we could generate a method like

    encodePathParam(value) {
       if (value instanceof ...) {
         // conversion logic
       } else {
         // other conversion logic
      }
      return encodeURIComponent(converted);
    }

and generate template expressions like `some/path/${encodePathComponent(paramName)}` for all params. This assumes the client type is sufficient to choose the appropriate encoding.

If however we need swagger property metadata to choose the appropriate conversion, I'd keep generate the conversion logic in Java, since conditionals in mustache templates are quite restricted and hard to read.

(I didn't look deeply enough into the date representations supported by swagger to figure out whether property metadata is needed.)

**Comment by macjohnny** [comment]
I filed a PR https://github.com/swagger-api/swagger-codegen/pull/7479 which should resolve the issue with little modifications. moreover, it should also fix https://github.com/swagger-api/swagger-codegen/issues/7302

**Comment by arjuin** [comment]
It resolves the issue. Thanks

**Comment by macjohnny** [comment]
@arjuin please reopen this issue until https://github.com/swagger-api/swagger-codegen/pull/7479 is merged into master.
Also, would you mind posting your successful test of the Code in https://github.com/swagger-api/swagger-codegen/pull/7479 ?
