### ISSUE TITLE
Confusion around Swagger 3 release

### ISSUE THREAD

**Issue by bschlenk** [swagger-api/swagger-codegen#7917]
The [Swagger blog](https://swagger.io/blog/announcing-openapi-3-0/) claims that Swagger 3.0 has been officially released, yet [this very repo](https://github.com/swagger-api/swagger-codegen#compatibility) states that Swagger 3.0.0 release is still TBD. So, which is it? Has Swagger 3.0 really been officially released, or is it still a work in progress? Are there different parts of swagger that release at different cadences? I am very confused about all this.

**Comment by macjohnny** [comment]
@bschlenk the `OpenAPI 3.0` specification has been released, while `Swagger Codegen 3.0.0` supporting `OpenAPI 3.0` has not yet been released

**Comment by bschlenk** [comment]
Is a yaml configuration written in the Swagger 3.0 specification useable in any form then? What are the benefits of upgrading a configuration to 3.0 if the underlying libraries do not yet support it?

**Comment by mpnordland** [comment]
@bschlenk I just spent several hours determining that usability is very limited. The editor supports it, the 3.0.0 branch will parse it, but only has html and java codegen's available. copying in 2.4's codegens makes more languages available, but at least Python's client generation fails while creating models. there is a separate codegen (https://github.com/Mermade/openapi-codegen) written in node that also parses OpenAPI3, and it is easier to get working. It's in a very early state so for my case doesn't generate working code. YMMV depending on what language and environment you're using.

**Comment by webron** [comment]
@bschlenk To summarize - the blog post doesn't say that Swagger 3.0 is out, but rather the OpenAPI Specification 3.0 (OAS3) is out. "Swagger" is not a single tool, but a set of tools around the OpenAPI Specification. 

Some of our tools support OAS3 more than others, with continuous work to improve the support. The codegen is almost the last project in line since it depends on a set of other projects that needed to be upgraded before hand. 

The benefits on upgrading to OAS3 depend on what you want to achieve. Our tools are not the only ones out there, and some may provide you more benefits than others. The advantage of using OAS3 is that it allows specifying more APIs, and in some cases the same current APIs but more accurately. If, for example, all you care about is documentation, then OAS3 can already provide you extra value.

The work on swagger-codegen 3.0.0 which supports OAS3 is in progress and heavily depends on community contributions to help us migrate the generators for other languages. We're also considering some options to help improve the process and make the migration easier.

And to answer the title itself - there will never be a "Swagger 3.0" release - as said, there's no single tool called Swagger.
