### ISSUE TITLE
[ASPNETCORE] Generation of Interfaces Only?

### ISSUE THREAD

**Issue by Peter554** [swagger-api/swagger-codegen#9141]
##### Description

I'm trying to use the swagger codegen to design and then stub out my Api. On the server side I'm using asp dotnet Core. The generated code is very elaborate but at hard as I try I can't find online any real info about how to control the output. Specifically I would really just like to stub out interfaces for my controllers and generate model definitions. I then want to handle the implementation of those interfaces myself seperately. I also don't need a whole .csproj and .sln really - I just want the interfaces and models. Is this possible? Where can I find documentation relating to the asp dotnet Core options?

##### Swagger-codegen version

https://hub.docker.com/r/swaggerapi/swagger-codegen-cli (latest)

##### Swagger declaration file content or url

https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-minimal.json

##### Command line used for generation

`docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate -i /local/petstore-minimal.json -l as
pnetcore -o /local/gen`

##### Related issues/PRs

Couldn't find any?

##### Suggest a fix/enhancement

More documentation.

**Comment by frantuma** [comment]
To limit the generated output to models and controllers, you can provide system properties as mentioned in [README](https://github.com/swagger-api/swagger-codegen/blob/master/README.md#selective-generation).

Since  `2.4.7` version it is possible to only generate interfaces by adding `interface-only=true` to `additionalProperties`,

Such properties are listed in language options by running

`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l aspnetcore`

the following command limits the output to models and controller interfaces
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore-minimal.json \
   -l aspnetcore \
   -o /tmp/codegen/aspnet \
   --api-package my.api \
   --model-package my.model \
   --additional-properties sourceFolder=src,interface-only=true \
   -D models \
   -D apis \
   -D modelDocs=false \
   -D apiTests=false \
   -D apiDocs=false 
```

please close ticket if this answers your question
