### ISSUE TITLE
No way to start the swagger-jaxrs-server

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-codegen#925]
_From @cosbor11 on June 27, 2015 0:44_

Steps to reproduce: 

1) Enter a valid swagger 2.0 json spec into the editor
2) Go to Generate Server > JaxRS
3) Download zip and unpack
4) Build the project
5) Run the `java -jar swagger-jaxrs-server-1.0.0.jar` command
* ISSUE:  The server doesn't start. Gives this message: 
````
no main manifest attribute, in swagger-jaxrs-server-1.0.0.jar
````

Also, the pom does not reference any MainClass 

Also, there is no README.md or guide to starting this server anywhere.

Ideally, I'd like to start this in a tomcat container, but it looks like it's intended to have an embedded jetty server,   How is this skeleton intended to be used?

-C

_Copied from original issue: swagger-api/swagger-editor#516_

**Comment by wing328** [comment]
Agree that a README would be a good starting on how to use the auto-generated code.

**Comment by olensmar** [comment]
I'll have a look at this - I'm guilty of the latest version of the jaxrs server side gen

**Comment by cosbor11** [comment]
There are many ways to start a jetty server. https://wiki.eclipse.org/Jetty/Howto/Run_Jetty
After much trial and error, I figured out that to start the swagger server skeletons you must run the `mvn jetty:run` command. 

Most people in the java world use Tomcat rather than jetty for actual projects.
