### ISSUE TITLE
JAX-RS generator not yet mature

### ISSUE THREAD

**Issue by giraone** [swagger-api/swagger-codegen#944]
Up to now I used RAML as the specification language for services and raml-for-jaxrs as the code generator. For me this JAX-RS generating solution was very straight forward and mature:
* I used the maven plugin directly in my project's pom.xml.
* I had to configure only my package name and the folder for the generated classes.
* The generator created all my model classes.
* The generator created Java interfaces for all specified resources.
* The only dependency beside standard JEE was "com.fasterxml.jackson" for the serializer.
* And I only had to create my implementation classes for each interface and run the solution in my web container.

The swagger-codegen hasn't yet that kind of maturity. The help states:

```
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l jaxrs

CONFIG OPTIONS
        modelPackage
            package for generated models

        apiPackage
            package for generated api classes

        invokerPackage
            root package for generated code

        groupId
            groupId in generated pom.xml

        artifactId
            artifactId in generated pom.xml

        artifactVersion
            artifact version in generated pom.xml

        sourceFolder
            source folder for generated code
```

So I did a quick test and used the following config.json:

```
{
	"modelPackage": "com.mycompany.testapi.model",
	"apiPackage": "com.mycompany.testapi.api",
	"invokerPackage": "com.mycompany.testapi",
	"groupId": "com.mycompany",
	"artifactId": "testapi-server",
	"artifactVersion": "1.0.0",
	"sourceFolder": "src/main/java"
}
```

and called

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i swagger.json -c config.json -l jaxrs -o my-generated-jaxrs
```

Now target the generated folder contains:

```
$ ls -R
.:
pom.xml  README.md  src

./src:
main

./src/main:
java  webapp

./src/main/java:
com  factories  impl

./src/main/java/com:
mycompany

./src/main/java/com/mycompany:
testapi

./src/main/java/com/mycompany/testapi:
api  model

./src/main/java/com/mycompany/testapi/api:
ApiException.java     ApiResponseMessage.java  TestPetsApi.java
ApiOriginFilter.java  NotFoundException.java   TestPetsApiService.java

./src/main/java/com/mycompany/testapi/model:
ErrorModel.java  NewPet.java  Pet.java

./src/main/java/factories:
com

./src/main/java/factories/com:
mycompany

./src/main/java/factories/com/mycompany:
testapi

./src/main/java/factories/com/mycompany/testapi:
api

./src/main/java/factories/com/mycompany/testapi/api:
TestPetsApiServiceFactory.java

./src/main/java/impl:
com

./src/main/java/impl/com:
mycompany

./src/main/java/impl/com/mycompany:
testapi

./src/main/java/impl/com/mycompany/testapi:
api

./src/main/java/impl/com/mycompany/testapi/api:
TestPetsApiServiceImpl.java

./src/main/webapp:
WEB-INF

./src/main/webapp/WEB-INF:
web.xml
```

First of all, there are several files and folders I do not need. How can I configure the generator to skip, the generation of
* src/main/webapp
* README.md
* impl/
* factories/ 

When I remove the above files, I still cannot use the generated code as is. Because the Api class cannot be compiled, it looks weird and it has additional dependencies - see my //*** comments

```
package com.mycompany.testapi.api;

import com.mycompany.testapi.model.*;
import com.mycompany.testapi.api.TestPetsApiService;
import com.mycompany.testapi.api.factories.TestPetsApiServiceFactory; // **** Wrong import!

import io.swagger.annotations.ApiParam;

import com.sun.jersey.multipart.FormDataParam; //*** Why this?

import com.mycompany.testapi.model.ErrorModel; //*** There is already an import for model.*
import com.mycompany.testapi.model.Pet;
import com.mycompany.testapi.model.NewPet;

import java.util.List;
import com.mycompany.testapi.api.NotFoundException;

import java.io.InputStream;

import com.sun.jersey.core.header.FormDataContentDisposition; //*** Why this?
import com.sun.jersey.multipart.FormDataParam; //*** Why this?

import javax.ws.rs.core.Response;
import javax.ws.rs.*;

@Path("/test-pets")
@Consumes({ "application/json" })
@Produces({ "application/json" })
@io.swagger.annotations.Api(value = "/test-pets", description = "the test-pets API")
public class TestPetsApi  {

   private final TestPetsApiService delegate = TestPetsApiServiceFactory.getTestPetsApi();
...
```
For me, it looks a bit like I am the first user for ```-l jaxrs``` or have I missed sth.?

**Comment by olensmar** [comment]
Thanks - the initial version is meant to compile/run out of the box (hence the pom, readme, etc files), but  I definitely agree it can be improved;
- add command-line option to only generate classes
- add command-line option to not generate implementations 
- generate jax-rs annotated interfaces instead of abstract classes 

If you agree I can create these modifications in a dedicated branch that you could try - interested?

**Comment by giraone** [comment]
Hi Ole,

I would appreciate if you can make the changes and I'll test them.

Hans

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Ole Lensmar <notifications@github.com> </div><div>Datum:06.07.2015  09:34  (GMT+01:00) </div><div>An: swagger-api/swagger-codegen <swagger-codegen@noreply.github.com> </div><div>Cc: giraone <hans.schuell@giraone.com> </div><div>Betreff: Re: [swagger-codegen] JAX-RS generator not yet mature (#944) </div><div>
</div>Thanks - the initial version is meant to compile/run out of the box (hence the pom, readme, etc files), but I definitely agree it can be improved;

add command-line option to only generate classes
add command-line option to not generate implementations
generate jax-rs annotated interfaces instead of abstract classes
If you agree I can create these modifications in a dedicated branch that you could try - interested?

**Comment by affogato** [comment]
Hi,

I have also recently used the JAX-RS module. It built and compiled out of the box for me. However, I want to use the generated code as a library so that it is separated from the custom code of the main project. The project is a web service, and it should be easy to modify the spec, re-generate the library, and then write the implementations in the main project.

I modified the apiServiceFactory mustache file, so that it is possible to inject the service, written in the main project, rather than it using the concrete generated implementation, which is empty every time it is regenerated.

I think this mustache file can be useful for others (included below). 

@olensmar Your suggestions would also do the trick I think, so I too would love to test it.

Thanks
Gideon



```
package {{package}}.factories;

import {{package}}.{{classname}}Service;

public class {{classname}}ServiceFactory {

   private static {{classname}}Service service = null;

   public static void setService({{classname}}Service pService) {
      service = pService;
   } 

   public static {{classname}}Service get{{classname}}()
   {
      return service;
   }
}
```

**Comment by mcory** [comment]
I second these changes. I'm looking into pretty much the same issues - we're using the maven plugin to generate a library we're going to work with in other projects. I've modified the mustache templates to accommodate things correctly, but there's still the *ApiServiceImpl and *ServiceFactory classes floating around (we're going to use Guice for injection, and inject our service impl's into the Api classes in other ways).

Granted, I can surely modify the maven pom file to exclude those classes and the other generated files, but it'd be nice if it was just a configuration option in the plugin.

**Comment by ret0** [comment]
Same issues here +1

**Comment by fehguy** [comment]
The challenge is, there are many different ways to implement a jaxrs server.  The templates are created such that the code will be annotated so that it continues to be self-describing via swagger run-time introspection, and that code changes will be reflected in the description.  This includes more dependencies and a more structured source code layout.

What you're describing is a different goal for the code generation--namely to create a single-shot api which is decoupled from the runtime libraries.  This is easily doable (actually much easier than what we do now) but it is and should be a different template set.

I'll keep this open and we can create another target that creates just the scaffolding rather than the full-blown, runnable server, which is what many (I might even say the majority) of users is looking for.

**Comment by ret0** [comment]
@fehguy Thanks for considering this!

**Comment by mcory** [comment]
For the record - and as a workaround for anyone else with the same desires - we're working with a multi-module project (that's by choice outside of swagger usage). We have the swagger resources in one module as a resource module using the assembly plugin, and two additional modules that use it as a dependency, unzip the resource, generate the code, and generate their jars by excluding the stuff that doesn't belong in their domain. I'm honestly not sure how I accomplished it - mainly just copy/paste and tweak from examples online - but it wasn't terribly difficult, and it sticks to the "1 artifact per pom" standard.

**Comment by garydgregory** [comment]
SwaggerCodegen 2.1.4 generates code that does not compile. The most egregious problem is that the folders are messed up, for example, code generated in the package "com.seagullsw.test.swagger.api.impl" in generated in "src\gen\java\impl\com\seagullsw\test\swagger\api\ArrayOfAllPrimitiveTypesInBodyApiServiceImpl.java" instead of "src\gen\java\com\seagullsw\test\swagger\api\impl\ArrayOfAllPrimitiveTypesInBodyApiServiceImpl.java"

There happens for other packages as well.

**Comment by wing328** [comment]
@garethjevans I believe the issue (on Windows) has been addressed in the latest master. Please pull the latest and give it a try.

**Comment by garydgregory** [comment]
Well, that could well be because it does not happen anymore and I am using locally built snapshots. What I did notice is that if my Swagger file is not valid (based on the JSON schema) then the JAXRS code generator will not fail and instead will generate code that does not compile.

**Comment by K76154** [comment]
Can we at least change the abstract class to interface first? That looks weird, and we all know abstract class is much less flexible then interface

**Comment by fehguy** [comment]
@K76154 can you please open a different ticket for your request?

@garydgregory we did have to make a call, if there's an issue in the specification that you provide, to either generate and allow users to fix the code, or just fail.  We went with the former because it does add a lot more value.  So if you're still seeing issues, please raise them.

**Comment by K76154** [comment]
Create issue #2672 for this
