### ISSUE TITLE
[Python] When using allOf, the parent class attributes are not set on the child model instance

### ISSUE THREAD

**Issue by paulcgt** [swagger-api/swagger-codegen#9480]
##### Description
When using Swagger allOf, the python generator correctly creates the parent and child model objects. However, when calling the API that returns a child model instance, the attributes that exist on the parent are not set on the child because the parent's swagger_types and attribute_names are not merged into the child's and so the deserializer in ApiClient does not map the JSON data into the child class instance.

##### Swagger-codegen version
3.0.8

##### Swagger declaration file content or url
ApiGetBasic [parent]
ApiGet [child]

https://docops.ca.com/ca-api-developer-portal-enhanced-experience/4-3/en/files/535737114/535737116/1/1554501612987/swagger-papi-431.json

##### Command line used for generation
```
java -jar {library_location}/swagger-codegen-cli-3.0.8.jar generate -l python -o . -c ./swagger-codegen.conf -i ./swagger.json 
```
##### Steps to reproduce
It's quite hard, unless you have an implementation of the API.

##### Related issues/PRs
I haven't found anything related.

##### Suggest a fix/enhancement
I've tested two fixes. The first was to change the client model and merge in the parent swagger_types and attribute_names into the child's, and then to call the parent's __init__ from within the child's __init__. This worked.

I'm not extremely experience in python, but I think a more elegant solution is to make the following change in ApiClient.deserialize() as follows:

```
def deserialize(self, response, response_type)
    ...
    child = self.__deserialize(data, response_type)
    for base in child.__class__.__bases__:
        if not base.__name__ == 'object':
            parent = self.__deserialize(data, base.__name__)
            child.__dict__ = {**child.__dict__, **parent.__dict__}

    return child
```

**Comment by shauntarves** [comment]
Any update on this? I'm having the exact same issue.

The problem absolutely seems to originate with the `swagger_types` field declaration. In both python2 and python3, when a _mutable_ object type (say, a `dict`) is defined _statically_ in a class, the subclass instance will *replace* the parent class definition with its own. So a child class that only contains 1 field (because that's all it adds to the parent) in the `swagger_types` object will end up with a `swagger_types` object with *only* that 1 field - not the amalgamation of the parent's `swagger_types` plus its own.

This basically renders the generated python client totally unusable if there is even the slightest bit of inheritance.

**Comment by paulcgt** [comment]
My second fix only works for GET requests and so it's not ideal. The first fix works for GET and POST requests, but that requires someone to build it into the generator.

I abandoned this generator and wrote the code myself. That ended up being a better option for me... Albeit somewhat painful.

Sorry that I don't have a better solution for you. Someone just needs to update the generator, or you can update the generated code as suggested... Although I guess that can be perilous ito future maintenance.

**Comment by dong-brian** [comment]
This seems to be fixed already in master

**Comment by HugoMario** [comment]
hey @paulcgt , i added a PR solving this issue. for codegen 3.0.x. please check when you have a chance and let us know if there is something wrong.
