### ISSUE TITLE
snapshot version typo?

### ISSUE THREAD

**Issue by jkoorts** [swagger-api/swagger-codegen#9585]
Cloning the project I see for instance  <version>2.4.-SNAPSHOT</version> in pom.xml.bash (and elsewhere)

I guess it should be 2.4.8-SNAPSHOT?

Would be great if you can write some doc on how to do your own release build because a snapshot build is not allowed for upload to Nexus.

**Comment by frantuma** [comment]
thanks for reporting this! fixed in #9062 

as for the "internal release" to some nexus repo (if I get this right, in order to use a snapshot version before the official release, but not depends on snapshots?), there's no particular step other than providing the dist management in poms and bumping the version. Closing the ticket, please reopen if this doesn't answer your question
