### ISSUE TITLE
[Java] [okhttp-gson] Updating OkHttp to version 3.x

### ISSUE THREAD

**Issue by nicktrav** [swagger-api/swagger-codegen#9606]
##### Description

I'd like to gauge the appetite for upgrading the version of OkHttp in the `okhttp-gson` module to a version in the 3.x series. Version 2.7.5 dates back to Feb 26, 2016, and there hasn't been an update since then.

Happy to put together a patch just for this module, but I first wanted to check to see if this is something that makes sense? Would this type of change need to wait for a major release of swagger-codegen, or could it be something that's released in a minor version - from what I can tell there would be API changes given the OkHttp package name is different in version 3.x and the API in okhttp-gson exposes some OkHttp classes.

##### Swagger-codegen version

3.0.10.

##### Related issues/PRs

This would help make progress on kubernetes-client/java#430. We'd love to be using a more recent version of OkHttp!

##### Suggest a fix/enhancement

Would be willing to offer up a patch (I have something already) if there's someone that would be willing to guide me through the process (my first time committing to this repo, so I might be missing some subtleties).

**Comment by frantuma** [comment]
Thanks for this, a patch/PR is more than welcome!

this basically would mean touching related java class `JavaClientCodegen` (in [3.0.0 branch](https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/java/io/swagger/codegen/v3/generators/java/JavaClientCodegen.java) if supporting OpenApi 3.x), providing a new version option and updating relevant code and [related template files](https://github.com/swagger-api/swagger-codegen-generators/tree/master/src/main/resources/handlebars/Java/libraries/okhttp-gson)

In case the differences are massive, it could make sense to add a new library option `okhttp-gson-v3` instead of modifying the current one.

this would still involve `JavaClientCodegen`, adding there a library and related template files in new directory `okhttp-gson-v3` in [this resource dir](https://github.com/swagger-api/swagger-codegen-generators/tree/master/src/main/resources/handlebars/Java/libraries)

**Comment by heng4fun** [comment]
Any progress about this?

**Comment by kolle1986** [comment]
Anything yet?

**Comment by matpag** [comment]
Any news about this? 
OkHttp 2.7.5 is 6 years old now, I don't know if generating the java client with Swagger is the right thing at this point...

**Comment by meena561** [comment]
Any update on this?
