### ISSUE TITLE
CodeGen SwaggerParser validation is different from their online validation

### ISSUE THREAD

**Issue by galagar** [swagger-api/swagger-codegen#963]
Swagger online validation is almost successful for all the swagger document, If you use the same document to parse or import using Swagger CodeGen it fails or returns null Swagger object. Which leads to big gap in the community. 

It would be great if system follows same validation mechanism on both online swagger validator and swagger codeGen.

**Comment by earth2marsh** [comment]
I think the problem here may be that the validator isn't thorough enough to cover cases that break codegen, so you end up with specs that appear to be valid but that don't create the expected Swagger object when passed to codegen. 

I'm not sure what the right answer is, but I'm sure @fehguy has an opinion… :)

**Comment by wing328** [comment]
@galagar currently there are some limitations with Swagger-Codegen based on my understanding. One example is lack of support for inline schema: https://github.com/swagger-api/swagger-codegen/issues/354

For the time being, I would recommend you to open an issue and provide the error message as well as the swagger spec for repeating the issue (assuming the spec can be shared publicly).

**Comment by wing328** [comment]
@galagar closing this issue as we've not heard any update from. There has been a lot of improvements to Swagger-Parser and Swagger-Codegen so please pull the latest swagger-codegen to see if you still encounter the same issue.
