### ISSUE TITLE
Generated PHP models do not support inheritance

### ISSUE THREAD

**Issue by danny-cassidy** [swagger-api/swagger-codegen#972]
The PHP model.mustache file does not support inheritance: 

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/model.mustache#L31

```
class {{classname}} implements ArrayAccess {
  static $swaggerTypes = array(
      {{#vars}}'{{name}}' => '{{{datatype}}}'{{#hasMore}},
      {{/hasMore}}{{/vars}}
  );

```

**Comment by wing328** [comment]
@danny-cassidy you're correct in saying that PHP (and many other languages) does not support inheritance in Swagger-Codegen.

May I know how critical you need the feature ?

**Comment by danny-cassidy** [comment]
I just assumed (incorrectly) that the all languages were consistent in terms of functionality and conformity to Swagger 2.0 specification. Is there any documentation anywhere about what is supported across the supported languages? Also, a potential roadmap? 

I know this is probably an ongoing conversation from the sound of this [post](http://swagger.io/next-steps-for-swagger-governance/).

**Comment by wing328** [comment]
@danny-cassidy thanks for the suggestion. Currently, I'm not aware of any documentation to show the functionality of API clients in different languages but I agree with you it would definitely help people to understand what feature is or is not supported by Swagger-Codegen.

For roadmap, I'm not aware of any either. I think the reason is partly because some features are contributed/driven by the community via PR. Another reason based on my guess is that the author of this project, Tony Tam, is too busy to put down a roadmap for Swagger-Codegen.

In your case, do you already have a SwaggerSpec that leverages `allOf` and/or `discriminator` and you would like to generate the PHP client for it ?

Ref: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#composition-and-inheritance-polymorphism

**Comment by danny-cassidy** [comment]
Thanks for your quick response. That all makes sense. 

> In your case, do you already have a SwaggerSpec that leverages allOf and/or discriminator and you 
> would like to generate the PHP client for it ? 

Yes, that is correct. I was generating the Java client while revising the my SwaggerSpec and all looked good in terms of the allOf/discriminator definitions being modeled correctly. Then started to look at other language clients. I just happened to start with the PHP client.

**Comment by wing328** [comment]
We might be able to add support for model composition (allOf) but not inheritance this week and will keep you posted.

**Comment by wing328** [comment]
@danny-cassidy The PR to support `allOf` (model composition) has been merged into `develop_2.0`. Do you mind giving it a try to see if meets your requirement?

**Comment by fehguy** [comment]
Please reopen if you're still having an issue @danny-cassidy

**Comment by arnested** [comment]
I made an attempt at implementing inheritance in the PHP client model code: #1440. It also includes a pointer to some initial work on introducing polymorphism in the PHP client api part.
