### ISSUE TITLE
[C#] Compilation error when compiling with Mono compiler

### ISSUE THREAD

**Issue by who** [swagger-api/swagger-codegen#985]
When I compile with the Mono compiler like so:

```
mcs -sdk:4.5 -r:bin/Newtonsoft.Json.dll,bin/RestSharp.dll,System.Runtime.Serialization.dll -target:library -out:bin/out-x86x64.dll -recurse:src/*.cs -doc:bin/out-x86x64.xml -platform:anycpu
```
I get this:

```
src/main/csharp/IO/Swagger/Client/ApiClient.cs(165,20): error CS0122: `System.Net.HttpUtility' is inaccessible due to its protection level
```

The error is originating from here: https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache#L163-L166

I recommend we use `Uri.EscapeDataString` instead of `HttpUtility.UrlEncode`.

**Comment by lakeba** [comment]
Change the line 165 from /modules/swagger-codegen/src/main/resources/csharp/Apiclient.mustache with:

return RestSharp.Contrib.HttpUtility.UrlEncode(str);

then> mV clean package

This will solve your problem.

Giuseppe


On 17 Jul 2015, at 10:33 am, Andrew B <notifications@github.com> wrote:

When I compile with the Mono compiler like so:

mcs -sdk:4.5 -r:bin/Newtonsoft.Json.dll,bin/RestSharp.dll,System.Runtime.Serialization.dll -target:library -out:bin/out-x86x64.dll -recurse:src/*.cs -doc:bin/out-x86x64.xml -platform:anycpu
I get this:

src/main/csharp/IO/Swagger/Client/ApiClient.cs(165,20): error CS0122: `System.Net.HttpUtility' is inaccessible due to its protection level
The error is originating from here: https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache#L163-L166 <https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/resources/csharp/ApiClient.mustache#L163-L166>
I recommend we use Uri.EscapeDataString instead of HttpUtility.UrlEncode.

**Comment by wing328** [comment]
@who thanks for reporting the issue. I'm totally ok with `Uri.EscapeDataString` if it solves the problem.

**Comment by who** [comment]
After looking into this, the recommendation by @lakeba (using `RestSharp.Contrib.HttpUtility.UrlEncode(str)` instead of `Uri.EscapeDataString`) is a better approach.  I will submit a PR.
