### ISSUE TITLE
With Swagger 2.0, usage of allOf generates bad java code

### ISSUE THREAD

**Issue by maheshcamath** [swagger-api/swagger-codegen#9963]
##### Description

Code generated from java code gen doesn't compile.

![image](https://user-images.githubusercontent.com/17781873/71871238-9245c200-313e-11ea-8454-d9b47ad1fad5.png)

##### Swagger-codegen version

2.4.11

##### Swagger declaration file content or url

Download from 
[PetStore_anyOf_java_issue.zip](https://github.com/swagger-api/swagger-codegen/files/4029007/PetStore_anyOf_java_issue.zip)

##### Command line used for generation
Downloaded
http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.11/swagger-codegen-cli-2.4.11.jar

 java -jar swagger-codegen-cli-2.4.11.jar generate -i PetStore_anyOf_issue.json -l java -o test_java

##### Steps to reproduce

1. Take the attached swagger definition
[PetStore_anyOf_java_issue.zip](https://github.com/swagger-api/swagger-codegen/files/4029007/PetStore_anyOf_java_issue.zip)

2. Generate java code 
 java -jar swagger-codegen-cli-2.4.11.jar generate -i PetStore_anyOf_issue.json -l java -o test_java

3. Code doesn't compile.

##### Related issues/PRs
None

##### Suggest a fix/enhancement
None

**Comment by HugoMario** [comment]
Hello @maheshcamath , this error happen because discriminator is string type according to https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object

however the discriminator type in this output is a enum of strings. So, there is a mismatch typing that creates this error.

as a solution i added [this PR ](https://github.com/swagger-api/swagger-codegen/pull/9983) to skip the discriminator assignment for enums. 

So, going to for now, if the issue is still present, please let me know.
